// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Liveness probe — a placeholder command so the bindings pipeline has
	 *  something to export. Replaced by the real device commands in a later step.
	 */
	getHealth: () => __TAURI_INVOKE<string>("get_health"),
};

