// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	startDiscovery: () => __TAURI_INVOKE<void>("start_discovery"),
	stopDiscovery: () => __TAURI_INVOKE<void>("stop_discovery"),
	/**
	 *  Current scan state and discovered devices, as a JSON-encoded
	 *  `{ scanning, devices }` document.
	 */
	getDiscoveredDevices: () => typedError<string, CommandError>(__TAURI_INVOKE("get_discovered_devices")),
	/**
	 *  Validates an IP and probes it for a BleBox `/info` payload. Returns the
	 *  `device` object as a JSON string on success.
	 */
	probeDevice: (ip: string) => typedError<string, CommandError>(__TAURI_INVOKE("probe_device", { ip })),
	deviceInfo: (ip: string) => typedError<string, CommandError>(__TAURI_INVOKE("device_info", { ip })),
	deviceStateExtended: (ip: string) => typedError<string, CommandError>(__TAURI_INVOKE("device_state_extended", { ip })),
	deviceActionsState: (ip: string) => typedError<string, CommandError>(__TAURI_INVOKE("device_actions_state", { ip })),
	/**
	 *  Persists one action via `POST /api/actions/set` (single-action upsert).
	 *  `action` is the JSON-encoded action object.
	 */
	deviceSaveAction: (ip: string, action: string) => typedError<null, CommandError>(__TAURI_INVOKE("device_save_action", { ip, action })),
	/**
	 *  Writes the relay-state document via `POST /state`. `payload` is the
	 *  JSON-encoded body — typically `{"relays":[{"relay":N,"state":0|1|2}]}`
	 *  (`2` toggles). Used by the Device tab's on/off switch.
	 */
	deviceSetState: (ip: string, payload: string) => typedError<null, CommandError>(__TAURI_INVOKE("device_set_state", { ip, payload })),
	/**
	 *  Triggers the device's OTA firmware update via `POST /api/ota/update`. The
	 *  spec accepts no body; the device pulls the new firmware from BleBox's
	 *  cloud over its tunnel. Returns when the device has accepted the request
	 *  (does not wait for the install).
	 */
	deviceOtaUpdate: (ip: string) => typedError<null, CommandError>(__TAURI_INVOKE("device_ota_update", { ip })),
	/**  Lists nearby access points via `GET /api/wifi/scan` (`{ap: [...]}`). */
	deviceWifiScan: (ip: string) => typedError<string, CommandError>(__TAURI_INVOKE("device_wifi_scan", { ip })),
	/**
	 *  Joins a network via `POST /api/wifi/connect`. `payload` is the JSON-encoded
	 *  `{ ssid, pwd }` (`pwd` null/empty for an open network). Returns the device's
	 *  `{ ssid, station_status }` response.
	 */
	deviceWifiConnect: (ip: string, payload: string) => typedError<string, CommandError>(__TAURI_INVOKE("device_wifi_connect", { ip, payload })),
	deviceNetwork: (ip: string) => typedError<string, CommandError>(__TAURI_INVOKE("device_network", { ip })),
	/**
	 *  Updates the device's internal access point. `settings` is the JSON-encoded
	 *  `network` object.
	 */
	deviceSetNetwork: (ip: string, settings: string) => typedError<null, CommandError>(__TAURI_INVOKE("device_set_network", { ip, settings })),
	deviceSettingsState: (ip: string) => typedError<string, CommandError>(__TAURI_INVOKE("device_settings_state", { ip })),
	/**
	 *  Updates device settings. `settings` is the JSON-encoded inner object —
	 *  e.g. `{"tunnel":{"enabled":1}}` — and is sent wrapped as
	 *  `{"settings": <settings>}` to `POST /api/settings/set`.
	 */
	deviceSettingsSet: (ip: string, settings: string) => typedError<null, CommandError>(__TAURI_INVOKE("device_settings_set", { ip, settings })),
};

/* Types */
/**
 *  A structured command failure. `code` is a stable machine-readable tag;
 *  `message` is human-readable.
 */
export type CommandError = {
	code: string,
	message: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

