/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevicesRouteRouteImport } from './routes/devices/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesIndexRouteImport } from './routes/devices/index'
import { Route as DevicesAddRouteImport } from './routes/devices/add'
import { Route as DevicesDeviceIpRouteImport } from './routes/devices/$deviceIp'
import { Route as DevicesDeviceIpActionsJsonRouteImport } from './routes/devices/$deviceIp.actions.json'
import { Route as DevicesDeviceIpActionsInputIdNewRouteImport } from './routes/devices/$deviceIp.actions.$inputId.new'
import { Route as DevicesDeviceIpActionsInputIdActionIdEditRouteImport } from './routes/devices/$deviceIp.actions.$inputId.$actionId.edit'

const DevicesRouteRoute = DevicesRouteRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevicesRouteRoute,
} as any)
const DevicesAddRoute = DevicesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DevicesRouteRoute,
} as any)
const DevicesDeviceIpRoute = DevicesDeviceIpRouteImport.update({
  id: '/$deviceIp',
  path: '/$deviceIp',
  getParentRoute: () => DevicesRouteRoute,
} as any)
const DevicesDeviceIpActionsJsonRoute =
  DevicesDeviceIpActionsJsonRouteImport.update({
    id: '/actions/json',
    path: '/actions/json',
    getParentRoute: () => DevicesDeviceIpRoute,
  } as any)
const DevicesDeviceIpActionsInputIdNewRoute =
  DevicesDeviceIpActionsInputIdNewRouteImport.update({
    id: '/actions/$inputId/new',
    path: '/actions/$inputId/new',
    getParentRoute: () => DevicesDeviceIpRoute,
  } as any)
const DevicesDeviceIpActionsInputIdActionIdEditRoute =
  DevicesDeviceIpActionsInputIdActionIdEditRouteImport.update({
    id: '/actions/$inputId/$actionId/edit',
    path: '/actions/$inputId/$actionId/edit',
    getParentRoute: () => DevicesDeviceIpRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRouteRouteWithChildren
  '/devices/$deviceIp': typeof DevicesDeviceIpRouteWithChildren
  '/devices/add': typeof DevicesAddRoute
  '/devices/': typeof DevicesIndexRoute
  '/devices/$deviceIp/actions/json': typeof DevicesDeviceIpActionsJsonRoute
  '/devices/$deviceIp/actions/$inputId/new': typeof DevicesDeviceIpActionsInputIdNewRoute
  '/devices/$deviceIp/actions/$inputId/$actionId/edit': typeof DevicesDeviceIpActionsInputIdActionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices/$deviceIp': typeof DevicesDeviceIpRouteWithChildren
  '/devices/add': typeof DevicesAddRoute
  '/devices': typeof DevicesIndexRoute
  '/devices/$deviceIp/actions/json': typeof DevicesDeviceIpActionsJsonRoute
  '/devices/$deviceIp/actions/$inputId/new': typeof DevicesDeviceIpActionsInputIdNewRoute
  '/devices/$deviceIp/actions/$inputId/$actionId/edit': typeof DevicesDeviceIpActionsInputIdActionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRouteRouteWithChildren
  '/devices/$deviceIp': typeof DevicesDeviceIpRouteWithChildren
  '/devices/add': typeof DevicesAddRoute
  '/devices/': typeof DevicesIndexRoute
  '/devices/$deviceIp/actions/json': typeof DevicesDeviceIpActionsJsonRoute
  '/devices/$deviceIp/actions/$inputId/new': typeof DevicesDeviceIpActionsInputIdNewRoute
  '/devices/$deviceIp/actions/$inputId/$actionId/edit': typeof DevicesDeviceIpActionsInputIdActionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/devices/$deviceIp'
    | '/devices/add'
    | '/devices/'
    | '/devices/$deviceIp/actions/json'
    | '/devices/$deviceIp/actions/$inputId/new'
    | '/devices/$deviceIp/actions/$inputId/$actionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices/$deviceIp'
    | '/devices/add'
    | '/devices'
    | '/devices/$deviceIp/actions/json'
    | '/devices/$deviceIp/actions/$inputId/new'
    | '/devices/$deviceIp/actions/$inputId/$actionId/edit'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/devices/$deviceIp'
    | '/devices/add'
    | '/devices/'
    | '/devices/$deviceIp/actions/json'
    | '/devices/$deviceIp/actions/$inputId/new'
    | '/devices/$deviceIp/actions/$inputId/$actionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRouteRoute: typeof DevicesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/': {
      id: '/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/add': {
      id: '/devices/add'
      path: '/add'
      fullPath: '/devices/add'
      preLoaderRoute: typeof DevicesAddRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/$deviceIp': {
      id: '/devices/$deviceIp'
      path: '/$deviceIp'
      fullPath: '/devices/$deviceIp'
      preLoaderRoute: typeof DevicesDeviceIpRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/$deviceIp/actions/json': {
      id: '/devices/$deviceIp/actions/json'
      path: '/actions/json'
      fullPath: '/devices/$deviceIp/actions/json'
      preLoaderRoute: typeof DevicesDeviceIpActionsJsonRouteImport
      parentRoute: typeof DevicesDeviceIpRoute
    }
    '/devices/$deviceIp/actions/$inputId/new': {
      id: '/devices/$deviceIp/actions/$inputId/new'
      path: '/actions/$inputId/new'
      fullPath: '/devices/$deviceIp/actions/$inputId/new'
      preLoaderRoute: typeof DevicesDeviceIpActionsInputIdNewRouteImport
      parentRoute: typeof DevicesDeviceIpRoute
    }
    '/devices/$deviceIp/actions/$inputId/$actionId/edit': {
      id: '/devices/$deviceIp/actions/$inputId/$actionId/edit'
      path: '/actions/$inputId/$actionId/edit'
      fullPath: '/devices/$deviceIp/actions/$inputId/$actionId/edit'
      preLoaderRoute: typeof DevicesDeviceIpActionsInputIdActionIdEditRouteImport
      parentRoute: typeof DevicesDeviceIpRoute
    }
  }
}

interface DevicesDeviceIpRouteChildren {
  DevicesDeviceIpActionsJsonRoute: typeof DevicesDeviceIpActionsJsonRoute
  DevicesDeviceIpActionsInputIdNewRoute: typeof DevicesDeviceIpActionsInputIdNewRoute
  DevicesDeviceIpActionsInputIdActionIdEditRoute: typeof DevicesDeviceIpActionsInputIdActionIdEditRoute
}

const DevicesDeviceIpRouteChildren: DevicesDeviceIpRouteChildren = {
  DevicesDeviceIpActionsJsonRoute: DevicesDeviceIpActionsJsonRoute,
  DevicesDeviceIpActionsInputIdNewRoute: DevicesDeviceIpActionsInputIdNewRoute,
  DevicesDeviceIpActionsInputIdActionIdEditRoute:
    DevicesDeviceIpActionsInputIdActionIdEditRoute,
}

const DevicesDeviceIpRouteWithChildren = DevicesDeviceIpRoute._addFileChildren(
  DevicesDeviceIpRouteChildren,
)

interface DevicesRouteRouteChildren {
  DevicesDeviceIpRoute: typeof DevicesDeviceIpRouteWithChildren
  DevicesAddRoute: typeof DevicesAddRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
}

const DevicesRouteRouteChildren: DevicesRouteRouteChildren = {
  DevicesDeviceIpRoute: DevicesDeviceIpRouteWithChildren,
  DevicesAddRoute: DevicesAddRoute,
  DevicesIndexRoute: DevicesIndexRoute,
}

const DevicesRouteRouteWithChildren = DevicesRouteRoute._addFileChildren(
  DevicesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRouteRoute: DevicesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
