// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tunnel } from './Tunnel';
import {
    TunnelFromJSON,
    TunnelFromJSONTyped,
    TunnelToJSON,
    TunnelToJSONTyped,
} from './Tunnel';
import type { StatusLed } from './StatusLed';
import {
    StatusLedFromJSON,
    StatusLedFromJSONTyped,
    StatusLedToJSON,
    StatusLedToJSONTyped,
} from './StatusLed';
import type { StateExtendedGet200ResponseButtonbox } from './StateExtendedGet200ResponseButtonbox';
import {
    StateExtendedGet200ResponseButtonboxFromJSON,
    StateExtendedGet200ResponseButtonboxFromJSONTyped,
    StateExtendedGet200ResponseButtonboxToJSON,
    StateExtendedGet200ResponseButtonboxToJSONTyped,
} from './StateExtendedGet200ResponseButtonbox';

/**
 * 
 * @export
 * @interface ApiSettingsSetPostRequestSettings
 */
export interface ApiSettingsSetPostRequestSettings {
    /**
     * **Name** of BleBox device/controller
     * @type {string}
     * @memberof ApiSettingsSetPostRequestSettings
     */
    deviceName?: string;
    /**
     * 
     * @type {Tunnel}
     * @memberof ApiSettingsSetPostRequestSettings
     */
    tunnel?: Tunnel;
    /**
     * 
     * @type {StatusLed}
     * @memberof ApiSettingsSetPostRequestSettings
     */
    statusLed?: StatusLed;
    /**
     * 
     * @type {StateExtendedGet200ResponseButtonbox}
     * @memberof ApiSettingsSetPostRequestSettings
     */
    buttonbox?: StateExtendedGet200ResponseButtonbox;
}

/**
 * Check if a given object implements the ApiSettingsSetPostRequestSettings interface.
 */
export function instanceOfApiSettingsSetPostRequestSettings(value: object): value is ApiSettingsSetPostRequestSettings {
    return true;
}

export function ApiSettingsSetPostRequestSettingsFromJSON(json: any): ApiSettingsSetPostRequestSettings {
    return ApiSettingsSetPostRequestSettingsFromJSONTyped(json, false);
}

export function ApiSettingsSetPostRequestSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsSetPostRequestSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
        'tunnel': json['tunnel'] == null ? undefined : TunnelFromJSON(json['tunnel']),
        'statusLed': json['statusLed'] == null ? undefined : StatusLedFromJSON(json['statusLed']),
        'buttonbox': json['buttonbox'] == null ? undefined : StateExtendedGet200ResponseButtonboxFromJSON(json['buttonbox']),
    };
}

export function ApiSettingsSetPostRequestSettingsToJSON(json: any): ApiSettingsSetPostRequestSettings {
    return ApiSettingsSetPostRequestSettingsToJSONTyped(json, false);
}

export function ApiSettingsSetPostRequestSettingsToJSONTyped(value?: ApiSettingsSetPostRequestSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceName': value['deviceName'],
        'tunnel': TunnelToJSON(value['tunnel']),
        'statusLed': StatusLedToJSON(value['statusLed']),
        'buttonbox': StateExtendedGet200ResponseButtonboxToJSON(value['buttonbox']),
    };
}

