// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * **General** information about device
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * **Name** of BleBox device/controller
     * @type {string}
     * @memberof Device
     */
    deviceName?: string;
    /**
     * Product name for informational purpose only - do not use it in any application logic
     * @type {string}
     * @memberof Device
     */
    product?: string;
    /**
     * **API type** of BleBox device - it indicate what **device-specific API** should be used
     * @type {string}
     * @memberof Device
     */
    type?: string;
    /**
     * **API level** of BleBox device - it indicate what version of **common and device-specific API** should be used
     * @type {string}
     * @memberof Device
     */
    apiLevel?: string;
    /**
     * Hardware version for informational purpose only - do not use it in any application logic
     * @type {string}
     * @memberof Device
     */
    hv?: string;
    /**
     * Firmware version for informational purpose only - do not use it in any application logic
     * @type {string}
     * @memberof Device
     */
    fv?: string;
    /**
     * Unique identification number of BleBox device
     * @type {string}
     * @memberof Device
     */
    id?: string;
    /**
     * IPv4 of BleBox device connected to local WiFi network. <br> **Empty string** indicates that **no WiFi network was connected**
     * @type {string}
     * @memberof Device
     */
    ip?: string;
}

/**
 * Check if a given object implements the Device interface.
 */
export function instanceOfDevice(value: object): value is Device {
    return true;
}

export function DeviceFromJSON(json: any): Device {
    return DeviceFromJSONTyped(json, false);
}

export function DeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Device {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
        'product': json['product'] == null ? undefined : json['product'],
        'type': json['type'] == null ? undefined : json['type'],
        'apiLevel': json['apiLevel'] == null ? undefined : json['apiLevel'],
        'hv': json['hv'] == null ? undefined : json['hv'],
        'fv': json['fv'] == null ? undefined : json['fv'],
        'id': json['id'] == null ? undefined : json['id'],
        'ip': json['ip'] == null ? undefined : json['ip'],
    };
}

export function DeviceToJSON(json: any): Device {
    return DeviceToJSONTyped(json, false);
}

export function DeviceToJSONTyped(value?: Device | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceName': value['deviceName'],
        'product': value['product'],
        'type': value['type'],
        'apiLevel': value['apiLevel'],
        'hv': value['hv'],
        'fv': value['fv'],
        'id': value['id'],
        'ip': value['ip'],
    };
}

