// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TunnelStatus } from './TunnelStatus';
import {
    TunnelStatusFromJSON,
    TunnelStatusFromJSONTyped,
    TunnelStatusToJSON,
    TunnelStatusToJSONTyped,
} from './TunnelStatus';
import type { StationStatus } from './StationStatus';
import {
    StationStatusFromJSON,
    StationStatusFromJSONTyped,
    StationStatusToJSON,
    StationStatusToJSONTyped,
} from './StationStatus';

/**
 * All information connected with network
 * @export
 * @interface Network
 */
export interface Network {
    /**
     * SSID of connected WiFi network. <br> **Empty string** indicates that **no WiFi network was selected**
     * @type {string}
     * @memberof Network
     */
    ssid?: string;
    /**
     * BSSID of connected WiFi network. <br> **Empty string** indicates that **no WiFi network was found**
     * @type {string}
     * @memberof Network
     */
    bssid?: string;
    /**
     * IPv4 of BleBox device connected to local WiFi network. <br> **Empty string** indicates that **no WiFi network was connected**
     * @type {string}
     * @memberof Network
     */
    ip?: string;
    /**
     * MAC address of BleBox device. <br> This interface connect to Access Point (to local WiFi network)
     * @type {string}
     * @memberof Network
     */
    mac?: string;
    /**
     * 
     * @type {StationStatus}
     * @memberof Network
     */
    stationStatus?: StationStatus;
    /**
     * 
     * @type {TunnelStatus}
     * @memberof Network
     */
    tunnelStatus?: TunnelStatus;
    /**
     * <br>Parameter that show if **internal** WiFi Access Point is enabled, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**false**</td> <td>disabled</td> </tr> <tr> <td>**true**</td> <td>enabled</td> </tr> </table><br> If **false** - **apSSID** and **apPasswd** can be ignored.
     * @type {boolean}
     * @memberof Network
     */
    apEnable?: boolean;
    /**
     * SSID of **internal** WiFi access Point
     * @type {string}
     * @memberof Network
     */
    apSSID?: string;
    /**
     * Password of **internal** WiFi Access Point. <br> WPA2-PSK is used. <br>Empty string or 'null' indicates that internal AP is set to open mode (without password).
     * @type {string}
     * @memberof Network
     */
    apPasswd?: string | null;
    /**
     * Channel of **internal** WiFi Access Point. **If device is connected to local WiFi** network then internal WiFi **channel is the same** as local WiFi Access Point's channel
     * @type {number}
     * @memberof Network
     */
    channel?: number;
}



/**
 * Check if a given object implements the Network interface.
 */
export function instanceOfNetwork(value: object): value is Network {
    return true;
}

export function NetworkFromJSON(json: any): Network {
    return NetworkFromJSONTyped(json, false);
}

export function NetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Network {
    if (json == null) {
        return json;
    }
    return {
        
        'ssid': json['ssid'] == null ? undefined : json['ssid'],
        'bssid': json['bssid'] == null ? undefined : json['bssid'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'mac': json['mac'] == null ? undefined : json['mac'],
        'stationStatus': json['station_status'] == null ? undefined : StationStatusFromJSON(json['station_status']),
        'tunnelStatus': json['tunnel_status'] == null ? undefined : TunnelStatusFromJSON(json['tunnel_status']),
        'apEnable': json['apEnable'] == null ? undefined : json['apEnable'],
        'apSSID': json['apSSID'] == null ? undefined : json['apSSID'],
        'apPasswd': json['apPasswd'] == null ? undefined : json['apPasswd'],
        'channel': json['channel'] == null ? undefined : json['channel'],
    };
}

export function NetworkToJSON(json: any): Network {
    return NetworkToJSONTyped(json, false);
}

export function NetworkToJSONTyped(value?: Network | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ssid': value['ssid'],
        'bssid': value['bssid'],
        'ip': value['ip'],
        'mac': value['mac'],
        'station_status': StationStatusToJSON(value['stationStatus']),
        'tunnel_status': TunnelStatusToJSON(value['tunnelStatus']),
        'apEnable': value['apEnable'],
        'apSSID': value['apSSID'],
        'apPasswd': value['apPasswd'],
        'channel': value['channel'],
    };
}

