// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>Status of current **WiFi connection**, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>Not configured</td> </tr> <tr> <td>**1**</td> <td>Connecting</td> </tr> <tr> <td>**2**</td> <td>Wrong password</td> </tr> <tr> <td>**3**</td> <td>WiFi network not found</td> </tr> <tr> <td>**4**</td> <td>Communication with WiFi network failed</td> </tr> <tr> <td>**5**</td> <td>Connected</td> </tr> </table>
 * @export
 */
export const StationStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type StationStatus = typeof StationStatus[keyof typeof StationStatus];


export function instanceOfStationStatus(value: any): boolean {
    for (const key in StationStatus) {
        if (Object.prototype.hasOwnProperty.call(StationStatus, key)) {
            if (StationStatus[key as keyof typeof StationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StationStatusFromJSON(json: any): StationStatus {
    return StationStatusFromJSONTyped(json, false);
}

export function StationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationStatus {
    return json as StationStatus;
}

export function StationStatusToJSON(value?: StationStatus | null): any {
    return value as any;
}

export function StationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): StationStatus {
    return value as StationStatus;
}

