// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InputStruct } from './InputStruct';
import {
    InputStructFromJSON,
    InputStructFromJSONTyped,
    InputStructToJSON,
    InputStructToJSONTyped,
} from './InputStruct';

/**
 * 
 * @export
 * @interface StateGet200Response
 */
export interface StateGet200Response {
    /**
     * List of all available inputs with corresponding states.
     * @type {Array<InputStruct>}
     * @memberof StateGet200Response
     */
    inputs?: Array<InputStruct>;
}

/**
 * Check if a given object implements the StateGet200Response interface.
 */
export function instanceOfStateGet200Response(value: object): value is StateGet200Response {
    return true;
}

export function StateGet200ResponseFromJSON(json: any): StateGet200Response {
    return StateGet200ResponseFromJSONTyped(json, false);
}

export function StateGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'inputs': json['inputs'] == null ? undefined : ((json['inputs'] as Array<any>).map(InputStructFromJSON)),
    };
}

export function StateGet200ResponseToJSON(json: any): StateGet200Response {
    return StateGet200ResponseToJSONTyped(json, false);
}

export function StateGet200ResponseToJSONTyped(value?: StateGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inputs': value['inputs'] == null ? undefined : ((value['inputs'] as Array<any>).map(InputStructToJSON)),
    };
}

