// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UiType } from './UiType';
import {
    UiTypeFromJSON,
    UiTypeFromJSONTyped,
    UiTypeToJSON,
    UiTypeToJSONTyped,
} from './UiType';

/**
 * 
 * @export
 * @interface StateExtendedGet200ResponseButtonbox
 */
export interface StateExtendedGet200ResponseButtonbox {
    /**
     * 
     * @type {UiType}
     * @memberof StateExtendedGet200ResponseButtonbox
     */
    uiType?: UiType;
}



/**
 * Check if a given object implements the StateExtendedGet200ResponseButtonbox interface.
 */
export function instanceOfStateExtendedGet200ResponseButtonbox(value: object): value is StateExtendedGet200ResponseButtonbox {
    return true;
}

export function StateExtendedGet200ResponseButtonboxFromJSON(json: any): StateExtendedGet200ResponseButtonbox {
    return StateExtendedGet200ResponseButtonboxFromJSONTyped(json, false);
}

export function StateExtendedGet200ResponseButtonboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateExtendedGet200ResponseButtonbox {
    if (json == null) {
        return json;
    }
    return {
        
        'uiType': json['uiType'] == null ? undefined : UiTypeFromJSON(json['uiType']),
    };
}

export function StateExtendedGet200ResponseButtonboxToJSON(json: any): StateExtendedGet200ResponseButtonbox {
    return StateExtendedGet200ResponseButtonboxToJSONTyped(json, false);
}

export function StateExtendedGet200ResponseButtonboxToJSONTyped(value?: StateExtendedGet200ResponseButtonbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uiType': UiTypeToJSON(value['uiType']),
    };
}

