// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>Status of **cloud connection** (remote access), where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>Waiting for stable WiFi connection</td> </tr> <tr> <td>**1**</td> <td>Connecting</td> </tr> <tr> <td>**2**</td> <td>Internet network is unreachable (DNS failed)</td> </tr> <tr> <td>**3**</td> <td>Internet network is unreachable (server not found)</td> </tr> <tr> <td>**4**</td> <td>Connection broken (connection was estabilished but it's broken now)</td> </tr> <tr> <td>**5**</td> <td>Connected</td> </tr> <tr> <td>**6**</td> <td>Disabled by user</td> </tr> </table>
 * @export
 */
export const TunnelStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type TunnelStatus = typeof TunnelStatus[keyof typeof TunnelStatus];


export function instanceOfTunnelStatus(value: any): boolean {
    for (const key in TunnelStatus) {
        if (Object.prototype.hasOwnProperty.call(TunnelStatus, key)) {
            if (TunnelStatus[key as keyof typeof TunnelStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TunnelStatusFromJSON(json: any): TunnelStatus {
    return TunnelStatusFromJSONTyped(json, false);
}

export function TunnelStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TunnelStatus {
    return json as TunnelStatus;
}

export function TunnelStatusToJSON(value?: TunnelStatus | null): any {
    return value as any;
}

export function TunnelStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): TunnelStatus {
    return value as TunnelStatus;
}

