// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of selected user interface (only information about the selected type, implementation should be provided on the GUI side), where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>Display controls for all triggers</td> </tr> <tr> <td>**1**</td> <td>Display controls for short and long click triggers only</td> </tr> </table>
 * @export
 */
export const UiType = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type UiType = typeof UiType[keyof typeof UiType];


export function instanceOfUiType(value: any): boolean {
    for (const key in UiType) {
        if (Object.prototype.hasOwnProperty.call(UiType, key)) {
            if (UiType[key as keyof typeof UiType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UiTypeFromJSON(json: any): UiType {
    return UiTypeFromJSONTyped(json, false);
}

export function UiTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UiType {
    return json as UiType;
}

export function UiTypeToJSON(value?: UiType | null): any {
    return value as any;
}

export function UiTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): UiType {
    return value as UiType;
}

