// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StateAfterRestart } from './StateAfterRestart';
import {
    StateAfterRestartFromJSON,
    StateAfterRestartFromJSONTyped,
    StateAfterRestartToJSON,
    StateAfterRestartToJSONTyped,
} from './StateAfterRestart';

/**
 * 
 * @export
 * @interface ApiSettingsStateGet200ResponseSettingsRelaysInner
 */
export interface ApiSettingsStateGet200ResponseSettingsRelaysInner {
    /**
     * 
     * @type {StateAfterRestart}
     * @memberof ApiSettingsStateGet200ResponseSettingsRelaysInner
     */
    stateAfterRestart?: StateAfterRestart;
    /**
     * Time in **seconds** **for button** "turn on for time" in wBox App, where **0 == disabled button**
     * @type {number}
     * @memberof ApiSettingsStateGet200ResponseSettingsRelaysInner
     */
    defaultForTime?: number;
}



/**
 * Check if a given object implements the ApiSettingsStateGet200ResponseSettingsRelaysInner interface.
 */
export function instanceOfApiSettingsStateGet200ResponseSettingsRelaysInner(value: object): value is ApiSettingsStateGet200ResponseSettingsRelaysInner {
    return true;
}

export function ApiSettingsStateGet200ResponseSettingsRelaysInnerFromJSON(json: any): ApiSettingsStateGet200ResponseSettingsRelaysInner {
    return ApiSettingsStateGet200ResponseSettingsRelaysInnerFromJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsRelaysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsStateGet200ResponseSettingsRelaysInner {
    if (json == null) {
        return json;
    }
    return {
        
        'stateAfterRestart': json['stateAfterRestart'] == null ? undefined : StateAfterRestartFromJSON(json['stateAfterRestart']),
        'defaultForTime': json['defaultForTime'] == null ? undefined : json['defaultForTime'],
    };
}

export function ApiSettingsStateGet200ResponseSettingsRelaysInnerToJSON(json: any): ApiSettingsStateGet200ResponseSettingsRelaysInner {
    return ApiSettingsStateGet200ResponseSettingsRelaysInnerToJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsRelaysInnerToJSONTyped(value?: ApiSettingsStateGet200ResponseSettingsRelaysInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stateAfterRestart': StateAfterRestartToJSON(value['stateAfterRestart']),
        'defaultForTime': value['defaultForTime'],
    };
}

