// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * **ID** - relay number
 * @export
 */
export const Relay = {
    NUMBER_0: 0
} as const;
export type Relay = typeof Relay[keyof typeof Relay];


export function instanceOfRelay(value: any): boolean {
    for (const key in Relay) {
        if (Object.prototype.hasOwnProperty.call(Relay, key)) {
            if (Relay[key as keyof typeof Relay] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RelayFromJSON(json: any): Relay {
    return RelayFromJSONTyped(json, false);
}

export function RelayFromJSONTyped(json: any, ignoreDiscriminator: boolean): Relay {
    return json as Relay;
}

export function RelayToJSON(value?: Relay | null): any {
    return value as any;
}

export function RelayToJSONTyped(value: any, ignoreDiscriminator: boolean): Relay {
    return value as Relay;
}

