// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>**Status of sensor**, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**4**</td> <td>Active mode without error reporting (if 4 occurs then it is always 4)</td> </tr> <table>
 * @export
 */
export const SensorState = {
    NUMBER_4: 4
} as const;
export type SensorState = typeof SensorState[keyof typeof SensorState];


export function instanceOfSensorState(value: any): boolean {
    for (const key in SensorState) {
        if (Object.prototype.hasOwnProperty.call(SensorState, key)) {
            if (SensorState[key as keyof typeof SensorState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SensorStateFromJSON(json: any): SensorState {
    return SensorStateFromJSONTyped(json, false);
}

export function SensorStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorState {
    return json as SensorState;
}

export function SensorStateToJSON(value?: SensorState | null): any {
    return value as any;
}

export function SensorStateToJSONTyped(value: any, ignoreDiscriminator: boolean): SensorState {
    return value as SensorState;
}

