// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SensorType } from './SensorType';
import {
    SensorTypeFromJSON,
    SensorTypeFromJSONTyped,
    SensorTypeToJSON,
    SensorTypeToJSONTyped,
} from './SensorType';
import type { SensorState } from './SensorState';
import {
    SensorStateFromJSON,
    SensorStateFromJSONTyped,
    SensorStateToJSON,
    SensorStateToJSONTyped,
} from './SensorState';
import type { SensorTrend } from './SensorTrend';
import {
    SensorTrendFromJSON,
    SensorTrendFromJSONTyped,
    SensorTrendToJSON,
    SensorTrendToJSONTyped,
} from './SensorTrend';

/**
 * Sensor and measurement information
 * @export
 * @interface Sensor
 */
export interface Sensor {
    /**
     * 
     * @type {SensorType}
     * @memberof Sensor
     */
    type?: SensorType;
    /**
     * Current value of measurement - **power of connected device** (active power counted in Watt)
     * @type {number}
     * @memberof Sensor
     */
    value?: number;
    /**
     * 
     * @type {SensorTrend}
     * @memberof Sensor
     */
    trend?: SensorTrend;
    /**
     * 
     * @type {SensorState}
     * @memberof Sensor
     */
    state?: SensorState;
}



/**
 * Check if a given object implements the Sensor interface.
 */
export function instanceOfSensor(value: object): value is Sensor {
    return true;
}

export function SensorFromJSON(json: any): Sensor {
    return SensorFromJSONTyped(json, false);
}

export function SensorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sensor {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : SensorTypeFromJSON(json['type']),
        'value': json['value'] == null ? undefined : json['value'],
        'trend': json['trend'] == null ? undefined : SensorTrendFromJSON(json['trend']),
        'state': json['state'] == null ? undefined : SensorStateFromJSON(json['state']),
    };
}

export function SensorToJSON(json: any): Sensor {
    return SensorToJSONTyped(json, false);
}

export function SensorToJSONTyped(value?: Sensor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': SensorTypeToJSON(value['type']),
        'value': value['value'],
        'trend': SensorTrendToJSON(value['trend']),
        'state': SensorStateToJSON(value['state']),
    };
}

