// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>**Set state** of relay, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>OFF</td> </tr> <tr> <td>**1**</td> <td>ON</td> </tr> <tr> <td>**2**</td> <td>Toggle (change to the opposite)</td> </tr> </table>
 * @export
 */
export const StateSet = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type StateSet = typeof StateSet[keyof typeof StateSet];


export function instanceOfStateSet(value: any): boolean {
    for (const key in StateSet) {
        if (Object.prototype.hasOwnProperty.call(StateSet, key)) {
            if (StateSet[key as keyof typeof StateSet] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StateSetFromJSON(json: any): StateSet {
    return StateSetFromJSONTyped(json, false);
}

export function StateSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateSet {
    return json as StateSet;
}

export function StateSetToJSON(value?: StateSet | null): any {
    return value as any;
}

export function StateSetToJSONTyped(value: any, ignoreDiscriminator: boolean): StateSet {
    return value as StateSet;
}

