// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>**State of relay after reebot/reset** (power outage), where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>OFF</td> </tr> <tr> <td>**1**</td> <td>ON</td> </tr> <tr> <td>**2**</td> <td>Last state</td> </tr> <tr> <td>**3**</td> <td>Opposed state</td> </tr> </table>
 * @export
 */
export const StateAfterRestart = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type StateAfterRestart = typeof StateAfterRestart[keyof typeof StateAfterRestart];


export function instanceOfStateAfterRestart(value: any): boolean {
    for (const key in StateAfterRestart) {
        if (Object.prototype.hasOwnProperty.call(StateAfterRestart, key)) {
            if (StateAfterRestart[key as keyof typeof StateAfterRestart] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StateAfterRestartFromJSON(json: any): StateAfterRestart {
    return StateAfterRestartFromJSONTyped(json, false);
}

export function StateAfterRestartFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateAfterRestart {
    return json as StateAfterRestart;
}

export function StateAfterRestartToJSON(value?: StateAfterRestart | null): any {
    return value as any;
}

export function StateAfterRestartToJSONTyped(value: any, ignoreDiscriminator: boolean): StateAfterRestart {
    return value as StateAfterRestart;
}

