// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    Adjust,
    ApiRgbwStateGet200Response,
    ColorFade,
} from '../models/index';

export interface ControlWithGETApiSAdjustChannelsDeltaGetRequest {
    adjust: Adjust;
    channelsDelta: string;
}

export interface ControlWithGETApiSChannelsColorFadeMsTimeMsForTimeTimeSGetRequest {
    channels: string;
    timeMs: ColorFade;
    timeS: number;
}

export interface ControlWithGETApiSChannelsColorFadeMsTimeMsGetRequest {
    channels: string;
    timeMs: ColorFade;
}

export interface ControlWithGETApiSChannelsForTimeTimeSGetRequest {
    channels: string;
    timeS: number;
}

export interface ControlWithGETApiSChannelsGetRequest {
    channels: string;
}

export interface ControlWithGETApiSXEffectIDForTimeTimeSGetRequest {
    effectID: number;
    timeS: number;
}

export interface ControlWithGETApiSXEffectIDGetRequest {
    effectID: number;
}

/**
 * 
 */
export class ControlWithGETApi extends runtime.BaseAPI {

    /**
     * Creates request options for sAdjustChannelsDeltaGet without sending the request
     */
    async sAdjustChannelsDeltaGetRequestOpts(requestParameters: ControlWithGETApiSAdjustChannelsDeltaGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['adjust'] == null) {
            throw new runtime.RequiredError(
                'adjust',
                'Required parameter "adjust" was null or undefined when calling sAdjustChannelsDeltaGet().'
            );
        }

        if (requestParameters['channelsDelta'] == null) {
            throw new runtime.RequiredError(
                'channelsDelta',
                'Required parameter "channelsDelta" was null or undefined when calling sAdjustChannelsDeltaGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/{adjust}/{channelsDelta}`;
        urlPath = urlPath.replace('{adjust}', encodeURIComponent(String(requestParameters['adjust'])));
        urlPath = urlPath.replace('{channelsDelta}', encodeURIComponent(String(requestParameters['channelsDelta'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Adjust brightness** using GET request
     * Adjust brightness
     */
    async sAdjustChannelsDeltaGetRaw(requestParameters: ControlWithGETApiSAdjustChannelsDeltaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.sAdjustChannelsDeltaGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Adjust brightness** using GET request
     * Adjust brightness
     */
    async sAdjustChannelsDeltaGet(requestParameters: ControlWithGETApiSAdjustChannelsDeltaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.sAdjustChannelsDeltaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sChannelsColorFadeMsTimeMsForTimeTimeSGet without sending the request
     */
    async sChannelsColorFadeMsTimeMsForTimeTimeSGetRequestOpts(requestParameters: ControlWithGETApiSChannelsColorFadeMsTimeMsForTimeTimeSGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channels'] == null) {
            throw new runtime.RequiredError(
                'channels',
                'Required parameter "channels" was null or undefined when calling sChannelsColorFadeMsTimeMsForTimeTimeSGet().'
            );
        }

        if (requestParameters['timeMs'] == null) {
            throw new runtime.RequiredError(
                'timeMs',
                'Required parameter "timeMs" was null or undefined when calling sChannelsColorFadeMsTimeMsForTimeTimeSGet().'
            );
        }

        if (requestParameters['timeS'] == null) {
            throw new runtime.RequiredError(
                'timeS',
                'Required parameter "timeS" was null or undefined when calling sChannelsColorFadeMsTimeMsForTimeTimeSGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/{channels}/colorFadeMs/{timeMs}/forTime/{timeS}`;
        urlPath = urlPath.replace('{channels}', encodeURIComponent(String(requestParameters['channels'])));
        urlPath = urlPath.replace('{timeMs}', encodeURIComponent(String(requestParameters['timeMs'])));
        urlPath = urlPath.replace('{timeS}', encodeURIComponent(String(requestParameters['timeS'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Set color with color fade time for given time** using GET request (after given time returns to previous state)
     * Set color with fade time for a given time
     */
    async sChannelsColorFadeMsTimeMsForTimeTimeSGetRaw(requestParameters: ControlWithGETApiSChannelsColorFadeMsTimeMsForTimeTimeSGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.sChannelsColorFadeMsTimeMsForTimeTimeSGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Set color with color fade time for given time** using GET request (after given time returns to previous state)
     * Set color with fade time for a given time
     */
    async sChannelsColorFadeMsTimeMsForTimeTimeSGet(requestParameters: ControlWithGETApiSChannelsColorFadeMsTimeMsForTimeTimeSGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.sChannelsColorFadeMsTimeMsForTimeTimeSGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sChannelsColorFadeMsTimeMsGet without sending the request
     */
    async sChannelsColorFadeMsTimeMsGetRequestOpts(requestParameters: ControlWithGETApiSChannelsColorFadeMsTimeMsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channels'] == null) {
            throw new runtime.RequiredError(
                'channels',
                'Required parameter "channels" was null or undefined when calling sChannelsColorFadeMsTimeMsGet().'
            );
        }

        if (requestParameters['timeMs'] == null) {
            throw new runtime.RequiredError(
                'timeMs',
                'Required parameter "timeMs" was null or undefined when calling sChannelsColorFadeMsTimeMsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/{channels}/colorFadeMs/{timeMs}`;
        urlPath = urlPath.replace('{channels}', encodeURIComponent(String(requestParameters['channels'])));
        urlPath = urlPath.replace('{timeMs}', encodeURIComponent(String(requestParameters['timeMs'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Set color with color fade time** in milliseconds using GET request
     * Set color with fade time
     */
    async sChannelsColorFadeMsTimeMsGetRaw(requestParameters: ControlWithGETApiSChannelsColorFadeMsTimeMsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.sChannelsColorFadeMsTimeMsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Set color with color fade time** in milliseconds using GET request
     * Set color with fade time
     */
    async sChannelsColorFadeMsTimeMsGet(requestParameters: ControlWithGETApiSChannelsColorFadeMsTimeMsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.sChannelsColorFadeMsTimeMsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sChannelsForTimeTimeSGet without sending the request
     */
    async sChannelsForTimeTimeSGetRequestOpts(requestParameters: ControlWithGETApiSChannelsForTimeTimeSGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channels'] == null) {
            throw new runtime.RequiredError(
                'channels',
                'Required parameter "channels" was null or undefined when calling sChannelsForTimeTimeSGet().'
            );
        }

        if (requestParameters['timeS'] == null) {
            throw new runtime.RequiredError(
                'timeS',
                'Required parameter "timeS" was null or undefined when calling sChannelsForTimeTimeSGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/{channels}/forTime/{timeS}`;
        urlPath = urlPath.replace('{channels}', encodeURIComponent(String(requestParameters['channels'])));
        urlPath = urlPath.replace('{timeS}', encodeURIComponent(String(requestParameters['timeS'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Set color for given time** using GET request (after given time returns to previous state)
     * Set color for a given time
     */
    async sChannelsForTimeTimeSGetRaw(requestParameters: ControlWithGETApiSChannelsForTimeTimeSGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.sChannelsForTimeTimeSGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Set color for given time** using GET request (after given time returns to previous state)
     * Set color for a given time
     */
    async sChannelsForTimeTimeSGet(requestParameters: ControlWithGETApiSChannelsForTimeTimeSGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.sChannelsForTimeTimeSGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sChannelsGet without sending the request
     */
    async sChannelsGetRequestOpts(requestParameters: ControlWithGETApiSChannelsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channels'] == null) {
            throw new runtime.RequiredError(
                'channels',
                'Required parameter "channels" was null or undefined when calling sChannelsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/{channels}`;
        urlPath = urlPath.replace('{channels}', encodeURIComponent(String(requestParameters['channels'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Set color** using GET request
     * Set color
     */
    async sChannelsGetRaw(requestParameters: ControlWithGETApiSChannelsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.sChannelsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Set color** using GET request
     * Set color
     */
    async sChannelsGet(requestParameters: ControlWithGETApiSChannelsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.sChannelsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sOffonLastGet without sending the request
     */
    async sOffonLastGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/offon/last`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Turning ON/OFF** (toggle) **last color or effect**
     * Toggle (ON/OFF last state)
     */
    async sOffonLastGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.sOffonLastGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Turning ON/OFF** (toggle) **last color or effect**
     * Toggle (ON/OFF last state)
     */
    async sOffonLastGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.sOffonLastGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sOnlastGet without sending the request
     */
    async sOnlastGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/onlast`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Setting last color or effect**
     * Set to last state
     */
    async sOnlastGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.sOnlastGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Setting last color or effect**
     * Set to last state
     */
    async sOnlastGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.sOnlastGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sXEffectIDForTimeTimeSGet without sending the request
     */
    async sXEffectIDForTimeTimeSGetRequestOpts(requestParameters: ControlWithGETApiSXEffectIDForTimeTimeSGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['effectID'] == null) {
            throw new runtime.RequiredError(
                'effectID',
                'Required parameter "effectID" was null or undefined when calling sXEffectIDForTimeTimeSGet().'
            );
        }

        if (requestParameters['timeS'] == null) {
            throw new runtime.RequiredError(
                'timeS',
                'Required parameter "timeS" was null or undefined when calling sXEffectIDForTimeTimeSGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/x/{effectID}/forTime/{timeS}`;
        urlPath = urlPath.replace('{effectID}', encodeURIComponent(String(requestParameters['effectID'])));
        urlPath = urlPath.replace('{timeS}', encodeURIComponent(String(requestParameters['timeS'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Turning ON effect with given ID** using GET request (after given time returns to previous state)
     * Set effect for a given time
     */
    async sXEffectIDForTimeTimeSGetRaw(requestParameters: ControlWithGETApiSXEffectIDForTimeTimeSGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.sXEffectIDForTimeTimeSGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Turning ON effect with given ID** using GET request (after given time returns to previous state)
     * Set effect for a given time
     */
    async sXEffectIDForTimeTimeSGet(requestParameters: ControlWithGETApiSXEffectIDForTimeTimeSGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.sXEffectIDForTimeTimeSGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sXEffectIDGet without sending the request
     */
    async sXEffectIDGetRequestOpts(requestParameters: ControlWithGETApiSXEffectIDGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['effectID'] == null) {
            throw new runtime.RequiredError(
                'effectID',
                'Required parameter "effectID" was null or undefined when calling sXEffectIDGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/x/{effectID}`;
        urlPath = urlPath.replace('{effectID}', encodeURIComponent(String(requestParameters['effectID'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Turning ON effect with given ID** using GET request
     * Set effect
     */
    async sXEffectIDGetRaw(requestParameters: ControlWithGETApiSXEffectIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.sXEffectIDGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Turning ON effect with given ID** using GET request
     * Set effect
     */
    async sXEffectIDGet(requestParameters: ControlWithGETApiSXEffectIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.sXEffectIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
