// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    ApiDeviceUptimeGet200Response,
    InfoGet200Response,
} from '../models/index';

/**
 * 
 */
export class GeneralApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiDeviceStateGet without sending the request
     * @deprecated
     */
    async apiDeviceStateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/device/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns **general information** about device <br><br>**It is deprecated** -> look at:
     * Information about device
     * @deprecated
     */
    async apiDeviceStateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiDeviceStateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns **general information** about device <br><br>**It is deprecated** -> look at:
     * Information about device
     * @deprecated
     */
    async apiDeviceStateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDeviceStateGetRaw(initOverrides);
    }

    /**
     * Creates request options for apiDeviceUptimeGet without sending the request
     */
    async apiDeviceUptimeGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/device/uptime`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns information about **number of seconds from boot**
     * Device upTime
     */
    async apiDeviceUptimeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDeviceUptimeGet200Response>> {
        const requestOptions = await this.apiDeviceUptimeGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns information about **number of seconds from boot**
     * Device upTime
     */
    async apiDeviceUptimeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDeviceUptimeGet200Response> {
        const response = await this.apiDeviceUptimeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiOtaUpdatePost without sending the request
     */
    async apiOtaUpdatePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ota/update`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Perform firmware update**. Return conflict if update is in progress
     * Perform firmware update
     */
    async apiOtaUpdatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiOtaUpdatePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Perform firmware update**. Return conflict if update is in progress
     * Perform firmware update
     */
    async apiOtaUpdatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiOtaUpdatePostRaw(initOverrides);
    }

    /**
     * Creates request options for infoGet without sending the request
     */
    async infoGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/info`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns **general information** about device
     * Information about device
     */
    async infoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InfoGet200Response>> {
        const requestOptions = await this.infoGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns **general information** about device
     * Information about device
     */
    async infoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InfoGet200Response> {
        const response = await this.infoGetRaw(initOverrides);
        return await response.value();
    }

}
