// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for the BleBox Device Manager.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    ApiDevicesProbePost200Response,
    ApiDevicesProbePost400Response,
    ApiDevicesProbePostRequest,
} from '../models/index';

export interface DevicesApiApiDevicesProbePostOperationRequest {
    apiDevicesProbePostRequest: ApiDevicesProbePostRequest;
}

/**
 * 
 */
export class DevicesApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiDevicesProbePost without sending the request
     */
    async apiDevicesProbePostRequestOpts(requestParameters: DevicesApiApiDevicesProbePostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['apiDevicesProbePostRequest'] == null) {
            throw new runtime.RequiredError(
                'apiDevicesProbePostRequest',
                'Required parameter "apiDevicesProbePostRequest" was null or undefined when calling apiDevicesProbePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/devices/probe`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['apiDevicesProbePostRequest'],
        };
    }

    /**
     * Probe a manually entered IP for a BleBox device
     */
    async apiDevicesProbePostRaw(requestParameters: DevicesApiApiDevicesProbePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDevicesProbePost200Response>> {
        const requestOptions = await this.apiDevicesProbePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Probe a manually entered IP for a BleBox device
     */
    async apiDevicesProbePost(requestParameters: DevicesApiApiDevicesProbePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDevicesProbePost200Response> {
        const response = await this.apiDevicesProbePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
