// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for the BleBox Device Manager.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    ApiDiscoveryDevicesGet200Response,
    ApiDiscoveryStartPost202Response,
} from '../models/index';

/**
 * 
 */
export class DiscoveryApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiDiscoveryDevicesGet without sending the request
     */
    async apiDiscoveryDevicesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/discovery/devices`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Currently discovered BleBox devices
     */
    async apiDiscoveryDevicesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDiscoveryDevicesGet200Response>> {
        const requestOptions = await this.apiDiscoveryDevicesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Currently discovered BleBox devices
     */
    async apiDiscoveryDevicesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDiscoveryDevicesGet200Response> {
        const response = await this.apiDiscoveryDevicesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDiscoveryStartPost without sending the request
     */
    async apiDiscoveryStartPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/discovery/start`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Start an mDNS + subnet scan
     */
    async apiDiscoveryStartPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDiscoveryStartPost202Response>> {
        const requestOptions = await this.apiDiscoveryStartPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Start an mDNS + subnet scan
     */
    async apiDiscoveryStartPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDiscoveryStartPost202Response> {
        const response = await this.apiDiscoveryStartPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDiscoveryStopPost without sending the request
     */
    async apiDiscoveryStopPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/discovery/stop`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stop scanning
     */
    async apiDiscoveryStopPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDiscoveryStartPost202Response>> {
        const requestOptions = await this.apiDiscoveryStopPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Stop scanning
     */
    async apiDiscoveryStopPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDiscoveryStartPost202Response> {
        const response = await this.apiDiscoveryStopPostRaw(initOverrides);
        return await response.value();
    }

}
