// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    ApiSettingsSetPostRequest,
    ApiSettingsStateGet200Response,
} from '../models/index';

export interface SettingsApiApiSettingsSetPostOperationRequest {
    apiSettingsSetPostRequest?: ApiSettingsSetPostRequest;
}

/**
 * 
 */
export class SettingsApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiSettingsSetPost without sending the request
     */
    async apiSettingsSetPostRequestOpts(requestParameters: SettingsApiApiSettingsSetPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/settings/set`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['apiSettingsSetPostRequest'],
        };
    }

    /**
     * Allow to set device\'s **specific** settings
     * Settings set
     */
    async apiSettingsSetPostRaw(requestParameters: SettingsApiApiSettingsSetPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiSettingsStateGet200Response>> {
        const requestOptions = await this.apiSettingsSetPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Allow to set device\'s **specific** settings
     * Settings set
     */
    async apiSettingsSetPost(requestParameters: SettingsApiApiSettingsSetPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiSettingsStateGet200Response> {
        const response = await this.apiSettingsSetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiSettingsStateGet without sending the request
     */
    async apiSettingsStateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/settings/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return device\'s **specific** settings
     * Settings state
     */
    async apiSettingsStateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiSettingsStateGet200Response>> {
        const requestOptions = await this.apiSettingsStateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Return device\'s **specific** settings
     * Settings state
     */
    async apiSettingsStateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiSettingsStateGet200Response> {
        const response = await this.apiSettingsStateGetRaw(initOverrides);
        return await response.value();
    }

}
