// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Enabled } from './Enabled';
import {
    EnabledFromJSON,
    EnabledFromJSONTyped,
    EnabledToJSON,
    EnabledToJSONTyped,
} from './Enabled';

/**
 * Allows to **enable** or **disable** extended status notification using built in **LED**
 * @export
 * @interface ApiSettingsStateGet200ResponseSettingsStatusLed
 */
export interface ApiSettingsStateGet200ResponseSettingsStatusLed {
    /**
     * 
     * @type {Enabled}
     * @memberof ApiSettingsStateGet200ResponseSettingsStatusLed
     */
    enabled?: Enabled;
}

/**
 * Check if a given object implements the ApiSettingsStateGet200ResponseSettingsStatusLed interface.
 */
export function instanceOfApiSettingsStateGet200ResponseSettingsStatusLed(value: object): value is ApiSettingsStateGet200ResponseSettingsStatusLed {
    return true;
}

export function ApiSettingsStateGet200ResponseSettingsStatusLedFromJSON(json: any): ApiSettingsStateGet200ResponseSettingsStatusLed {
    return ApiSettingsStateGet200ResponseSettingsStatusLedFromJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsStatusLedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsStateGet200ResponseSettingsStatusLed {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : EnabledFromJSON(json['enabled']),
    };
}

export function ApiSettingsStateGet200ResponseSettingsStatusLedToJSON(json: any): ApiSettingsStateGet200ResponseSettingsStatusLed {
    return ApiSettingsStateGet200ResponseSettingsStatusLedToJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsStatusLedToJSONTyped(value?: ApiSettingsStateGet200ResponseSettingsStatusLed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': EnabledToJSON(value['enabled']),
    };
}

