// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Enabled } from './Enabled';
import {
    EnabledFromJSON,
    EnabledFromJSONTyped,
    EnabledToJSON,
    EnabledToJSONTyped,
} from './Enabled';

/**
 * Allows to **enable or disable** connection with **the BleBox's cloud** and decide whether events generated by this device should be log to **the BleBox's cloud** (necessary for push notifications), the user can view the event log through the wBox application.
 * @export
 * @interface ApiSettingsStateGet200ResponseSettingsTunnel
 */
export interface ApiSettingsStateGet200ResponseSettingsTunnel {
    /**
     * <br>Allow to **disable or enable function**, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>disabled</td> </tr> <tr> <td>**1**</td> <td>enabled</td> </tr> </table>
     * @type {ApiSettingsStateGet200ResponseSettingsTunnelEnabledEnum}
     * @memberof ApiSettingsStateGet200ResponseSettingsTunnel
     */
    enabled?: ApiSettingsStateGet200ResponseSettingsTunnelEnabledEnum;
    /**
     * 
     * @type {Enabled}
     * @memberof ApiSettingsStateGet200ResponseSettingsTunnel
     */
    logEnabled?: Enabled;
}


/**
 * @export
 */
export const ApiSettingsStateGet200ResponseSettingsTunnelEnabledEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type ApiSettingsStateGet200ResponseSettingsTunnelEnabledEnum = typeof ApiSettingsStateGet200ResponseSettingsTunnelEnabledEnum[keyof typeof ApiSettingsStateGet200ResponseSettingsTunnelEnabledEnum];


/**
 * Check if a given object implements the ApiSettingsStateGet200ResponseSettingsTunnel interface.
 */
export function instanceOfApiSettingsStateGet200ResponseSettingsTunnel(value: object): value is ApiSettingsStateGet200ResponseSettingsTunnel {
    return true;
}

export function ApiSettingsStateGet200ResponseSettingsTunnelFromJSON(json: any): ApiSettingsStateGet200ResponseSettingsTunnel {
    return ApiSettingsStateGet200ResponseSettingsTunnelFromJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsTunnelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsStateGet200ResponseSettingsTunnel {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'logEnabled': json['logEnabled'] == null ? undefined : EnabledFromJSON(json['logEnabled']),
    };
}

export function ApiSettingsStateGet200ResponseSettingsTunnelToJSON(json: any): ApiSettingsStateGet200ResponseSettingsTunnel {
    return ApiSettingsStateGet200ResponseSettingsTunnelToJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsTunnelToJSONTyped(value?: ApiSettingsStateGet200ResponseSettingsTunnel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'logEnabled': EnabledToJSON(value['logEnabled']),
    };
}

