// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiWifiScanGet200ResponseApInner
 */
export interface ApiWifiScanGet200ResponseApInner {
    /**
     * SSID (name) of found network
     * @type {string}
     * @memberof ApiWifiScanGet200ResponseApInner
     */
    ssid?: string;
    /**
     * <br>**Signal strength** of found network, where:<br> <table> <tr> <td>From:</td> <td>To:</td> <td>Description:</td> </tr> <tr> <td>**-67**</td> <td>**0**</td> <td>Very good</td> </tr> <tr> <td>**-73**</td> <td>**-68**</td> <td>Good</td> </tr> <tr> <td>**-80**</td> <td>**-74**</td> <td>Poor</td> </tr> <tr> <td>**-127**</td> <td>**-81**</td> <td>Unstable/Unusable</td> </tr> </table>
     * @type {number}
     * @memberof ApiWifiScanGet200ResponseApInner
     */
    rssi?: number;
    /**
     * <br>**Encryption mode** of found network, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>Open network (without password) - unsafe, but can be used</td> </tr> <tr> <td>**1**</td> <td>WEP encryption - unsafe - can not be used</td> </tr> <tr> <td>**2**</td> <td>WPA encryption - unsafe - can not be used</td> </tr> <tr> <td>**3**</td> <td>WPA2 encryption - safe if properly configured - can be used (recomended)</td> </tr> <tr> <td>**4**</td> <td>WPA/WPA2 encryption - unsafe, but can be used as WPA2</td> </tr> </table>
     * @type {ApiWifiScanGet200ResponseApInnerEncEnum}
     * @memberof ApiWifiScanGet200ResponseApInner
     */
    enc?: ApiWifiScanGet200ResponseApInnerEncEnum;
}


/**
 * @export
 */
export const ApiWifiScanGet200ResponseApInnerEncEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type ApiWifiScanGet200ResponseApInnerEncEnum = typeof ApiWifiScanGet200ResponseApInnerEncEnum[keyof typeof ApiWifiScanGet200ResponseApInnerEncEnum];


/**
 * Check if a given object implements the ApiWifiScanGet200ResponseApInner interface.
 */
export function instanceOfApiWifiScanGet200ResponseApInner(value: object): value is ApiWifiScanGet200ResponseApInner {
    return true;
}

export function ApiWifiScanGet200ResponseApInnerFromJSON(json: any): ApiWifiScanGet200ResponseApInner {
    return ApiWifiScanGet200ResponseApInnerFromJSONTyped(json, false);
}

export function ApiWifiScanGet200ResponseApInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWifiScanGet200ResponseApInner {
    if (json == null) {
        return json;
    }
    return {
        
        'ssid': json['ssid'] == null ? undefined : json['ssid'],
        'rssi': json['rssi'] == null ? undefined : json['rssi'],
        'enc': json['enc'] == null ? undefined : json['enc'],
    };
}

export function ApiWifiScanGet200ResponseApInnerToJSON(json: any): ApiWifiScanGet200ResponseApInner {
    return ApiWifiScanGet200ResponseApInnerToJSONTyped(json, false);
}

export function ApiWifiScanGet200ResponseApInnerToJSONTyped(value?: ApiWifiScanGet200ResponseApInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ssid': value['ssid'],
        'rssi': value['rssi'],
        'enc': value['enc'],
    };
}

