// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceName } from './DeviceName';
import {
    DeviceNameFromJSON,
    DeviceNameFromJSONTyped,
    DeviceNameToJSON,
    DeviceNameToJSONTyped,
} from './DeviceName';

/**
 * **General** information about device
 * @export
 * @interface InfoGet200ResponseDevice
 */
export interface InfoGet200ResponseDevice {
    /**
     * 
     * @type {DeviceName}
     * @memberof InfoGet200ResponseDevice
     */
    deviceName?: DeviceName;
    /**
     * Product name for informational purpose only - do not use it in any application logic
     * @type {string}
     * @memberof InfoGet200ResponseDevice
     */
    product?: string;
    /**
     * **API type** of BleBox device - it indicate what **device-specific API** should be used
     * @type {string}
     * @memberof InfoGet200ResponseDevice
     */
    type?: string;
    /**
     * **API level** of BleBox device - it indicate what version of **common and device-specific API** should be used
     * @type {string}
     * @memberof InfoGet200ResponseDevice
     */
    apiLevel?: string;
    /**
     * Hardware version for informational purpose only - do not use it in any application logic
     * @type {string}
     * @memberof InfoGet200ResponseDevice
     */
    hv?: string;
    /**
     * Firmware version for informational purpose only - do not use it in any application logic
     * @type {string}
     * @memberof InfoGet200ResponseDevice
     */
    fv?: string;
    /**
     * Unique identification number of BleBox device
     * @type {string}
     * @memberof InfoGet200ResponseDevice
     */
    id?: string;
    /**
     * 
     * @type {object}
     * @memberof InfoGet200ResponseDevice
     */
    ip?: object;
}

/**
 * Check if a given object implements the InfoGet200ResponseDevice interface.
 */
export function instanceOfInfoGet200ResponseDevice(value: object): value is InfoGet200ResponseDevice {
    return true;
}

export function InfoGet200ResponseDeviceFromJSON(json: any): InfoGet200ResponseDevice {
    return InfoGet200ResponseDeviceFromJSONTyped(json, false);
}

export function InfoGet200ResponseDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoGet200ResponseDevice {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceName': json['deviceName'] == null ? undefined : DeviceNameFromJSON(json['deviceName']),
        'product': json['product'] == null ? undefined : json['product'],
        'type': json['type'] == null ? undefined : json['type'],
        'apiLevel': json['apiLevel'] == null ? undefined : json['apiLevel'],
        'hv': json['hv'] == null ? undefined : json['hv'],
        'fv': json['fv'] == null ? undefined : json['fv'],
        'id': json['id'] == null ? undefined : json['id'],
        'ip': json['ip'] == null ? undefined : json['ip'],
    };
}

export function InfoGet200ResponseDeviceToJSON(json: any): InfoGet200ResponseDevice {
    return InfoGet200ResponseDeviceToJSONTyped(json, false);
}

export function InfoGet200ResponseDeviceToJSONTyped(value?: InfoGet200ResponseDevice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceName': DeviceNameToJSON(value['deviceName']),
        'product': value['product'],
        'type': value['type'],
        'apiLevel': value['apiLevel'],
        'hv': value['hv'],
        'fv': value['fv'],
        'id': value['id'],
        'ip': value['ip'],
    };
}

