// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>**Relation between output relays**, where: <br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>independent outputs</td> </tr> <tr> <td>**1**</td> <td>push-pull outputs (only one at a time can be enabled)</td> </tr> </table>
 * @export
 */
export const OutputMode = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type OutputMode = typeof OutputMode[keyof typeof OutputMode];


export function instanceOfOutputMode(value: any): boolean {
    for (const key in OutputMode) {
        if (Object.prototype.hasOwnProperty.call(OutputMode, key)) {
            if (OutputMode[key as keyof typeof OutputMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OutputModeFromJSON(json: any): OutputMode {
    return OutputModeFromJSONTyped(json, false);
}

export function OutputModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputMode {
    return json as OutputMode;
}

export function OutputModeToJSON(value?: OutputMode | null): any {
    return value as any;
}

export function OutputModeToJSONTyped(value: any, ignoreDiscriminator: boolean): OutputMode {
    return value as OutputMode;
}

