// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PowerConsumption
 */
export interface PowerConsumption {
    /**
     * Period of measurement in seconds - applies to the "value" field.
     * @type {number}
     * @memberof PowerConsumption
     */
    periodS?: number;
    /**
     * **Energy consuption** in **kWh**. Always 3 decimal places
     * @type {number}
     * @memberof PowerConsumption
     */
    value?: number;
}

/**
 * Check if a given object implements the PowerConsumption interface.
 */
export function instanceOfPowerConsumption(value: object): value is PowerConsumption {
    return true;
}

export function PowerConsumptionFromJSON(json: any): PowerConsumption {
    return PowerConsumptionFromJSONTyped(json, false);
}

export function PowerConsumptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PowerConsumption {
    if (json == null) {
        return json;
    }
    return {
        
        'periodS': json['periodS'] == null ? undefined : json['periodS'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function PowerConsumptionToJSON(json: any): PowerConsumption {
    return PowerConsumptionToJSONTyped(json, false);
}

export function PowerConsumptionToJSONTyped(value?: PowerConsumption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'periodS': value['periodS'],
        'value': value['value'],
    };
}

