// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PowerConsumption } from './PowerConsumption';
import {
    PowerConsumptionFromJSON,
    PowerConsumptionFromJSONTyped,
    PowerConsumptionToJSON,
    PowerConsumptionToJSONTyped,
} from './PowerConsumption';

/**
 * Informations from **power measuring module**, see also section **sensor** for **activePower** sensor data. If hardware doesn't support power measuring then always **"enabled" == 0**
 * @export
 * @interface PowerMeasuring
 */
export interface PowerMeasuring {
    /**
     * <br>Indicates whether **the function is disabled or enabled**, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>disabled</td> </tr> <tr> <td>**1**</td> <td>enabled</td> </tr> </table>
     * @type {PowerMeasuringEnabledEnum}
     * @memberof PowerMeasuring
     */
    enabled?: PowerMeasuringEnabledEnum;
    /**
     * **Energy consumption** from the last time period. If field **"enabled" == 0** then **array doesn't exist**.
     * @type {Array<PowerConsumption>}
     * @memberof PowerMeasuring
     */
    powerConsumption?: Array<PowerConsumption>;
}


/**
 * @export
 */
export const PowerMeasuringEnabledEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type PowerMeasuringEnabledEnum = typeof PowerMeasuringEnabledEnum[keyof typeof PowerMeasuringEnabledEnum];


/**
 * Check if a given object implements the PowerMeasuring interface.
 */
export function instanceOfPowerMeasuring(value: object): value is PowerMeasuring {
    return true;
}

export function PowerMeasuringFromJSON(json: any): PowerMeasuring {
    return PowerMeasuringFromJSONTyped(json, false);
}

export function PowerMeasuringFromJSONTyped(json: any, ignoreDiscriminator: boolean): PowerMeasuring {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'powerConsumption': json['powerConsumption'] == null ? undefined : ((json['powerConsumption'] as Array<any>).map(PowerConsumptionFromJSON)),
    };
}

export function PowerMeasuringToJSON(json: any): PowerMeasuring {
    return PowerMeasuringToJSONTyped(json, false);
}

export function PowerMeasuringToJSONTyped(value?: PowerMeasuring | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'powerConsumption': value['powerConsumption'] == null ? undefined : ((value['powerConsumption'] as Array<any>).map(PowerConsumptionToJSON)),
    };
}

