// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Relay } from './Relay';
import {
    RelayFromJSON,
    RelayFromJSONTyped,
    RelayToJSON,
    RelayToJSONTyped,
} from './Relay';
import type { StateGet } from './StateGet';
import {
    StateGetFromJSON,
    StateGetFromJSONTyped,
    StateGetToJSON,
    StateGetToJSONTyped,
} from './StateGet';
import type { StateAfterRestart } from './StateAfterRestart';
import {
    StateAfterRestartFromJSON,
    StateAfterRestartFromJSONTyped,
    StateAfterRestartToJSON,
    StateAfterRestartToJSONTyped,
} from './StateAfterRestart';

/**
 * 
 * @export
 * @interface StateExtendedGet200ResponseRelaysInner
 */
export interface StateExtendedGet200ResponseRelaysInner {
    /**
     * 
     * @type {Relay}
     * @memberof StateExtendedGet200ResponseRelaysInner
     */
    relay?: Relay;
    /**
     * 
     * @type {StateGet}
     * @memberof StateExtendedGet200ResponseRelaysInner
     */
    state?: StateGet;
    /**
     * 
     * @type {StateAfterRestart}
     * @memberof StateExtendedGet200ResponseRelaysInner
     */
    stateAfterRestart?: StateAfterRestart;
    /**
     * Time in **seconds** **for button** "turn on for time" in wBox App, where **0 == disabled button**
     * @type {number}
     * @memberof StateExtendedGet200ResponseRelaysInner
     */
    defaultForTime?: number;
    /**
     * **Name of output**
     * @type {string}
     * @memberof StateExtendedGet200ResponseRelaysInner
     */
    name?: string;
}



/**
 * Check if a given object implements the StateExtendedGet200ResponseRelaysInner interface.
 */
export function instanceOfStateExtendedGet200ResponseRelaysInner(value: object): value is StateExtendedGet200ResponseRelaysInner {
    return true;
}

export function StateExtendedGet200ResponseRelaysInnerFromJSON(json: any): StateExtendedGet200ResponseRelaysInner {
    return StateExtendedGet200ResponseRelaysInnerFromJSONTyped(json, false);
}

export function StateExtendedGet200ResponseRelaysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateExtendedGet200ResponseRelaysInner {
    if (json == null) {
        return json;
    }
    return {
        
        'relay': json['relay'] == null ? undefined : RelayFromJSON(json['relay']),
        'state': json['state'] == null ? undefined : StateGetFromJSON(json['state']),
        'stateAfterRestart': json['stateAfterRestart'] == null ? undefined : StateAfterRestartFromJSON(json['stateAfterRestart']),
        'defaultForTime': json['defaultForTime'] == null ? undefined : json['defaultForTime'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function StateExtendedGet200ResponseRelaysInnerToJSON(json: any): StateExtendedGet200ResponseRelaysInner {
    return StateExtendedGet200ResponseRelaysInnerToJSONTyped(json, false);
}

export function StateExtendedGet200ResponseRelaysInnerToJSONTyped(value?: StateExtendedGet200ResponseRelaysInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relay': RelayToJSON(value['relay']),
        'state': StateGetToJSON(value['state']),
        'stateAfterRestart': StateAfterRestartToJSON(value['stateAfterRestart']),
        'defaultForTime': value['defaultForTime'],
        'name': value['name'],
    };
}

