// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OutputMode } from './OutputMode';
import {
    OutputModeFromJSON,
    OutputModeFromJSONTyped,
    OutputModeToJSON,
    OutputModeToJSONTyped,
} from './OutputMode';

/**
 * Order of outputs and operating mode
 * @export
 * @interface Switch
 */
export interface Switch {
    /**
     * 
     * @type {OutputMode}
     * @memberof Switch
     */
    outputMode: OutputMode;
    /**
     * **Logical order of outputs**
     * @type {Array<number>}
     * @memberof Switch
     */
    outputOrder?: Array<number>;
}



/**
 * Check if a given object implements the Switch interface.
 */
export function instanceOfSwitch(value: object): value is Switch {
    if (!('outputMode' in value) || value['outputMode'] === undefined) return false;
    return true;
}

export function SwitchFromJSON(json: any): Switch {
    return SwitchFromJSONTyped(json, false);
}

export function SwitchFromJSONTyped(json: any, ignoreDiscriminator: boolean): Switch {
    if (json == null) {
        return json;
    }
    return {
        
        'outputMode': OutputModeFromJSON(json['outputMode']),
        'outputOrder': json['outputOrder'] == null ? undefined : json['outputOrder'],
    };
}

export function SwitchToJSON(json: any): Switch {
    return SwitchToJSONTyped(json, false);
}

export function SwitchToJSONTyped(value?: Switch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outputMode': OutputModeToJSON(value['outputMode']),
        'outputOrder': value['outputOrder'],
    };
}

