// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSettingsStateGet200ResponseSettings } from './ApiSettingsStateGet200ResponseSettings';
import {
    ApiSettingsStateGet200ResponseSettingsFromJSON,
    ApiSettingsStateGet200ResponseSettingsFromJSONTyped,
    ApiSettingsStateGet200ResponseSettingsToJSON,
    ApiSettingsStateGet200ResponseSettingsToJSONTyped,
} from './ApiSettingsStateGet200ResponseSettings';

/**
 * 
 * @export
 * @interface ApiSettingsStateGet200Response
 */
export interface ApiSettingsStateGet200Response {
    /**
     * 
     * @type {ApiSettingsStateGet200ResponseSettings}
     * @memberof ApiSettingsStateGet200Response
     */
    settings?: ApiSettingsStateGet200ResponseSettings;
}

/**
 * Check if a given object implements the ApiSettingsStateGet200Response interface.
 */
export function instanceOfApiSettingsStateGet200Response(value: object): value is ApiSettingsStateGet200Response {
    return true;
}

export function ApiSettingsStateGet200ResponseFromJSON(json: any): ApiSettingsStateGet200Response {
    return ApiSettingsStateGet200ResponseFromJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsStateGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'settings': json['settings'] == null ? undefined : ApiSettingsStateGet200ResponseSettingsFromJSON(json['settings']),
    };
}

export function ApiSettingsStateGet200ResponseToJSON(json: any): ApiSettingsStateGet200Response {
    return ApiSettingsStateGet200ResponseToJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseToJSONTyped(value?: ApiSettingsStateGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'settings': ApiSettingsStateGet200ResponseSettingsToJSON(value['settings']),
    };
}

