// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSettingsSetPostRequestSettings } from './ApiSettingsSetPostRequestSettings';
import {
    ApiSettingsSetPostRequestSettingsFromJSON,
    ApiSettingsSetPostRequestSettingsFromJSONTyped,
    ApiSettingsSetPostRequestSettingsToJSON,
    ApiSettingsSetPostRequestSettingsToJSONTyped,
} from './ApiSettingsSetPostRequestSettings';

/**
 * 
 * @export
 * @interface ApiSettingsSetPostRequest
 */
export interface ApiSettingsSetPostRequest {
    /**
     * 
     * @type {ApiSettingsSetPostRequestSettings}
     * @memberof ApiSettingsSetPostRequest
     */
    settings?: ApiSettingsSetPostRequestSettings;
}

/**
 * Check if a given object implements the ApiSettingsSetPostRequest interface.
 */
export function instanceOfApiSettingsSetPostRequest(value: object): value is ApiSettingsSetPostRequest {
    return true;
}

export function ApiSettingsSetPostRequestFromJSON(json: any): ApiSettingsSetPostRequest {
    return ApiSettingsSetPostRequestFromJSONTyped(json, false);
}

export function ApiSettingsSetPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsSetPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'settings': json['settings'] == null ? undefined : ApiSettingsSetPostRequestSettingsFromJSON(json['settings']),
    };
}

export function ApiSettingsSetPostRequestToJSON(json: any): ApiSettingsSetPostRequest {
    return ApiSettingsSetPostRequestToJSONTyped(json, false);
}

export function ApiSettingsSetPostRequestToJSONTyped(value?: ApiSettingsSetPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'settings': ApiSettingsSetPostRequestSettingsToJSON(value['settings']),
    };
}

