// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSettingsStateGet200ResponseSettingsPowerMeasuring } from './ApiSettingsStateGet200ResponseSettingsPowerMeasuring';
import {
    ApiSettingsStateGet200ResponseSettingsPowerMeasuringFromJSON,
    ApiSettingsStateGet200ResponseSettingsPowerMeasuringFromJSONTyped,
    ApiSettingsStateGet200ResponseSettingsPowerMeasuringToJSON,
    ApiSettingsStateGet200ResponseSettingsPowerMeasuringToJSONTyped,
} from './ApiSettingsStateGet200ResponseSettingsPowerMeasuring';
import type { Switch } from './Switch';
import {
    SwitchFromJSON,
    SwitchFromJSONTyped,
    SwitchToJSON,
    SwitchToJSONTyped,
} from './Switch';
import type { ApiSettingsStateGet200ResponseSettingsRelaysInner } from './ApiSettingsStateGet200ResponseSettingsRelaysInner';
import {
    ApiSettingsStateGet200ResponseSettingsRelaysInnerFromJSON,
    ApiSettingsStateGet200ResponseSettingsRelaysInnerFromJSONTyped,
    ApiSettingsStateGet200ResponseSettingsRelaysInnerToJSON,
    ApiSettingsStateGet200ResponseSettingsRelaysInnerToJSONTyped,
} from './ApiSettingsStateGet200ResponseSettingsRelaysInner';
import type { ApiSettingsStateGet200ResponseSettingsStatusLed } from './ApiSettingsStateGet200ResponseSettingsStatusLed';
import {
    ApiSettingsStateGet200ResponseSettingsStatusLedFromJSON,
    ApiSettingsStateGet200ResponseSettingsStatusLedFromJSONTyped,
    ApiSettingsStateGet200ResponseSettingsStatusLedToJSON,
    ApiSettingsStateGet200ResponseSettingsStatusLedToJSONTyped,
} from './ApiSettingsStateGet200ResponseSettingsStatusLed';
import type { ApiSettingsStateGet200ResponseSettingsTunnel } from './ApiSettingsStateGet200ResponseSettingsTunnel';
import {
    ApiSettingsStateGet200ResponseSettingsTunnelFromJSON,
    ApiSettingsStateGet200ResponseSettingsTunnelFromJSONTyped,
    ApiSettingsStateGet200ResponseSettingsTunnelToJSON,
    ApiSettingsStateGet200ResponseSettingsTunnelToJSONTyped,
} from './ApiSettingsStateGet200ResponseSettingsTunnel';

/**
 * Object with **specific** settings
 * @export
 * @interface ApiSettingsStateGet200ResponseSettings
 */
export interface ApiSettingsStateGet200ResponseSettings {
    /**
     * **Name** of BleBox device/controller
     * @type {string}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    deviceName?: string;
    /**
     * 
     * @type {ApiSettingsStateGet200ResponseSettingsTunnel}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    tunnel?: ApiSettingsStateGet200ResponseSettingsTunnel;
    /**
     * 
     * @type {ApiSettingsStateGet200ResponseSettingsStatusLed}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    statusLed?: ApiSettingsStateGet200ResponseSettingsStatusLed;
    /**
     * 
     * @type {ApiSettingsStateGet200ResponseSettingsPowerMeasuring}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    powerMeasuring?: ApiSettingsStateGet200ResponseSettingsPowerMeasuring;
    /**
     * 
     * @type {Array<ApiSettingsStateGet200ResponseSettingsRelaysInner>}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    relays?: Array<ApiSettingsStateGet200ResponseSettingsRelaysInner>;
    /**
     * 
     * @type {Switch}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    _switch?: Switch;
}

/**
 * Check if a given object implements the ApiSettingsStateGet200ResponseSettings interface.
 */
export function instanceOfApiSettingsStateGet200ResponseSettings(value: object): value is ApiSettingsStateGet200ResponseSettings {
    return true;
}

export function ApiSettingsStateGet200ResponseSettingsFromJSON(json: any): ApiSettingsStateGet200ResponseSettings {
    return ApiSettingsStateGet200ResponseSettingsFromJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsStateGet200ResponseSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
        'tunnel': json['tunnel'] == null ? undefined : ApiSettingsStateGet200ResponseSettingsTunnelFromJSON(json['tunnel']),
        'statusLed': json['statusLed'] == null ? undefined : ApiSettingsStateGet200ResponseSettingsStatusLedFromJSON(json['statusLed']),
        'powerMeasuring': json['powerMeasuring'] == null ? undefined : ApiSettingsStateGet200ResponseSettingsPowerMeasuringFromJSON(json['powerMeasuring']),
        'relays': json['relays'] == null ? undefined : ((json['relays'] as Array<any>).map(ApiSettingsStateGet200ResponseSettingsRelaysInnerFromJSON)),
        '_switch': json['switch'] == null ? undefined : SwitchFromJSON(json['switch']),
    };
}

export function ApiSettingsStateGet200ResponseSettingsToJSON(json: any): ApiSettingsStateGet200ResponseSettings {
    return ApiSettingsStateGet200ResponseSettingsToJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsToJSONTyped(value?: ApiSettingsStateGet200ResponseSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceName': value['deviceName'],
        'tunnel': ApiSettingsStateGet200ResponseSettingsTunnelToJSON(value['tunnel']),
        'statusLed': ApiSettingsStateGet200ResponseSettingsStatusLedToJSON(value['statusLed']),
        'powerMeasuring': ApiSettingsStateGet200ResponseSettingsPowerMeasuringToJSON(value['powerMeasuring']),
        'relays': value['relays'] == null ? undefined : ((value['relays'] as Array<any>).map(ApiSettingsStateGet200ResponseSettingsRelaysInnerToJSON)),
        'switch': SwitchToJSON(value['_switch']),
    };
}

