// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Enabled } from './Enabled';
import {
    EnabledFromJSON,
    EnabledFromJSONTyped,
    EnabledToJSON,
    EnabledToJSONTyped,
} from './Enabled';

/**
 * Allows to enable or disable **power measuring module** (**powerConsumption** and **activePower** sensor). If hardware doesn't support power measuring then **this object doesn't exist**
 * @export
 * @interface ApiSettingsStateGet200ResponseSettingsPowerMeasuring
 */
export interface ApiSettingsStateGet200ResponseSettingsPowerMeasuring {
    /**
     * 
     * @type {Enabled}
     * @memberof ApiSettingsStateGet200ResponseSettingsPowerMeasuring
     */
    enabled?: Enabled;
}

/**
 * Check if a given object implements the ApiSettingsStateGet200ResponseSettingsPowerMeasuring interface.
 */
export function instanceOfApiSettingsStateGet200ResponseSettingsPowerMeasuring(value: object): value is ApiSettingsStateGet200ResponseSettingsPowerMeasuring {
    return true;
}

export function ApiSettingsStateGet200ResponseSettingsPowerMeasuringFromJSON(json: any): ApiSettingsStateGet200ResponseSettingsPowerMeasuring {
    return ApiSettingsStateGet200ResponseSettingsPowerMeasuringFromJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsPowerMeasuringFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsStateGet200ResponseSettingsPowerMeasuring {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : EnabledFromJSON(json['enabled']),
    };
}

export function ApiSettingsStateGet200ResponseSettingsPowerMeasuringToJSON(json: any): ApiSettingsStateGet200ResponseSettingsPowerMeasuring {
    return ApiSettingsStateGet200ResponseSettingsPowerMeasuringToJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsPowerMeasuringToJSONTyped(value?: ApiSettingsStateGet200ResponseSettingsPowerMeasuring | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': EnabledToJSON(value['enabled']),
    };
}

