// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>Parameter that show **state of relay**, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>OFF</td> </tr> <tr> <td>**1**</td> <td>ON</td> </tr> </table>
 * @export
 */
export const StateGet = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type StateGet = typeof StateGet[keyof typeof StateGet];


export function instanceOfStateGet(value: any): boolean {
    for (const key in StateGet) {
        if (Object.prototype.hasOwnProperty.call(StateGet, key)) {
            if (StateGet[key as keyof typeof StateGet] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StateGetFromJSON(json: any): StateGet {
    return StateGetFromJSONTyped(json, false);
}

export function StateGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateGet {
    return json as StateGet;
}

export function StateGetToJSON(value?: StateGet | null): any {
    return value as any;
}

export function StateGetToJSONTyped(value: any, ignoreDiscriminator: boolean): StateGet {
    return value as StateGet;
}

