// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatePostRequestRelaysInner } from './StatePostRequestRelaysInner';
import {
    StatePostRequestRelaysInnerFromJSON,
    StatePostRequestRelaysInnerFromJSONTyped,
    StatePostRequestRelaysInnerToJSON,
    StatePostRequestRelaysInnerToJSONTyped,
} from './StatePostRequestRelaysInner';

/**
 * 
 * @export
 * @interface StatePostRequest
 */
export interface StatePostRequest {
    /**
     * List of relays state
     * @type {Array<StatePostRequestRelaysInner>}
     * @memberof StatePostRequest
     */
    relays?: Array<StatePostRequestRelaysInner>;
}

/**
 * Check if a given object implements the StatePostRequest interface.
 */
export function instanceOfStatePostRequest(value: object): value is StatePostRequest {
    return true;
}

export function StatePostRequestFromJSON(json: any): StatePostRequest {
    return StatePostRequestFromJSONTyped(json, false);
}

export function StatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'relays': json['relays'] == null ? undefined : ((json['relays'] as Array<any>).map(StatePostRequestRelaysInnerFromJSON)),
    };
}

export function StatePostRequestToJSON(json: any): StatePostRequest {
    return StatePostRequestToJSONTyped(json, false);
}

export function StatePostRequestToJSONTyped(value?: StatePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relays': value['relays'] == null ? undefined : ((value['relays'] as Array<any>).map(StatePostRequestRelaysInnerToJSON)),
    };
}

