// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Relay } from './Relay';
import {
    RelayFromJSON,
    RelayFromJSONTyped,
    RelayToJSON,
    RelayToJSONTyped,
} from './Relay';
import type { ForTime } from './ForTime';
import {
    ForTimeFromJSON,
    ForTimeFromJSONTyped,
    ForTimeToJSON,
    ForTimeToJSONTyped,
} from './ForTime';
import type { StateSet } from './StateSet';
import {
    StateSetFromJSON,
    StateSetFromJSONTyped,
    StateSetToJSON,
    StateSetToJSONTyped,
} from './StateSet';

/**
 * 
 * @export
 * @interface StatePostRequestRelaysInner
 */
export interface StatePostRequestRelaysInner {
    /**
     * 
     * @type {Relay}
     * @memberof StatePostRequestRelaysInner
     */
    relay: Relay;
    /**
     * 
     * @type {StateSet}
     * @memberof StatePostRequestRelaysInner
     */
    state: StateSet;
    /**
     * 
     * @type {ForTime}
     * @memberof StatePostRequestRelaysInner
     */
    forTime?: ForTime;
}



/**
 * Check if a given object implements the StatePostRequestRelaysInner interface.
 */
export function instanceOfStatePostRequestRelaysInner(value: object): value is StatePostRequestRelaysInner {
    if (!('relay' in value) || value['relay'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function StatePostRequestRelaysInnerFromJSON(json: any): StatePostRequestRelaysInner {
    return StatePostRequestRelaysInnerFromJSONTyped(json, false);
}

export function StatePostRequestRelaysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatePostRequestRelaysInner {
    if (json == null) {
        return json;
    }
    return {
        
        'relay': RelayFromJSON(json['relay']),
        'state': StateSetFromJSON(json['state']),
        'forTime': json['forTime'] == null ? undefined : ForTimeFromJSON(json['forTime']),
    };
}

export function StatePostRequestRelaysInnerToJSON(json: any): StatePostRequestRelaysInner {
    return StatePostRequestRelaysInnerToJSONTyped(json, false);
}

export function StatePostRequestRelaysInnerToJSONTyped(value?: StatePostRequestRelaysInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relay': RelayToJSON(value['relay']),
        'state': StateSetToJSON(value['state']),
        'forTime': ForTimeToJSON(value['forTime']),
    };
}

