// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ns } from './Ns';
import {
    NsFromJSON,
    NsFromJSONTyped,
    NsToJSON,
    NsToJSONTyped,
} from './Ns';

/**
 * Module "forTime" which contain parameters of this functionality. **Requires** **state == 1 (ON)**
 * @export
 * @interface ForTime
 */
export interface ForTime {
    /**
     * Time in **seconds**
     * @type {number}
     * @memberof ForTime
     */
    timeS: number;
    /**
     * 
     * @type {Ns}
     * @memberof ForTime
     */
    ns: Ns;
}



/**
 * Check if a given object implements the ForTime interface.
 */
export function instanceOfForTime(value: object): value is ForTime {
    if (!('timeS' in value) || value['timeS'] === undefined) return false;
    if (!('ns' in value) || value['ns'] === undefined) return false;
    return true;
}

export function ForTimeFromJSON(json: any): ForTime {
    return ForTimeFromJSONTyped(json, false);
}

export function ForTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForTime {
    if (json == null) {
        return json;
    }
    return {
        
        'timeS': json['timeS'],
        'ns': NsFromJSON(json['ns']),
    };
}

export function ForTimeToJSON(json: any): ForTime {
    return ForTimeToJSONTyped(json, false);
}

export function ForTimeToJSONTyped(value?: ForTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeS': value['timeS'],
        'ns': NsToJSON(value['ns']),
    };
}

