// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InfoGet200ResponseDevice } from './InfoGet200ResponseDevice';
import {
    InfoGet200ResponseDeviceFromJSON,
    InfoGet200ResponseDeviceFromJSONTyped,
    InfoGet200ResponseDeviceToJSON,
    InfoGet200ResponseDeviceToJSONTyped,
} from './InfoGet200ResponseDevice';

/**
 * 
 * @export
 * @interface InfoGet200Response
 */
export interface InfoGet200Response {
    /**
     * 
     * @type {InfoGet200ResponseDevice}
     * @memberof InfoGet200Response
     */
    device?: InfoGet200ResponseDevice;
}

/**
 * Check if a given object implements the InfoGet200Response interface.
 */
export function instanceOfInfoGet200Response(value: object): value is InfoGet200Response {
    return true;
}

export function InfoGet200ResponseFromJSON(json: any): InfoGet200Response {
    return InfoGet200ResponseFromJSONTyped(json, false);
}

export function InfoGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'device': json['device'] == null ? undefined : InfoGet200ResponseDeviceFromJSON(json['device']),
    };
}

export function InfoGet200ResponseToJSON(json: any): InfoGet200Response {
    return InfoGet200ResponseToJSONTyped(json, false);
}

export function InfoGet200ResponseToJSONTyped(value?: InfoGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device': InfoGet200ResponseDeviceToJSON(value['device']),
    };
}

