// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>**Next state** after previous action (e.g. set for time), where: <br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>OFF</td> </tr> </table>
 * @export
 */
export const Ns = {
    NUMBER_0: 0
} as const;
export type Ns = typeof Ns[keyof typeof Ns];


export function instanceOfNs(value: any): boolean {
    for (const key in Ns) {
        if (Object.prototype.hasOwnProperty.call(Ns, key)) {
            if (Ns[key as keyof typeof Ns] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NsFromJSON(json: any): Ns {
    return NsFromJSONTyped(json, false);
}

export function NsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ns {
    return json as Ns;
}

export function NsToJSON(value?: Ns | null): any {
    return value as any;
}

export function NsToJSONTyped(value: any, ignoreDiscriminator: boolean): Ns {
    return value as Ns;
}

