// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * **Type** of power measurement
 * @export
 */
export const SensorType = {
    ActivePower: 'activePower'
} as const;
export type SensorType = typeof SensorType[keyof typeof SensorType];


export function instanceOfSensorType(value: any): boolean {
    for (const key in SensorType) {
        if (Object.prototype.hasOwnProperty.call(SensorType, key)) {
            if (SensorType[key as keyof typeof SensorType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SensorTypeFromJSON(json: any): SensorType {
    return SensorTypeFromJSONTyped(json, false);
}

export function SensorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorType {
    return json as SensorType;
}

export function SensorTypeToJSON(value?: SensorType | null): any {
    return value as any;
}

export function SensorTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SensorType {
    return value as SensorType;
}

