// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Trend - not used, always 0
 * @export
 */
export const SensorTrend = {
    NUMBER_0: 0
} as const;
export type SensorTrend = typeof SensorTrend[keyof typeof SensorTrend];


export function instanceOfSensorTrend(value: any): boolean {
    for (const key in SensorTrend) {
        if (Object.prototype.hasOwnProperty.call(SensorTrend, key)) {
            if (SensorTrend[key as keyof typeof SensorTrend] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SensorTrendFromJSON(json: any): SensorTrend {
    return SensorTrendFromJSONTyped(json, false);
}

export function SensorTrendFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorTrend {
    return json as SensorTrend;
}

export function SensorTrendToJSON(value?: SensorTrend | null): any {
    return value as any;
}

export function SensorTrendToJSONTyped(value: any, ignoreDiscriminator: boolean): SensorTrend {
    return value as SensorTrend;
}

