// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StateExtendedGet200ResponseRelaysInner } from './StateExtendedGet200ResponseRelaysInner';
import {
    StateExtendedGet200ResponseRelaysInnerFromJSON,
    StateExtendedGet200ResponseRelaysInnerFromJSONTyped,
    StateExtendedGet200ResponseRelaysInnerToJSON,
    StateExtendedGet200ResponseRelaysInnerToJSONTyped,
} from './StateExtendedGet200ResponseRelaysInner';
import type { PowerMeasuring } from './PowerMeasuring';
import {
    PowerMeasuringFromJSON,
    PowerMeasuringFromJSONTyped,
    PowerMeasuringToJSON,
    PowerMeasuringToJSONTyped,
} from './PowerMeasuring';
import type { Sensor } from './Sensor';
import {
    SensorFromJSON,
    SensorFromJSONTyped,
    SensorToJSON,
    SensorToJSONTyped,
} from './Sensor';

/**
 * 
 * @export
 * @interface StateExtendedGet200Response
 */
export interface StateExtendedGet200Response {
    /**
     * List of **relays state** with **additional information**
     * @type {Array<StateExtendedGet200ResponseRelaysInner>}
     * @memberof StateExtendedGet200Response
     */
    relays?: Array<StateExtendedGet200ResponseRelaysInner>;
    /**
     * 
     * @type {PowerMeasuring}
     * @memberof StateExtendedGet200Response
     */
    powerMeasuring?: PowerMeasuring;
    /**
     * **List of active sensors**. If there is no active sensors then array doesn't exist
     * @type {Array<Sensor>}
     * @memberof StateExtendedGet200Response
     */
    sensors?: Array<Sensor>;
}

/**
 * Check if a given object implements the StateExtendedGet200Response interface.
 */
export function instanceOfStateExtendedGet200Response(value: object): value is StateExtendedGet200Response {
    return true;
}

export function StateExtendedGet200ResponseFromJSON(json: any): StateExtendedGet200Response {
    return StateExtendedGet200ResponseFromJSONTyped(json, false);
}

export function StateExtendedGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateExtendedGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'relays': json['relays'] == null ? undefined : ((json['relays'] as Array<any>).map(StateExtendedGet200ResponseRelaysInnerFromJSON)),
        'powerMeasuring': json['powerMeasuring'] == null ? undefined : PowerMeasuringFromJSON(json['powerMeasuring']),
        'sensors': json['sensors'] == null ? undefined : ((json['sensors'] as Array<any>).map(SensorFromJSON)),
    };
}

export function StateExtendedGet200ResponseToJSON(json: any): StateExtendedGet200Response {
    return StateExtendedGet200ResponseToJSONTyped(json, false);
}

export function StateExtendedGet200ResponseToJSONTyped(value?: StateExtendedGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relays': value['relays'] == null ? undefined : ((value['relays'] as Array<any>).map(StateExtendedGet200ResponseRelaysInnerToJSON)),
        'powerMeasuring': PowerMeasuringToJSON(value['powerMeasuring']),
        'sensors': value['sensors'] == null ? undefined : ((value['sensors'] as Array<any>).map(SensorToJSON)),
    };
}

