// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StateGet200ResponseRelaysInner } from './StateGet200ResponseRelaysInner';
import {
    StateGet200ResponseRelaysInnerFromJSON,
    StateGet200ResponseRelaysInnerFromJSONTyped,
    StateGet200ResponseRelaysInnerToJSON,
    StateGet200ResponseRelaysInnerToJSONTyped,
} from './StateGet200ResponseRelaysInner';

/**
 * 
 * @export
 * @interface StateGet200Response
 */
export interface StateGet200Response {
    /**
     * List of **relays state**
     * @type {Array<StateGet200ResponseRelaysInner>}
     * @memberof StateGet200Response
     */
    relays?: Array<StateGet200ResponseRelaysInner>;
}

/**
 * Check if a given object implements the StateGet200Response interface.
 */
export function instanceOfStateGet200Response(value: object): value is StateGet200Response {
    return true;
}

export function StateGet200ResponseFromJSON(json: any): StateGet200Response {
    return StateGet200ResponseFromJSONTyped(json, false);
}

export function StateGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'relays': json['relays'] == null ? undefined : ((json['relays'] as Array<any>).map(StateGet200ResponseRelaysInnerFromJSON)),
    };
}

export function StateGet200ResponseToJSON(json: any): StateGet200Response {
    return StateGet200ResponseToJSONTyped(json, false);
}

export function StateGet200ResponseToJSONTyped(value?: StateGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relays': value['relays'] == null ? undefined : ((value['relays'] as Array<any>).map(StateGet200ResponseRelaysInnerToJSON)),
    };
}

