// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Relay } from './Relay';
import {
    RelayFromJSON,
    RelayFromJSONTyped,
    RelayToJSON,
    RelayToJSONTyped,
} from './Relay';
import type { StateGet } from './StateGet';
import {
    StateGetFromJSON,
    StateGetFromJSONTyped,
    StateGetToJSON,
    StateGetToJSONTyped,
} from './StateGet';

/**
 * 
 * @export
 * @interface StateGet200ResponseRelaysInner
 */
export interface StateGet200ResponseRelaysInner {
    /**
     * 
     * @type {Relay}
     * @memberof StateGet200ResponseRelaysInner
     */
    relay?: Relay;
    /**
     * 
     * @type {StateGet}
     * @memberof StateGet200ResponseRelaysInner
     */
    state?: StateGet;
}



/**
 * Check if a given object implements the StateGet200ResponseRelaysInner interface.
 */
export function instanceOfStateGet200ResponseRelaysInner(value: object): value is StateGet200ResponseRelaysInner {
    return true;
}

export function StateGet200ResponseRelaysInnerFromJSON(json: any): StateGet200ResponseRelaysInner {
    return StateGet200ResponseRelaysInnerFromJSONTyped(json, false);
}

export function StateGet200ResponseRelaysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateGet200ResponseRelaysInner {
    if (json == null) {
        return json;
    }
    return {
        
        'relay': json['relay'] == null ? undefined : RelayFromJSON(json['relay']),
        'state': json['state'] == null ? undefined : StateGetFromJSON(json['state']),
    };
}

export function StateGet200ResponseRelaysInnerToJSON(json: any): StateGet200ResponseRelaysInner {
    return StateGet200ResponseRelaysInnerToJSONTyped(json, false);
}

export function StateGet200ResponseRelaysInnerToJSONTyped(value?: StateGet200ResponseRelaysInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relay': RelayToJSON(value['relay']),
        'state': StateGetToJSON(value['state']),
    };
}

