// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    StateExtendedGet200Response,
    StateGet200Response,
    StatePostRequest,
} from '../models/index';

export interface ControlStateApiApiRelaySetPostRequest {
    statePostRequest?: StatePostRequest;
}

export interface ControlStateApiStatePostOperationRequest {
    statePostRequest?: StatePostRequest;
}

/**
 * 
 */
export class ControlStateApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiRelayExtendedStateGet without sending the request
     * @deprecated
     */
    async apiRelayExtendedStateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/relay/extended/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **extended information** about **device and relays**<br>  *(all parameters needed to display user interface)*<br> <br><br>**It is deprecated** -> look at:
     * Extended relay state
     * @deprecated
     */
    async apiRelayExtendedStateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateExtendedGet200Response>> {
        const requestOptions = await this.apiRelayExtendedStateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **extended information** about **device and relays**<br>  *(all parameters needed to display user interface)*<br> <br><br>**It is deprecated** -> look at:
     * Extended relay state
     * @deprecated
     */
    async apiRelayExtendedStateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateExtendedGet200Response> {
        const response = await this.apiRelayExtendedStateGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRelaySetPost without sending the request
     * @deprecated
     */
    async apiRelaySetPostRequestOpts(requestParameters: ControlStateApiApiRelaySetPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/relay/set`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['statePostRequest'],
        };
    }

    /**
     * Allows to **set** desired **relay state** <br> *(turn on, turn off, toggle state, turn on for time)* <br><br>**It is deprecated** -> look at:
     * Set relay
     * @deprecated
     */
    async apiRelaySetPostRaw(requestParameters: ControlStateApiApiRelaySetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.apiRelaySetPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Allows to **set** desired **relay state** <br> *(turn on, turn off, toggle state, turn on for time)* <br><br>**It is deprecated** -> look at:
     * Set relay
     * @deprecated
     */
    async apiRelaySetPost(requestParameters: ControlStateApiApiRelaySetPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.apiRelaySetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRelayStateGet without sending the request
     * @deprecated
     */
    async apiRelayStateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/relay/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns information about **relays state** <br><br>**It is deprecated** -> look at:
     * Relay state
     * @deprecated
     */
    async apiRelayStateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.apiRelayStateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns information about **relays state** <br><br>**It is deprecated** -> look at:
     * Relay state
     * @deprecated
     */
    async apiRelayStateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.apiRelayStateGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stateExtendedGet without sending the request
     */
    async stateExtendedGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/state/extended`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns **extended information** about **device and relays**<br>  *(all parameters needed to display user interface)*
     * Extended device state
     */
    async stateExtendedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateExtendedGet200Response>> {
        const requestOptions = await this.stateExtendedGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns **extended information** about **device and relays**<br>  *(all parameters needed to display user interface)*
     * Extended device state
     */
    async stateExtendedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateExtendedGet200Response> {
        const response = await this.stateExtendedGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stateGet without sending the request
     */
    async stateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns information about **relays state**
     * Device state
     */
    async stateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.stateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns information about **relays state**
     * Device state
     */
    async stateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.stateGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for statePost without sending the request
     */
    async statePostRequestOpts(requestParameters: ControlStateApiStatePostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/state`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['statePostRequest'],
        };
    }

    /**
     * Allow to set desired relay state (ON, OFF, TOGGLE, FORTIME)
     * State set
     */
    async statePostRaw(requestParameters: ControlStateApiStatePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.statePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Allow to set desired relay state (ON, OFF, TOGGLE, FORTIME)
     * State set
     */
    async statePost(requestParameters: ControlStateApiStatePostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.statePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
