// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for Device Manager for BleBox.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    ApiHealthGet200Response,
} from '../models/index';

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiHealthGet without sending the request
     */
    async apiHealthGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Liveness probe
     */
    async apiHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiHealthGet200Response>> {
        const requestOptions = await this.apiHealthGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Liveness probe
     */
    async apiHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiHealthGet200Response> {
        const response = await this.apiHealthGetRaw(initOverrides);
        return await response.value();
    }

}
