// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for Device Manager for BleBox.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDiscoveryDevicesGet200ResponseDevicesInner } from './ApiDiscoveryDevicesGet200ResponseDevicesInner';
import {
    ApiDiscoveryDevicesGet200ResponseDevicesInnerFromJSON,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerFromJSONTyped,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerToJSON,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerToJSONTyped,
} from './ApiDiscoveryDevicesGet200ResponseDevicesInner';

/**
 * 
 * @export
 * @interface ApiDiscoveryDevicesGet200Response
 */
export interface ApiDiscoveryDevicesGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiDiscoveryDevicesGet200Response
     */
    scanning: boolean;
    /**
     * 
     * @type {Array<ApiDiscoveryDevicesGet200ResponseDevicesInner>}
     * @memberof ApiDiscoveryDevicesGet200Response
     */
    devices: Array<ApiDiscoveryDevicesGet200ResponseDevicesInner>;
}

/**
 * Check if a given object implements the ApiDiscoveryDevicesGet200Response interface.
 */
export function instanceOfApiDiscoveryDevicesGet200Response(value: object): value is ApiDiscoveryDevicesGet200Response {
    if (!('scanning' in value) || value['scanning'] === undefined) return false;
    if (!('devices' in value) || value['devices'] === undefined) return false;
    return true;
}

export function ApiDiscoveryDevicesGet200ResponseFromJSON(json: any): ApiDiscoveryDevicesGet200Response {
    return ApiDiscoveryDevicesGet200ResponseFromJSONTyped(json, false);
}

export function ApiDiscoveryDevicesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDiscoveryDevicesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'scanning': json['scanning'],
        'devices': ((json['devices'] as Array<any>).map(ApiDiscoveryDevicesGet200ResponseDevicesInnerFromJSON)),
    };
}

export function ApiDiscoveryDevicesGet200ResponseToJSON(json: any): ApiDiscoveryDevicesGet200Response {
    return ApiDiscoveryDevicesGet200ResponseToJSONTyped(json, false);
}

export function ApiDiscoveryDevicesGet200ResponseToJSONTyped(value?: ApiDiscoveryDevicesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scanning': value['scanning'],
        'devices': ((value['devices'] as Array<any>).map(ApiDiscoveryDevicesGet200ResponseDevicesInnerToJSON)),
    };
}

