// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for Device Manager for BleBox.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel
 */
export interface ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel {
}

/**
 * Check if a given object implements the ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel interface.
 */
export function instanceOfApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel(value: object): value is ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel {
    return true;
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelFromJSON(json: any): ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel {
    return ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelFromJSONTyped(json, false);
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel {
    return json;
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelToJSON(json: any): ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel {
    return ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelToJSONTyped(json, false);
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelToJSONTyped(value?: ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

