// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for Device Manager for BleBox.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice } from './ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice';
import {
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceFromJSON,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceFromJSONTyped,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceToJSON,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceToJSONTyped,
} from './ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice';

/**
 * 
 * @export
 * @interface ApiDiscoveryDevicesGet200ResponseDevicesInner
 */
export interface ApiDiscoveryDevicesGet200ResponseDevicesInner {
    /**
     * 
     * @type {string}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInner
     */
    ip: string;
    /**
     * 
     * @type {ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInner
     */
    device: ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice;
    /**
     * 
     * @type {string}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInner
     */
    discoveredAt: string;
}

/**
 * Check if a given object implements the ApiDiscoveryDevicesGet200ResponseDevicesInner interface.
 */
export function instanceOfApiDiscoveryDevicesGet200ResponseDevicesInner(value: object): value is ApiDiscoveryDevicesGet200ResponseDevicesInner {
    if (!('ip' in value) || value['ip'] === undefined) return false;
    if (!('device' in value) || value['device'] === undefined) return false;
    if (!('discoveredAt' in value) || value['discoveredAt'] === undefined) return false;
    return true;
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerFromJSON(json: any): ApiDiscoveryDevicesGet200ResponseDevicesInner {
    return ApiDiscoveryDevicesGet200ResponseDevicesInnerFromJSONTyped(json, false);
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDiscoveryDevicesGet200ResponseDevicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'ip': json['ip'],
        'device': ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceFromJSON(json['device']),
        'discoveredAt': json['discoveredAt'],
    };
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerToJSON(json: any): ApiDiscoveryDevicesGet200ResponseDevicesInner {
    return ApiDiscoveryDevicesGet200ResponseDevicesInnerToJSONTyped(json, false);
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerToJSONTyped(value?: ApiDiscoveryDevicesGet200ResponseDevicesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ip': value['ip'],
        'device': ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceToJSON(value['device']),
        'discoveredAt': value['discoveredAt'],
    };
}

