// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDeviceUptimeGet200Response
 */
export interface ApiDeviceUptimeGet200Response {
    /**
     * Number of **seconds** since the device was turned on
     * @type {number}
     * @memberof ApiDeviceUptimeGet200Response
     */
    upTimeS?: number;
}

/**
 * Check if a given object implements the ApiDeviceUptimeGet200Response interface.
 */
export function instanceOfApiDeviceUptimeGet200Response(value: object): value is ApiDeviceUptimeGet200Response {
    return true;
}

export function ApiDeviceUptimeGet200ResponseFromJSON(json: any): ApiDeviceUptimeGet200Response {
    return ApiDeviceUptimeGet200ResponseFromJSONTyped(json, false);
}

export function ApiDeviceUptimeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDeviceUptimeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'upTimeS': json['upTimeS'] == null ? undefined : json['upTimeS'],
    };
}

export function ApiDeviceUptimeGet200ResponseToJSON(json: any): ApiDeviceUptimeGet200Response {
    return ApiDeviceUptimeGet200ResponseToJSONTyped(json, false);
}

export function ApiDeviceUptimeGet200ResponseToJSONTyped(value?: ApiDeviceUptimeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'upTimeS': value['upTimeS'],
    };
}

