// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRgbwExtendedSetPostRequestRgbw } from './ApiRgbwExtendedSetPostRequestRgbw';
import {
    ApiRgbwExtendedSetPostRequestRgbwFromJSON,
    ApiRgbwExtendedSetPostRequestRgbwFromJSONTyped,
    ApiRgbwExtendedSetPostRequestRgbwToJSON,
    ApiRgbwExtendedSetPostRequestRgbwToJSONTyped,
} from './ApiRgbwExtendedSetPostRequestRgbw';

/**
 * 
 * @export
 * @interface ApiRgbwExtendedSetPostRequest
 */
export interface ApiRgbwExtendedSetPostRequest {
    /**
     * 
     * @type {ApiRgbwExtendedSetPostRequestRgbw}
     * @memberof ApiRgbwExtendedSetPostRequest
     */
    rgbw?: ApiRgbwExtendedSetPostRequestRgbw;
}

/**
 * Check if a given object implements the ApiRgbwExtendedSetPostRequest interface.
 */
export function instanceOfApiRgbwExtendedSetPostRequest(value: object): value is ApiRgbwExtendedSetPostRequest {
    return true;
}

export function ApiRgbwExtendedSetPostRequestFromJSON(json: any): ApiRgbwExtendedSetPostRequest {
    return ApiRgbwExtendedSetPostRequestFromJSONTyped(json, false);
}

export function ApiRgbwExtendedSetPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRgbwExtendedSetPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rgbw': json['rgbw'] == null ? undefined : ApiRgbwExtendedSetPostRequestRgbwFromJSON(json['rgbw']),
    };
}

export function ApiRgbwExtendedSetPostRequestToJSON(json: any): ApiRgbwExtendedSetPostRequest {
    return ApiRgbwExtendedSetPostRequestToJSONTyped(json, false);
}

export function ApiRgbwExtendedSetPostRequestToJSONTyped(value?: ApiRgbwExtendedSetPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rgbw': ApiRgbwExtendedSetPostRequestRgbwToJSON(value['rgbw']),
    };
}

