// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRgbwSetPostRequestRgbw } from './ApiRgbwSetPostRequestRgbw';
import {
    ApiRgbwSetPostRequestRgbwFromJSON,
    ApiRgbwSetPostRequestRgbwFromJSONTyped,
    ApiRgbwSetPostRequestRgbwToJSON,
    ApiRgbwSetPostRequestRgbwToJSONTyped,
} from './ApiRgbwSetPostRequestRgbw';

/**
 * 
 * @export
 * @interface ApiRgbwSetPostRequest
 */
export interface ApiRgbwSetPostRequest {
    /**
     * 
     * @type {ApiRgbwSetPostRequestRgbw}
     * @memberof ApiRgbwSetPostRequest
     */
    rgbw?: ApiRgbwSetPostRequestRgbw;
}

/**
 * Check if a given object implements the ApiRgbwSetPostRequest interface.
 */
export function instanceOfApiRgbwSetPostRequest(value: object): value is ApiRgbwSetPostRequest {
    return true;
}

export function ApiRgbwSetPostRequestFromJSON(json: any): ApiRgbwSetPostRequest {
    return ApiRgbwSetPostRequestFromJSONTyped(json, false);
}

export function ApiRgbwSetPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRgbwSetPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rgbw': json['rgbw'] == null ? undefined : ApiRgbwSetPostRequestRgbwFromJSON(json['rgbw']),
    };
}

export function ApiRgbwSetPostRequestToJSON(json: any): ApiRgbwSetPostRequest {
    return ApiRgbwSetPostRequestToJSONTyped(json, false);
}

export function ApiRgbwSetPostRequestToJSONTyped(value?: ApiRgbwSetPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rgbw': ApiRgbwSetPostRequestRgbwToJSON(value['rgbw']),
    };
}

