// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OutputMode } from './OutputMode';
import {
    OutputModeFromJSON,
    OutputModeFromJSONTyped,
    OutputModeToJSON,
    OutputModeToJSONTyped,
} from './OutputMode';
import type { ColorMode } from './ColorMode';
import {
    ColorModeFromJSON,
    ColorModeFromJSONTyped,
    ColorModeToJSON,
    ColorModeToJSONTyped,
} from './ColorMode';
import type { ButtonMode } from './ButtonMode';
import {
    ButtonModeFromJSON,
    ButtonModeFromJSONTyped,
    ButtonModeToJSON,
    ButtonModeToJSONTyped,
} from './ButtonMode';
import type { PwmFreq } from './PwmFreq';
import {
    PwmFreqFromJSON,
    PwmFreqFromJSONTyped,
    PwmFreqToJSON,
    PwmFreqToJSONTyped,
} from './PwmFreq';

/**
 * An object which contain **specific settings**
 * @export
 * @interface ApiSettingsSetPostRequestSettingsRgbw
 */
export interface ApiSettingsSetPostRequestSettingsRgbw {
    /**
     * 
     * @type {PwmFreq}
     * @memberof ApiSettingsSetPostRequestSettingsRgbw
     */
    pwmFreq?: PwmFreq;
    /**
     * 
     * @type {ColorMode}
     * @memberof ApiSettingsSetPostRequestSettingsRgbw
     */
    colorMode?: ColorMode;
    /**
     * 
     * @type {OutputMode}
     * @memberof ApiSettingsSetPostRequestSettingsRgbw
     */
    outputMode?: OutputMode;
    /**
     * 
     * @type {ButtonMode}
     * @memberof ApiSettingsSetPostRequestSettingsRgbw
     */
    buttonMode?: ButtonMode;
}



/**
 * Check if a given object implements the ApiSettingsSetPostRequestSettingsRgbw interface.
 */
export function instanceOfApiSettingsSetPostRequestSettingsRgbw(value: object): value is ApiSettingsSetPostRequestSettingsRgbw {
    return true;
}

export function ApiSettingsSetPostRequestSettingsRgbwFromJSON(json: any): ApiSettingsSetPostRequestSettingsRgbw {
    return ApiSettingsSetPostRequestSettingsRgbwFromJSONTyped(json, false);
}

export function ApiSettingsSetPostRequestSettingsRgbwFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsSetPostRequestSettingsRgbw {
    if (json == null) {
        return json;
    }
    return {
        
        'pwmFreq': json['pwmFreq'] == null ? undefined : PwmFreqFromJSON(json['pwmFreq']),
        'colorMode': json['colorMode'] == null ? undefined : ColorModeFromJSON(json['colorMode']),
        'outputMode': json['outputMode'] == null ? undefined : OutputModeFromJSON(json['outputMode']),
        'buttonMode': json['buttonMode'] == null ? undefined : ButtonModeFromJSON(json['buttonMode']),
    };
}

export function ApiSettingsSetPostRequestSettingsRgbwToJSON(json: any): ApiSettingsSetPostRequestSettingsRgbw {
    return ApiSettingsSetPostRequestSettingsRgbwToJSONTyped(json, false);
}

export function ApiSettingsSetPostRequestSettingsRgbwToJSONTyped(value?: ApiSettingsSetPostRequestSettingsRgbw | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pwmFreq': PwmFreqToJSON(value['pwmFreq']),
        'colorMode': ColorModeToJSON(value['colorMode']),
        'outputMode': OutputModeToJSON(value['outputMode']),
        'buttonMode': ButtonModeToJSON(value['buttonMode']),
    };
}

