// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OutputMode } from './OutputMode';
import {
    OutputModeFromJSON,
    OutputModeFromJSONTyped,
    OutputModeToJSON,
    OutputModeToJSONTyped,
} from './OutputMode';
import type { FieldsPreferencesInner } from './FieldsPreferencesInner';
import {
    FieldsPreferencesInnerFromJSON,
    FieldsPreferencesInnerFromJSONTyped,
    FieldsPreferencesInnerToJSON,
    FieldsPreferencesInnerToJSONTyped,
} from './FieldsPreferencesInner';
import type { ColorMode } from './ColorMode';
import {
    ColorModeFromJSON,
    ColorModeFromJSONTyped,
    ColorModeToJSON,
    ColorModeToJSONTyped,
} from './ColorMode';
import type { ButtonMode } from './ButtonMode';
import {
    ButtonModeFromJSON,
    ButtonModeFromJSONTyped,
    ButtonModeToJSON,
    ButtonModeToJSONTyped,
} from './ButtonMode';
import type { PwmFreq } from './PwmFreq';
import {
    PwmFreqFromJSON,
    PwmFreqFromJSONTyped,
    PwmFreqToJSON,
    PwmFreqToJSONTyped,
} from './PwmFreq';

/**
 * An object which contain **specific settings**
 * @export
 * @interface ApiSettingsStateGet200ResponseSettingsRgbw
 */
export interface ApiSettingsStateGet200ResponseSettingsRgbw {
    /**
     * 
     * @type {ColorMode}
     * @memberof ApiSettingsStateGet200ResponseSettingsRgbw
     */
    colorMode?: ColorMode;
    /**
     * 
     * @type {OutputMode}
     * @memberof ApiSettingsStateGet200ResponseSettingsRgbw
     */
    outputMode?: OutputMode;
    /**
     * 
     * @type {PwmFreq}
     * @memberof ApiSettingsStateGet200ResponseSettingsRgbw
     */
    pwmFreq?: PwmFreq;
    /**
     * 
     * @type {ButtonMode}
     * @memberof ApiSettingsStateGet200ResponseSettingsRgbw
     */
    buttonMode?: ButtonMode;
    /**
     * **Values of settings which are allowed by controller** (hardware/firmware version) <br> *(Parameters needed to display settings page in user interface)*
     * @type {Array<FieldsPreferencesInner>}
     * @memberof ApiSettingsStateGet200ResponseSettingsRgbw
     */
    fieldsPreferences?: Array<FieldsPreferencesInner>;
}



/**
 * Check if a given object implements the ApiSettingsStateGet200ResponseSettingsRgbw interface.
 */
export function instanceOfApiSettingsStateGet200ResponseSettingsRgbw(value: object): value is ApiSettingsStateGet200ResponseSettingsRgbw {
    return true;
}

export function ApiSettingsStateGet200ResponseSettingsRgbwFromJSON(json: any): ApiSettingsStateGet200ResponseSettingsRgbw {
    return ApiSettingsStateGet200ResponseSettingsRgbwFromJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsRgbwFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsStateGet200ResponseSettingsRgbw {
    if (json == null) {
        return json;
    }
    return {
        
        'colorMode': json['colorMode'] == null ? undefined : ColorModeFromJSON(json['colorMode']),
        'outputMode': json['outputMode'] == null ? undefined : OutputModeFromJSON(json['outputMode']),
        'pwmFreq': json['pwmFreq'] == null ? undefined : PwmFreqFromJSON(json['pwmFreq']),
        'buttonMode': json['buttonMode'] == null ? undefined : ButtonModeFromJSON(json['buttonMode']),
        'fieldsPreferences': json['fieldsPreferences'] == null ? undefined : ((json['fieldsPreferences'] as Array<any>).map(FieldsPreferencesInnerFromJSON)),
    };
}

export function ApiSettingsStateGet200ResponseSettingsRgbwToJSON(json: any): ApiSettingsStateGet200ResponseSettingsRgbw {
    return ApiSettingsStateGet200ResponseSettingsRgbwToJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsRgbwToJSONTyped(value?: ApiSettingsStateGet200ResponseSettingsRgbw | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'colorMode': ColorModeToJSON(value['colorMode']),
        'outputMode': OutputModeToJSON(value['outputMode']),
        'pwmFreq': PwmFreqToJSON(value['pwmFreq']),
        'buttonMode': ButtonModeToJSON(value['buttonMode']),
        'fieldsPreferences': value['fieldsPreferences'] == null ? undefined : ((value['fieldsPreferences'] as Array<any>).map(FieldsPreferencesInnerToJSON)),
    };
}

