// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSettingsStateGet200ResponseSettingsRgbw } from './ApiSettingsStateGet200ResponseSettingsRgbw';
import {
    ApiSettingsStateGet200ResponseSettingsRgbwFromJSON,
    ApiSettingsStateGet200ResponseSettingsRgbwFromJSONTyped,
    ApiSettingsStateGet200ResponseSettingsRgbwToJSON,
    ApiSettingsStateGet200ResponseSettingsRgbwToJSONTyped,
} from './ApiSettingsStateGet200ResponseSettingsRgbw';
import type { ApiSettingsStateGet200ResponseSettingsStatusLed } from './ApiSettingsStateGet200ResponseSettingsStatusLed';
import {
    ApiSettingsStateGet200ResponseSettingsStatusLedFromJSON,
    ApiSettingsStateGet200ResponseSettingsStatusLedFromJSONTyped,
    ApiSettingsStateGet200ResponseSettingsStatusLedToJSON,
    ApiSettingsStateGet200ResponseSettingsStatusLedToJSONTyped,
} from './ApiSettingsStateGet200ResponseSettingsStatusLed';
import type { ApiSettingsStateGet200ResponseSettingsTunnel } from './ApiSettingsStateGet200ResponseSettingsTunnel';
import {
    ApiSettingsStateGet200ResponseSettingsTunnelFromJSON,
    ApiSettingsStateGet200ResponseSettingsTunnelFromJSONTyped,
    ApiSettingsStateGet200ResponseSettingsTunnelToJSON,
    ApiSettingsStateGet200ResponseSettingsTunnelToJSONTyped,
} from './ApiSettingsStateGet200ResponseSettingsTunnel';

/**
 * An object which contain **specific settings**
 * @export
 * @interface ApiSettingsStateGet200ResponseSettings
 */
export interface ApiSettingsStateGet200ResponseSettings {
    /**
     * **Name** of BleBox device/controller
     * @type {string}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    deviceName?: string;
    /**
     * 
     * @type {ApiSettingsStateGet200ResponseSettingsTunnel}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    tunnel?: ApiSettingsStateGet200ResponseSettingsTunnel;
    /**
     * 
     * @type {ApiSettingsStateGet200ResponseSettingsStatusLed}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    statusLed?: ApiSettingsStateGet200ResponseSettingsStatusLed;
    /**
     * 
     * @type {ApiSettingsStateGet200ResponseSettingsRgbw}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    rgbw?: ApiSettingsStateGet200ResponseSettingsRgbw;
}

/**
 * Check if a given object implements the ApiSettingsStateGet200ResponseSettings interface.
 */
export function instanceOfApiSettingsStateGet200ResponseSettings(value: object): value is ApiSettingsStateGet200ResponseSettings {
    return true;
}

export function ApiSettingsStateGet200ResponseSettingsFromJSON(json: any): ApiSettingsStateGet200ResponseSettings {
    return ApiSettingsStateGet200ResponseSettingsFromJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsStateGet200ResponseSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
        'tunnel': json['tunnel'] == null ? undefined : ApiSettingsStateGet200ResponseSettingsTunnelFromJSON(json['tunnel']),
        'statusLed': json['statusLed'] == null ? undefined : ApiSettingsStateGet200ResponseSettingsStatusLedFromJSON(json['statusLed']),
        'rgbw': json['rgbw'] == null ? undefined : ApiSettingsStateGet200ResponseSettingsRgbwFromJSON(json['rgbw']),
    };
}

export function ApiSettingsStateGet200ResponseSettingsToJSON(json: any): ApiSettingsStateGet200ResponseSettings {
    return ApiSettingsStateGet200ResponseSettingsToJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsToJSONTyped(value?: ApiSettingsStateGet200ResponseSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceName': value['deviceName'],
        'tunnel': ApiSettingsStateGet200ResponseSettingsTunnelToJSON(value['tunnel']),
        'statusLed': ApiSettingsStateGet200ResponseSettingsStatusLedToJSON(value['statusLed']),
        'rgbw': ApiSettingsStateGet200ResponseSettingsRgbwToJSON(value['rgbw']),
    };
}

