// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSettingsSetPostRequestSettingsRgbw } from './ApiSettingsSetPostRequestSettingsRgbw';
import {
    ApiSettingsSetPostRequestSettingsRgbwFromJSON,
    ApiSettingsSetPostRequestSettingsRgbwFromJSONTyped,
    ApiSettingsSetPostRequestSettingsRgbwToJSON,
    ApiSettingsSetPostRequestSettingsRgbwToJSONTyped,
} from './ApiSettingsSetPostRequestSettingsRgbw';
import type { Tunnel } from './Tunnel';
import {
    TunnelFromJSON,
    TunnelFromJSONTyped,
    TunnelToJSON,
    TunnelToJSONTyped,
} from './Tunnel';
import type { StatusLed } from './StatusLed';
import {
    StatusLedFromJSON,
    StatusLedFromJSONTyped,
    StatusLedToJSON,
    StatusLedToJSONTyped,
} from './StatusLed';
import type { DeviceName } from './DeviceName';
import {
    DeviceNameFromJSON,
    DeviceNameFromJSONTyped,
    DeviceNameToJSON,
    DeviceNameToJSONTyped,
} from './DeviceName';

/**
 * An object which contain **specific settings**
 * @export
 * @interface ApiSettingsSetPostRequestSettings
 */
export interface ApiSettingsSetPostRequestSettings {
    /**
     * 
     * @type {DeviceName}
     * @memberof ApiSettingsSetPostRequestSettings
     */
    deviceName?: DeviceName;
    /**
     * 
     * @type {Tunnel}
     * @memberof ApiSettingsSetPostRequestSettings
     */
    tunnel?: Tunnel;
    /**
     * 
     * @type {StatusLed}
     * @memberof ApiSettingsSetPostRequestSettings
     */
    statusLed?: StatusLed;
    /**
     * 
     * @type {ApiSettingsSetPostRequestSettingsRgbw}
     * @memberof ApiSettingsSetPostRequestSettings
     */
    rgbw?: ApiSettingsSetPostRequestSettingsRgbw;
}

/**
 * Check if a given object implements the ApiSettingsSetPostRequestSettings interface.
 */
export function instanceOfApiSettingsSetPostRequestSettings(value: object): value is ApiSettingsSetPostRequestSettings {
    return true;
}

export function ApiSettingsSetPostRequestSettingsFromJSON(json: any): ApiSettingsSetPostRequestSettings {
    return ApiSettingsSetPostRequestSettingsFromJSONTyped(json, false);
}

export function ApiSettingsSetPostRequestSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsSetPostRequestSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceName': json['deviceName'] == null ? undefined : DeviceNameFromJSON(json['deviceName']),
        'tunnel': json['tunnel'] == null ? undefined : TunnelFromJSON(json['tunnel']),
        'statusLed': json['statusLed'] == null ? undefined : StatusLedFromJSON(json['statusLed']),
        'rgbw': json['rgbw'] == null ? undefined : ApiSettingsSetPostRequestSettingsRgbwFromJSON(json['rgbw']),
    };
}

export function ApiSettingsSetPostRequestSettingsToJSON(json: any): ApiSettingsSetPostRequestSettings {
    return ApiSettingsSetPostRequestSettingsToJSONTyped(json, false);
}

export function ApiSettingsSetPostRequestSettingsToJSONTyped(value?: ApiSettingsSetPostRequestSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceName': DeviceNameToJSON(value['deviceName']),
        'tunnel': TunnelToJSON(value['tunnel']),
        'statusLed': StatusLedToJSON(value['statusLed']),
        'rgbw': ApiSettingsSetPostRequestSettingsRgbwToJSON(value['rgbw']),
    };
}

