// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiWifiStatusGet200Response
 */
export interface ApiWifiStatusGet200Response {
    /**
     * <br>Parameter that show if **WiFi scanning is in progress**, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**false**</td> <td>disabled</td> </tr> <tr> <td>**true**</td> <td>enabled</td> </tr> </table>
     * @type {boolean}
     * @memberof ApiWifiStatusGet200Response
     */
    scanning?: boolean;
    /**
     * SSID of connected WiFi network. <br> **Empty string** indicates that **no WiFi network was selected**
     * @type {string}
     * @memberof ApiWifiStatusGet200Response
     */
    ssid?: string;
    /**
     * IPv4 of BleBox device connected to local WiFi network. <br> **Empty string** indicates that **no WiFi network was connected**
     * @type {string}
     * @memberof ApiWifiStatusGet200Response
     */
    ip?: string;
    /**
     * <br>Status of current **WiFi connection**, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>Not configured</td> </tr> <tr> <td>**1**</td> <td>Connecting</td> </tr> <tr> <td>**2**</td> <td>Wrong password</td> </tr> <tr> <td>**3**</td> <td>WiFi network not found</td> </tr> <tr> <td>**4**</td> <td>Communication with WiFi network failed</td> </tr> <tr> <td>**5**</td> <td>Connected</td> </tr> </table>
     * @type {ApiWifiStatusGet200ResponseStationStatusEnum}
     * @memberof ApiWifiStatusGet200Response
     */
    stationStatus?: ApiWifiStatusGet200ResponseStationStatusEnum;
}


/**
 * @export
 */
export const ApiWifiStatusGet200ResponseStationStatusEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type ApiWifiStatusGet200ResponseStationStatusEnum = typeof ApiWifiStatusGet200ResponseStationStatusEnum[keyof typeof ApiWifiStatusGet200ResponseStationStatusEnum];


/**
 * Check if a given object implements the ApiWifiStatusGet200Response interface.
 */
export function instanceOfApiWifiStatusGet200Response(value: object): value is ApiWifiStatusGet200Response {
    return true;
}

export function ApiWifiStatusGet200ResponseFromJSON(json: any): ApiWifiStatusGet200Response {
    return ApiWifiStatusGet200ResponseFromJSONTyped(json, false);
}

export function ApiWifiStatusGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWifiStatusGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'scanning': json['scanning'] == null ? undefined : json['scanning'],
        'ssid': json['ssid'] == null ? undefined : json['ssid'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'stationStatus': json['station_status'] == null ? undefined : json['station_status'],
    };
}

export function ApiWifiStatusGet200ResponseToJSON(json: any): ApiWifiStatusGet200Response {
    return ApiWifiStatusGet200ResponseToJSONTyped(json, false);
}

export function ApiWifiStatusGet200ResponseToJSONTyped(value?: ApiWifiStatusGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scanning': value['scanning'],
        'ssid': value['ssid'],
        'ip': value['ip'],
        'station_status': value['stationStatus'],
    };
}

