// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * **Type of controlled appliance** (type and quantity of LED strips), where: <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**1**</td> <td>**RGBW**</td> </tr> <tr> <td>**2**</td> <td>**RGB**</td> </tr> <tr> <td>**3**</td> <td>**MONO** - 4 separated channel (LED strips)</td> </tr> <tr> <td>**4**</td> <td>**RGB or W**<br> * RGBW but with exceptive parts: color (RGB) and white (W), where <br> white (W) part has priority*</td> </tr> <tr> <td>**5**</td> <td>**CT** (color temperature)  <br> *For one 2-channel LED strips <br> (warm white - 1:(R); cold white - 1:(G))*</td> </tr> <tr> <td>**6**</td> <td>**CTx2** - 2 separated LED strips (color temperature) <br> *For two separated 2-channel LED strips <br> (warm white - 1:(R),2:(B); cold white - 1:(G),2:(W))*</td> </tr> </table> <br><br> *Warring: This settings is available only in 4-channels controllers. Allowed colorMode depends on hardware/firmware version (field preferences)*
 * @export
 */
export const ColorMode = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type ColorMode = typeof ColorMode[keyof typeof ColorMode];


export function instanceOfColorMode(value: any): boolean {
    for (const key in ColorMode) {
        if (Object.prototype.hasOwnProperty.call(ColorMode, key)) {
            if (ColorMode[key as keyof typeof ColorMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ColorModeFromJSON(json: any): ColorMode {
    return ColorModeFromJSONTyped(json, false);
}

export function ColorModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorMode {
    return json as ColorMode;
}

export function ColorModeToJSON(value?: ColorMode | null): any {
    return value as any;
}

export function ColorModeToJSONTyped(value: any, ignoreDiscriminator: boolean): ColorMode {
    return value as ColorMode;
}

