// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColorFade } from './ColorFade';
import {
    ColorFadeFromJSON,
    ColorFadeFromJSONTyped,
    ColorFadeToJSON,
    ColorFadeToJSONTyped,
} from './ColorFade';
import type { EffectStep } from './EffectStep';
import {
    EffectStepFromJSON,
    EffectStepFromJSONTyped,
    EffectStepToJSON,
    EffectStepToJSONTyped,
} from './EffectStep';
import type { EffectFade } from './EffectFade';
import {
    EffectFadeFromJSON,
    EffectFadeFromJSONTyped,
    EffectFadeToJSON,
    EffectFadeToJSONTyped,
} from './EffectFade';

/**
 * Object which contain parameters connected with **transitions of color and effects**
 * @export
 * @interface DurationsMs
 */
export interface DurationsMs {
    /**
     * 
     * @type {ColorFade}
     * @memberof DurationsMs
     */
    colorFade?: ColorFade;
    /**
     * 
     * @type {EffectFade}
     * @memberof DurationsMs
     */
    effectFade?: EffectFade;
    /**
     * 
     * @type {EffectStep}
     * @memberof DurationsMs
     */
    effectStep?: EffectStep;
}



/**
 * Check if a given object implements the DurationsMs interface.
 */
export function instanceOfDurationsMs(value: object): value is DurationsMs {
    return true;
}

export function DurationsMsFromJSON(json: any): DurationsMs {
    return DurationsMsFromJSONTyped(json, false);
}

export function DurationsMsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DurationsMs {
    if (json == null) {
        return json;
    }
    return {
        
        'colorFade': json['colorFade'] == null ? undefined : ColorFadeFromJSON(json['colorFade']),
        'effectFade': json['effectFade'] == null ? undefined : EffectFadeFromJSON(json['effectFade']),
        'effectStep': json['effectStep'] == null ? undefined : EffectStepFromJSON(json['effectStep']),
    };
}

export function DurationsMsToJSON(json: any): DurationsMs {
    return DurationsMsToJSONTyped(json, false);
}

export function DurationsMsToJSONTyped(value?: DurationsMs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'colorFade': ColorFadeToJSON(value['colorFade']),
        'effectFade': EffectFadeToJSON(value['effectFade']),
        'effectStep': EffectStepToJSON(value['effectStep']),
    };
}

