// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * **Type of output signal** (depend on controlled LED strip/module), where: <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**1**</td> <td>**linearizedPWM**</td> </tr> <tr> <td>**2**</td> <td>**linearizedAndInvertedPWM**</td> </tr> <tr> <td>**3**</td> <td>**linePWM**</td> </tr> <tr> <td>**4**</td> <td>**linearizedCcPWM**</td> </tr> </table> <br><br> *Warring: This settings is available only in 1-channels controllers. Allowed outputMode depends from hardware/firmware version (field preferences)*
 * @export
 */
export const OutputMode = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type OutputMode = typeof OutputMode[keyof typeof OutputMode];


export function instanceOfOutputMode(value: any): boolean {
    for (const key in OutputMode) {
        if (Object.prototype.hasOwnProperty.call(OutputMode, key)) {
            if (OutputMode[key as keyof typeof OutputMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OutputModeFromJSON(json: any): OutputMode {
    return OutputModeFromJSONTyped(json, false);
}

export function OutputModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputMode {
    return json as OutputMode;
}

export function OutputModeToJSON(value?: OutputMode | null): any {
    return value as any;
}

export function OutputModeToJSONTyped(value: any, ignoreDiscriminator: boolean): OutputMode {
    return value as OutputMode;
}

