// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Encryption } from './Encryption';
import {
    EncryptionFromJSON,
    EncryptionFromJSONTyped,
    EncryptionToJSON,
    EncryptionToJSONTyped,
} from './Encryption';

/**
 * 
 * @export
 * @interface ApFound
 */
export interface ApFound {
    /**
     * SSID (name) of found network
     * @type {string}
     * @memberof ApFound
     */
    ssid?: string;
    /**
     * <br>**Signal strength** of found network, where:<br> <table> <tr> <td>From:</td> <td>To:</td> <td>Description:</td> </tr> <tr> <td>**-67**</td> <td>**0**</td> <td>Very good</td> </tr> <tr> <td>**-73**</td> <td>**-68**</td> <td>Good</td> </tr> <tr> <td>**-80**</td> <td>**-74**</td> <td>Poor</td> </tr> <tr> <td>**-127**</td> <td>**-81**</td> <td>Unstable/Unusable</td> </tr> </table>
     * @type {number}
     * @memberof ApFound
     */
    rssi?: number;
    /**
     * 
     * @type {Encryption}
     * @memberof ApFound
     */
    enc?: Encryption;
}



/**
 * Check if a given object implements the ApFound interface.
 */
export function instanceOfApFound(value: object): value is ApFound {
    return true;
}

export function ApFoundFromJSON(json: any): ApFound {
    return ApFoundFromJSONTyped(json, false);
}

export function ApFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApFound {
    if (json == null) {
        return json;
    }
    return {
        
        'ssid': json['ssid'] == null ? undefined : json['ssid'],
        'rssi': json['rssi'] == null ? undefined : json['rssi'],
        'enc': json['enc'] == null ? undefined : EncryptionFromJSON(json['enc']),
    };
}

export function ApFoundToJSON(json: any): ApFound {
    return ApFoundToJSONTyped(json, false);
}

export function ApFoundToJSONTyped(value?: ApFound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ssid': value['ssid'],
        'rssi': value['rssi'],
        'enc': EncryptionToJSON(value['enc']),
    };
}

