// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDeviceSetPostRequestNetwork } from './ApiDeviceSetPostRequestNetwork';
import {
    ApiDeviceSetPostRequestNetworkFromJSON,
    ApiDeviceSetPostRequestNetworkFromJSONTyped,
    ApiDeviceSetPostRequestNetworkToJSON,
    ApiDeviceSetPostRequestNetworkToJSONTyped,
} from './ApiDeviceSetPostRequestNetwork';

/**
 * 
 * @export
 * @interface ApiDeviceSetPostRequest
 */
export interface ApiDeviceSetPostRequest {
    /**
     * 
     * @type {ApiDeviceSetPostRequestNetwork}
     * @memberof ApiDeviceSetPostRequest
     */
    network: ApiDeviceSetPostRequestNetwork;
}

/**
 * Check if a given object implements the ApiDeviceSetPostRequest interface.
 */
export function instanceOfApiDeviceSetPostRequest(value: object): value is ApiDeviceSetPostRequest {
    if (!('network' in value) || value['network'] === undefined) return false;
    return true;
}

export function ApiDeviceSetPostRequestFromJSON(json: any): ApiDeviceSetPostRequest {
    return ApiDeviceSetPostRequestFromJSONTyped(json, false);
}

export function ApiDeviceSetPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDeviceSetPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'network': ApiDeviceSetPostRequestNetworkFromJSON(json['network']),
    };
}

export function ApiDeviceSetPostRequestToJSON(json: any): ApiDeviceSetPostRequest {
    return ApiDeviceSetPostRequestToJSONTyped(json, false);
}

export function ApiDeviceSetPostRequestToJSONTyped(value?: ApiDeviceSetPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': ApiDeviceSetPostRequestNetworkToJSON(value['network']),
    };
}

