// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Device } from './Device';
import {
    DeviceFromJSON,
    DeviceFromJSONTyped,
    DeviceToJSON,
    DeviceToJSONTyped,
} from './Device';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
    NetworkToJSONTyped,
} from './Network';

/**
 * 
 * @export
 * @interface ApiDeviceSetPost200Response
 */
export interface ApiDeviceSetPost200Response {
    /**
     * 
     * @type {Device}
     * @memberof ApiDeviceSetPost200Response
     */
    device?: Device;
    /**
     * 
     * @type {Network}
     * @memberof ApiDeviceSetPost200Response
     */
    network?: Network;
}

/**
 * Check if a given object implements the ApiDeviceSetPost200Response interface.
 */
export function instanceOfApiDeviceSetPost200Response(value: object): value is ApiDeviceSetPost200Response {
    return true;
}

export function ApiDeviceSetPost200ResponseFromJSON(json: any): ApiDeviceSetPost200Response {
    return ApiDeviceSetPost200ResponseFromJSONTyped(json, false);
}

export function ApiDeviceSetPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDeviceSetPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'device': json['device'] == null ? undefined : DeviceFromJSON(json['device']),
        'network': json['network'] == null ? undefined : NetworkFromJSON(json['network']),
    };
}

export function ApiDeviceSetPost200ResponseToJSON(json: any): ApiDeviceSetPost200Response {
    return ApiDeviceSetPost200ResponseToJSONTyped(json, false);
}

export function ApiDeviceSetPost200ResponseToJSONTyped(value?: ApiDeviceSetPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device': DeviceToJSON(value['device']),
        'network': NetworkToJSON(value['network']),
    };
}

