// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSettingsStateGet200ResponseSettingsButtonbox } from './ApiSettingsStateGet200ResponseSettingsButtonbox';
import {
    ApiSettingsStateGet200ResponseSettingsButtonboxFromJSON,
    ApiSettingsStateGet200ResponseSettingsButtonboxFromJSONTyped,
    ApiSettingsStateGet200ResponseSettingsButtonboxToJSON,
    ApiSettingsStateGet200ResponseSettingsButtonboxToJSONTyped,
} from './ApiSettingsStateGet200ResponseSettingsButtonbox';
import type { Tunnel } from './Tunnel';
import {
    TunnelFromJSON,
    TunnelFromJSONTyped,
    TunnelToJSON,
    TunnelToJSONTyped,
} from './Tunnel';
import type { StatusLed } from './StatusLed';
import {
    StatusLedFromJSON,
    StatusLedFromJSONTyped,
    StatusLedToJSON,
    StatusLedToJSONTyped,
} from './StatusLed';

/**
 * Object with **specific** settings
 * @export
 * @interface ApiSettingsStateGet200ResponseSettings
 */
export interface ApiSettingsStateGet200ResponseSettings {
    /**
     * **Name** of BleBox device/controller
     * @type {string}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    deviceName?: string;
    /**
     * 
     * @type {Tunnel}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    tunnel?: Tunnel;
    /**
     * 
     * @type {StatusLed}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    statusLed?: StatusLed;
    /**
     * 
     * @type {ApiSettingsStateGet200ResponseSettingsButtonbox}
     * @memberof ApiSettingsStateGet200ResponseSettings
     */
    buttonbox?: ApiSettingsStateGet200ResponseSettingsButtonbox;
}

/**
 * Check if a given object implements the ApiSettingsStateGet200ResponseSettings interface.
 */
export function instanceOfApiSettingsStateGet200ResponseSettings(value: object): value is ApiSettingsStateGet200ResponseSettings {
    return true;
}

export function ApiSettingsStateGet200ResponseSettingsFromJSON(json: any): ApiSettingsStateGet200ResponseSettings {
    return ApiSettingsStateGet200ResponseSettingsFromJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsStateGet200ResponseSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
        'tunnel': json['tunnel'] == null ? undefined : TunnelFromJSON(json['tunnel']),
        'statusLed': json['statusLed'] == null ? undefined : StatusLedFromJSON(json['statusLed']),
        'buttonbox': json['buttonbox'] == null ? undefined : ApiSettingsStateGet200ResponseSettingsButtonboxFromJSON(json['buttonbox']),
    };
}

export function ApiSettingsStateGet200ResponseSettingsToJSON(json: any): ApiSettingsStateGet200ResponseSettings {
    return ApiSettingsStateGet200ResponseSettingsToJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsToJSONTyped(value?: ApiSettingsStateGet200ResponseSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceName': value['deviceName'],
        'tunnel': TunnelToJSON(value['tunnel']),
        'statusLed': StatusLedToJSON(value['statusLed']),
        'buttonbox': ApiSettingsStateGet200ResponseSettingsButtonboxToJSON(value['buttonbox']),
    };
}

