// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UiType } from './UiType';
import {
    UiTypeFromJSON,
    UiTypeFromJSONTyped,
    UiTypeToJSON,
    UiTypeToJSONTyped,
} from './UiType';

/**
 * 
 * @export
 * @interface ApiSettingsStateGet200ResponseSettingsButtonbox
 */
export interface ApiSettingsStateGet200ResponseSettingsButtonbox {
    /**
     * 
     * @type {UiType}
     * @memberof ApiSettingsStateGet200ResponseSettingsButtonbox
     */
    uiType?: UiType;
}



/**
 * Check if a given object implements the ApiSettingsStateGet200ResponseSettingsButtonbox interface.
 */
export function instanceOfApiSettingsStateGet200ResponseSettingsButtonbox(value: object): value is ApiSettingsStateGet200ResponseSettingsButtonbox {
    return true;
}

export function ApiSettingsStateGet200ResponseSettingsButtonboxFromJSON(json: any): ApiSettingsStateGet200ResponseSettingsButtonbox {
    return ApiSettingsStateGet200ResponseSettingsButtonboxFromJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsButtonboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSettingsStateGet200ResponseSettingsButtonbox {
    if (json == null) {
        return json;
    }
    return {
        
        'uiType': json['uiType'] == null ? undefined : UiTypeFromJSON(json['uiType']),
    };
}

export function ApiSettingsStateGet200ResponseSettingsButtonboxToJSON(json: any): ApiSettingsStateGet200ResponseSettingsButtonbox {
    return ApiSettingsStateGet200ResponseSettingsButtonboxToJSONTyped(json, false);
}

export function ApiSettingsStateGet200ResponseSettingsButtonboxToJSONTyped(value?: ApiSettingsStateGet200ResponseSettingsButtonbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uiType': UiTypeToJSON(value['uiType']),
    };
}

