// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StationStatus } from './StationStatus';
import {
    StationStatusFromJSON,
    StationStatusFromJSONTyped,
    StationStatusToJSON,
    StationStatusToJSONTyped,
} from './StationStatus';

/**
 * 
 * @export
 * @interface ApiWifiStatusGet200Response
 */
export interface ApiWifiStatusGet200Response {
    /**
     * <br>Parameter that show if **WiFi scanning is in progress**, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**false**</td> <td>disabled</td> </tr> <tr> <td>**true**</td> <td>enabled</td> </tr> </table>
     * @type {boolean}
     * @memberof ApiWifiStatusGet200Response
     */
    scanning?: boolean;
    /**
     * SSID of connected WiFi network. <br> **Empty string** indicates that **no WiFi network was selected**
     * @type {string}
     * @memberof ApiWifiStatusGet200Response
     */
    ssid?: string;
    /**
     * IPv4 of BleBox device connected to local WiFi network. <br> **Empty string** indicates that **no WiFi network was connected**
     * @type {string}
     * @memberof ApiWifiStatusGet200Response
     */
    ip?: string;
    /**
     * 
     * @type {StationStatus}
     * @memberof ApiWifiStatusGet200Response
     */
    stationStatus?: StationStatus;
}



/**
 * Check if a given object implements the ApiWifiStatusGet200Response interface.
 */
export function instanceOfApiWifiStatusGet200Response(value: object): value is ApiWifiStatusGet200Response {
    return true;
}

export function ApiWifiStatusGet200ResponseFromJSON(json: any): ApiWifiStatusGet200Response {
    return ApiWifiStatusGet200ResponseFromJSONTyped(json, false);
}

export function ApiWifiStatusGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWifiStatusGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'scanning': json['scanning'] == null ? undefined : json['scanning'],
        'ssid': json['ssid'] == null ? undefined : json['ssid'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'stationStatus': json['station_status'] == null ? undefined : StationStatusFromJSON(json['station_status']),
    };
}

export function ApiWifiStatusGet200ResponseToJSON(json: any): ApiWifiStatusGet200Response {
    return ApiWifiStatusGet200ResponseToJSONTyped(json, false);
}

export function ApiWifiStatusGet200ResponseToJSONTyped(value?: ApiWifiStatusGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scanning': value['scanning'],
        'ssid': value['ssid'],
        'ip': value['ip'],
        'station_status': StationStatusToJSON(value['stationStatus']),
    };
}

