// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StationStatus } from './StationStatus';
import {
    StationStatusFromJSON,
    StationStatusFromJSONTyped,
    StationStatusToJSON,
    StationStatusToJSONTyped,
} from './StationStatus';

/**
 * 
 * @export
 * @interface ApiWifiConnectPost200Response
 */
export interface ApiWifiConnectPost200Response {
    /**
     * SSID of connected WiFi network. <br> **Empty string** indicates that **no WiFi network was selected**
     * @type {string}
     * @memberof ApiWifiConnectPost200Response
     */
    ssid?: string;
    /**
     * 
     * @type {StationStatus}
     * @memberof ApiWifiConnectPost200Response
     */
    stationStatus?: StationStatus;
}



/**
 * Check if a given object implements the ApiWifiConnectPost200Response interface.
 */
export function instanceOfApiWifiConnectPost200Response(value: object): value is ApiWifiConnectPost200Response {
    return true;
}

export function ApiWifiConnectPost200ResponseFromJSON(json: any): ApiWifiConnectPost200Response {
    return ApiWifiConnectPost200ResponseFromJSONTyped(json, false);
}

export function ApiWifiConnectPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWifiConnectPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ssid': json['ssid'] == null ? undefined : json['ssid'],
        'stationStatus': json['station_status'] == null ? undefined : StationStatusFromJSON(json['station_status']),
    };
}

export function ApiWifiConnectPost200ResponseToJSON(json: any): ApiWifiConnectPost200Response {
    return ApiWifiConnectPost200ResponseToJSONTyped(json, false);
}

export function ApiWifiConnectPost200ResponseToJSONTyped(value?: ApiWifiConnectPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ssid': value['ssid'],
        'station_status': StationStatusToJSON(value['stationStatus']),
    };
}

