// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiWifiConnectPostRequest
 */
export interface ApiWifiConnectPostRequest {
    /**
     * SSID of WiFi network. <br> **Empty string** will disconnect from WiFi network
     * @type {string}
     * @memberof ApiWifiConnectPostRequest
     */
    ssid: string;
    /**
     * Password to WiFi network. Empty string or 'null' indicates open mode (without password).
     * @type {string}
     * @memberof ApiWifiConnectPostRequest
     */
    pwd?: string | null;
}

/**
 * Check if a given object implements the ApiWifiConnectPostRequest interface.
 */
export function instanceOfApiWifiConnectPostRequest(value: object): value is ApiWifiConnectPostRequest {
    if (!('ssid' in value) || value['ssid'] === undefined) return false;
    return true;
}

export function ApiWifiConnectPostRequestFromJSON(json: any): ApiWifiConnectPostRequest {
    return ApiWifiConnectPostRequestFromJSONTyped(json, false);
}

export function ApiWifiConnectPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWifiConnectPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ssid': json['ssid'],
        'pwd': json['pwd'] == null ? undefined : json['pwd'],
    };
}

export function ApiWifiConnectPostRequestToJSON(json: any): ApiWifiConnectPostRequest {
    return ApiWifiConnectPostRequestToJSONTyped(json, false);
}

export function ApiWifiConnectPostRequestToJSONTyped(value?: ApiWifiConnectPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ssid': value['ssid'],
        'pwd': value['pwd'],
    };
}

