// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApFound } from './ApFound';
import {
    ApFoundFromJSON,
    ApFoundFromJSONTyped,
    ApFoundToJSON,
    ApFoundToJSONTyped,
} from './ApFound';

/**
 * 
 * @export
 * @interface ApiWifiScanGet200Response
 */
export interface ApiWifiScanGet200Response {
    /**
     * **List of** found **WiFi** networks
     * @type {Array<ApFound>}
     * @memberof ApiWifiScanGet200Response
     */
    ap?: Array<ApFound>;
}

/**
 * Check if a given object implements the ApiWifiScanGet200Response interface.
 */
export function instanceOfApiWifiScanGet200Response(value: object): value is ApiWifiScanGet200Response {
    return true;
}

export function ApiWifiScanGet200ResponseFromJSON(json: any): ApiWifiScanGet200Response {
    return ApiWifiScanGet200ResponseFromJSONTyped(json, false);
}

export function ApiWifiScanGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWifiScanGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ap': json['ap'] == null ? undefined : ((json['ap'] as Array<any>).map(ApFoundFromJSON)),
    };
}

export function ApiWifiScanGet200ResponseToJSON(json: any): ApiWifiScanGet200Response {
    return ApiWifiScanGet200ResponseToJSONTyped(json, false);
}

export function ApiWifiScanGet200ResponseToJSONTyped(value?: ApiWifiScanGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ap': value['ap'] == null ? undefined : ((value['ap'] as Array<any>).map(ApFoundToJSON)),
    };
}

