// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>Allow to **disable or enable function**, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>disabled</td> </tr> <tr> <td>**1**</td> <td>enabled</td> </tr> </table>
 * @export
 */
export const BoolFieldEnabled = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type BoolFieldEnabled = typeof BoolFieldEnabled[keyof typeof BoolFieldEnabled];


export function instanceOfBoolFieldEnabled(value: any): boolean {
    for (const key in BoolFieldEnabled) {
        if (Object.prototype.hasOwnProperty.call(BoolFieldEnabled, key)) {
            if (BoolFieldEnabled[key as keyof typeof BoolFieldEnabled] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BoolFieldEnabledFromJSON(json: any): BoolFieldEnabled {
    return BoolFieldEnabledFromJSONTyped(json, false);
}

export function BoolFieldEnabledFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoolFieldEnabled {
    return json as BoolFieldEnabled;
}

export function BoolFieldEnabledToJSON(value?: BoolFieldEnabled | null): any {
    return value as any;
}

export function BoolFieldEnabledToJSONTyped(value: any, ignoreDiscriminator: boolean): BoolFieldEnabled {
    return value as BoolFieldEnabled;
}

