// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>**Encryption mode** of found network, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>Open network (without password) - unsafe, but can be used</td> </tr> <tr> <td>**1**</td> <td>WEP encryption - unsafe - can not be used</td> </tr> <tr> <td>**2**</td> <td>WPA encryption - unsafe - can not be used</td> </tr> <tr> <td>**3**</td> <td>WPA2 encryption - safe if properly configured - can be used (recomended)</td> </tr> <tr> <td>**4**</td> <td>WPA/WPA2 encryption - unsafe, but can be used as WPA2</td> </tr> </table>
 * @export
 */
export const Encryption = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type Encryption = typeof Encryption[keyof typeof Encryption];


export function instanceOfEncryption(value: any): boolean {
    for (const key in Encryption) {
        if (Object.prototype.hasOwnProperty.call(Encryption, key)) {
            if (Encryption[key as keyof typeof Encryption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EncryptionFromJSON(json: any): Encryption {
    return EncryptionFromJSONTyped(json, false);
}

export function EncryptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Encryption {
    return json as Encryption;
}

export function EncryptionToJSON(value?: Encryption | null): any {
    return value as any;
}

export function EncryptionToJSONTyped(value: any, ignoreDiscriminator: boolean): Encryption {
    return value as Encryption;
}

