// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <br>Parameter that show **state of input**, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>Low</td> </tr> <tr> <td>**1**</td> <td>High</td> </tr> </table>
 * @export
 */
export const InputState = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type InputState = typeof InputState[keyof typeof InputState];


export function instanceOfInputState(value: any): boolean {
    for (const key in InputState) {
        if (Object.prototype.hasOwnProperty.call(InputState, key)) {
            if (InputState[key as keyof typeof InputState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InputStateFromJSON(json: any): InputState {
    return InputStateFromJSONTyped(json, false);
}

export function InputStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputState {
    return json as InputState;
}

export function InputStateToJSON(value?: InputState | null): any {
    return value as any;
}

export function InputStateToJSONTyped(value: any, ignoreDiscriminator: boolean): InputState {
    return value as InputState;
}

