// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InputState } from './InputState';
import {
    InputStateFromJSON,
    InputStateFromJSONTyped,
    InputStateToJSON,
    InputStateToJSONTyped,
} from './InputState';

/**
 * Description of selected input.
 * @export
 * @interface InputStruct
 */
export interface InputStruct {
    /**
     * Input ID. Numbered from 0. Maximum ID depending on the number of inputs available in the device (the available IDs are given in **inputs** array in the response of **Device state - /state**).
     * @type {number}
     * @memberof InputStruct
     */
    input: number;
    /**
     * 
     * @type {InputState}
     * @memberof InputStruct
     */
    state: InputState;
}



/**
 * Check if a given object implements the InputStruct interface.
 */
export function instanceOfInputStruct(value: object): value is InputStruct {
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function InputStructFromJSON(json: any): InputStruct {
    return InputStructFromJSONTyped(json, false);
}

export function InputStructFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputStruct {
    if (json == null) {
        return json;
    }
    return {
        
        'input': json['input'],
        'state': InputStateFromJSON(json['state']),
    };
}

export function InputStructToJSON(json: any): InputStruct {
    return InputStructToJSONTyped(json, false);
}

export function InputStructToJSONTyped(value?: InputStruct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input': value['input'],
        'state': InputStateToJSON(value['state']),
    };
}

