// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BoolFieldEnabled } from './BoolFieldEnabled';
import {
    BoolFieldEnabledFromJSON,
    BoolFieldEnabledFromJSONTyped,
    BoolFieldEnabledToJSON,
    BoolFieldEnabledToJSONTyped,
} from './BoolFieldEnabled';

/**
 * Allows to **enable** or **disable** extended status notification using built in **LED**
 * @export
 * @interface StatusLed
 */
export interface StatusLed {
    /**
     * 
     * @type {BoolFieldEnabled}
     * @memberof StatusLed
     */
    enabled?: BoolFieldEnabled;
}



/**
 * Check if a given object implements the StatusLed interface.
 */
export function instanceOfStatusLed(value: object): value is StatusLed {
    return true;
}

export function StatusLedFromJSON(json: any): StatusLed {
    return StatusLedFromJSONTyped(json, false);
}

export function StatusLedFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusLed {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : BoolFieldEnabledFromJSON(json['enabled']),
    };
}

export function StatusLedToJSON(json: any): StatusLed {
    return StatusLedToJSONTyped(json, false);
}

export function StatusLedToJSONTyped(value?: StatusLed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': BoolFieldEnabledToJSON(value['enabled']),
    };
}

