// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InputStruct } from './InputStruct';
import {
    InputStructFromJSON,
    InputStructFromJSONTyped,
    InputStructToJSON,
    InputStructToJSONTyped,
} from './InputStruct';
import type { StateExtendedGet200ResponseButtonbox } from './StateExtendedGet200ResponseButtonbox';
import {
    StateExtendedGet200ResponseButtonboxFromJSON,
    StateExtendedGet200ResponseButtonboxFromJSONTyped,
    StateExtendedGet200ResponseButtonboxToJSON,
    StateExtendedGet200ResponseButtonboxToJSONTyped,
} from './StateExtendedGet200ResponseButtonbox';

/**
 * 
 * @export
 * @interface StateExtendedGet200Response
 */
export interface StateExtendedGet200Response {
    /**
     * List of all available inputs with corresponding states.
     * @type {Array<InputStruct>}
     * @memberof StateExtendedGet200Response
     */
    inputs?: Array<InputStruct>;
    /**
     * 
     * @type {StateExtendedGet200ResponseButtonbox}
     * @memberof StateExtendedGet200Response
     */
    buttonbox?: StateExtendedGet200ResponseButtonbox;
}

/**
 * Check if a given object implements the StateExtendedGet200Response interface.
 */
export function instanceOfStateExtendedGet200Response(value: object): value is StateExtendedGet200Response {
    return true;
}

export function StateExtendedGet200ResponseFromJSON(json: any): StateExtendedGet200Response {
    return StateExtendedGet200ResponseFromJSONTyped(json, false);
}

export function StateExtendedGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateExtendedGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'inputs': json['inputs'] == null ? undefined : ((json['inputs'] as Array<any>).map(InputStructFromJSON)),
        'buttonbox': json['buttonbox'] == null ? undefined : StateExtendedGet200ResponseButtonboxFromJSON(json['buttonbox']),
    };
}

export function StateExtendedGet200ResponseToJSON(json: any): StateExtendedGet200Response {
    return StateExtendedGet200ResponseToJSONTyped(json, false);
}

export function StateExtendedGet200ResponseToJSONTyped(value?: StateExtendedGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inputs': value['inputs'] == null ? undefined : ((value['inputs'] as Array<any>).map(InputStructToJSON)),
        'buttonbox': StateExtendedGet200ResponseButtonboxToJSON(value['buttonbox']),
    };
}

