// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of selected trigger, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**1**</td> <td>Short click</td> </tr> <tr> <td>**2**</td> <td>Long click</td> </tr> <tr> <td>**3**</td> <td>Falling edge (transition from high to low state on the selected input)</td> </tr> <tr> <td>**4**</td> <td>Rising edge (transition from low to high state on the selected input)</td> </tr> <tr> <td>**5**</td> <td>Any edge (transition from "low to high state" or "high to low state" on the selected input)</td> </tr> </table>
 * @export
 */
export const TriggerType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type TriggerType = typeof TriggerType[keyof typeof TriggerType];


export function instanceOfTriggerType(value: any): boolean {
    for (const key in TriggerType) {
        if (Object.prototype.hasOwnProperty.call(TriggerType, key)) {
            if (TriggerType[key as keyof typeof TriggerType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TriggerTypeFromJSON(json: any): TriggerType {
    return TriggerTypeFromJSONTyped(json, false);
}

export function TriggerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerType {
    return json as TriggerType;
}

export function TriggerTypeToJSON(value?: TriggerType | null): any {
    return value as any;
}

export function TriggerTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): TriggerType {
    return value as TriggerType;
}

