// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BoolFieldEnabled } from './BoolFieldEnabled';
import {
    BoolFieldEnabledFromJSON,
    BoolFieldEnabledFromJSONTyped,
    BoolFieldEnabledToJSON,
    BoolFieldEnabledToJSONTyped,
} from './BoolFieldEnabled';

/**
 * Allows to **enable or disable** connection with **the BleBox's cloud** and decide whether events generated by this device should be log to **the BleBox's cloud** (necessary for push notifications), the user can view the event log through the wBox application.
 * @export
 * @interface Tunnel
 */
export interface Tunnel {
    /**
     * 
     * @type {BoolFieldEnabled}
     * @memberof Tunnel
     */
    enabled?: BoolFieldEnabled;
    /**
     * 
     * @type {BoolFieldEnabled}
     * @memberof Tunnel
     */
    logEnabled?: BoolFieldEnabled;
}



/**
 * Check if a given object implements the Tunnel interface.
 */
export function instanceOfTunnel(value: object): value is Tunnel {
    return true;
}

export function TunnelFromJSON(json: any): Tunnel {
    return TunnelFromJSONTyped(json, false);
}

export function TunnelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tunnel {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : BoolFieldEnabledFromJSON(json['enabled']),
        'logEnabled': json['logEnabled'] == null ? undefined : BoolFieldEnabledFromJSON(json['logEnabled']),
    };
}

export function TunnelToJSON(json: any): Tunnel {
    return TunnelToJSONTyped(json, false);
}

export function TunnelToJSONTyped(value?: Tunnel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': BoolFieldEnabledToJSON(value['enabled']),
        'logEnabled': BoolFieldEnabledToJSON(value['logEnabled']),
    };
}

