// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for Device Manager for BleBox.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDevicesProbePostRequest
 */
export interface ApiDevicesProbePostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiDevicesProbePostRequest
     */
    ip: string;
}

/**
 * Check if a given object implements the ApiDevicesProbePostRequest interface.
 */
export function instanceOfApiDevicesProbePostRequest(value: object): value is ApiDevicesProbePostRequest {
    if (!('ip' in value) || value['ip'] === undefined) return false;
    return true;
}

export function ApiDevicesProbePostRequestFromJSON(json: any): ApiDevicesProbePostRequest {
    return ApiDevicesProbePostRequestFromJSONTyped(json, false);
}

export function ApiDevicesProbePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDevicesProbePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ip': json['ip'],
    };
}

export function ApiDevicesProbePostRequestToJSON(json: any): ApiDevicesProbePostRequest {
    return ApiDevicesProbePostRequestToJSONTyped(json, false);
}

export function ApiDevicesProbePostRequestToJSONTyped(value?: ApiDevicesProbePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ip': value['ip'],
    };
}

