// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for the BleBox Device Manager.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDiscoveryStartPost202Response
 */
export interface ApiDiscoveryStartPost202Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiDiscoveryStartPost202Response
     */
    scanning: boolean;
}

/**
 * Check if a given object implements the ApiDiscoveryStartPost202Response interface.
 */
export function instanceOfApiDiscoveryStartPost202Response(value: object): value is ApiDiscoveryStartPost202Response {
    if (!('scanning' in value) || value['scanning'] === undefined) return false;
    return true;
}

export function ApiDiscoveryStartPost202ResponseFromJSON(json: any): ApiDiscoveryStartPost202Response {
    return ApiDiscoveryStartPost202ResponseFromJSONTyped(json, false);
}

export function ApiDiscoveryStartPost202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDiscoveryStartPost202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'scanning': json['scanning'],
    };
}

export function ApiDiscoveryStartPost202ResponseToJSON(json: any): ApiDiscoveryStartPost202Response {
    return ApiDiscoveryStartPost202ResponseToJSONTyped(json, false);
}

export function ApiDiscoveryStartPost202ResponseToJSONTyped(value?: ApiDiscoveryStartPost202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scanning': value['scanning'],
    };
}

