// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for Device Manager for BleBox.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDevicesProbePost400Response
 */
export interface ApiDevicesProbePost400Response {
    /**
     * 
     * @type {string}
     * @memberof ApiDevicesProbePost400Response
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDevicesProbePost400Response
     */
    message: string;
}

/**
 * Check if a given object implements the ApiDevicesProbePost400Response interface.
 */
export function instanceOfApiDevicesProbePost400Response(value: object): value is ApiDevicesProbePost400Response {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ApiDevicesProbePost400ResponseFromJSON(json: any): ApiDevicesProbePost400Response {
    return ApiDevicesProbePost400ResponseFromJSONTyped(json, false);
}

export function ApiDevicesProbePost400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDevicesProbePost400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function ApiDevicesProbePost400ResponseToJSON(json: any): ApiDevicesProbePost400Response {
    return ApiDevicesProbePost400ResponseToJSONTyped(json, false);
}

export function ApiDevicesProbePost400ResponseToJSONTyped(value?: ApiDevicesProbePost400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

