// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for the BleBox Device Manager.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice } from './ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice';
import {
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceFromJSON,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceFromJSONTyped,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceToJSON,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceToJSONTyped,
} from './ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice';

/**
 * 
 * @export
 * @interface ApiDevicesProbePost200Response
 */
export interface ApiDevicesProbePost200Response {
    /**
     * 
     * @type {ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice}
     * @memberof ApiDevicesProbePost200Response
     */
    device: ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice;
}

/**
 * Check if a given object implements the ApiDevicesProbePost200Response interface.
 */
export function instanceOfApiDevicesProbePost200Response(value: object): value is ApiDevicesProbePost200Response {
    if (!('device' in value) || value['device'] === undefined) return false;
    return true;
}

export function ApiDevicesProbePost200ResponseFromJSON(json: any): ApiDevicesProbePost200Response {
    return ApiDevicesProbePost200ResponseFromJSONTyped(json, false);
}

export function ApiDevicesProbePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDevicesProbePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'device': ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceFromJSON(json['device']),
    };
}

export function ApiDevicesProbePost200ResponseToJSON(json: any): ApiDevicesProbePost200Response {
    return ApiDevicesProbePost200ResponseToJSONTyped(json, false);
}

export function ApiDevicesProbePost200ResponseToJSONTyped(value?: ApiDevicesProbePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device': ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceToJSON(value['device']),
    };
}

