// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for the BleBox Device Manager.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel } from './ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel';
import {
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelFromJSON,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelFromJSONTyped,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelToJSON,
    ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelToJSONTyped,
} from './ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel';

/**
 * 
 * @export
 * @interface ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
 */
export interface ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice {
    /**
     * 
     * @type {string}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    deviceName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    product?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    hv?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    fv?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    universe?: number;
    /**
     * 
     * @type {ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    apiLevel?: ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevel;
    /**
     * 
     * @type {Array<number>}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    categories?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    ip?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice
     */
    availableFv?: string | null;
}

/**
 * Check if a given object implements the ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice interface.
 */
export function instanceOfApiDiscoveryDevicesGet200ResponseDevicesInnerDevice(value: object): value is ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice {
    if (!('deviceName' in value) || value['deviceName'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceFromJSON(json: any): ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice {
    return ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceFromJSONTyped(json, false);
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceName': json['deviceName'],
        'type': json['type'],
        'product': json['product'] == null ? undefined : json['product'],
        'hv': json['hv'] == null ? undefined : json['hv'],
        'fv': json['fv'] == null ? undefined : json['fv'],
        'universe': json['universe'] == null ? undefined : json['universe'],
        'apiLevel': json['apiLevel'] == null ? undefined : ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelFromJSON(json['apiLevel']),
        'categories': json['categories'] == null ? undefined : json['categories'],
        'id': json['id'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'availableFv': json['availableFv'] == null ? undefined : json['availableFv'],
    };
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceToJSON(json: any): ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice {
    return ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceToJSONTyped(json, false);
}

export function ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceToJSONTyped(value?: ApiDiscoveryDevicesGet200ResponseDevicesInnerDevice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceName': value['deviceName'],
        'type': value['type'],
        'product': value['product'],
        'hv': value['hv'],
        'fv': value['fv'],
        'universe': value['universe'],
        'apiLevel': ApiDiscoveryDevicesGet200ResponseDevicesInnerDeviceApiLevelToJSON(value['apiLevel']),
        'categories': value['categories'],
        'id': value['id'],
        'ip': value['ip'],
        'availableFv': value['availableFv'],
    };
}

