// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * BleBox Companion API
 * Discovery and CORS-proxy service for Device Manager for BleBox.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiHealthGet200Response
 */
export interface ApiHealthGet200Response {
    /**
     * 
     * @type {ApiHealthGet200ResponseStatusEnum}
     * @memberof ApiHealthGet200Response
     */
    status: ApiHealthGet200ResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ApiHealthGet200Response
     */
    uptimeS: number;
}


/**
 * @export
 */
export const ApiHealthGet200ResponseStatusEnum = {
    Ok: 'ok'
} as const;
export type ApiHealthGet200ResponseStatusEnum = typeof ApiHealthGet200ResponseStatusEnum[keyof typeof ApiHealthGet200ResponseStatusEnum];


/**
 * Check if a given object implements the ApiHealthGet200Response interface.
 */
export function instanceOfApiHealthGet200Response(value: object): value is ApiHealthGet200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('uptimeS' in value) || value['uptimeS'] === undefined) return false;
    return true;
}

export function ApiHealthGet200ResponseFromJSON(json: any): ApiHealthGet200Response {
    return ApiHealthGet200ResponseFromJSONTyped(json, false);
}

export function ApiHealthGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiHealthGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'uptimeS': json['uptimeS'],
    };
}

export function ApiHealthGet200ResponseToJSON(json: any): ApiHealthGet200Response {
    return ApiHealthGet200ResponseToJSONTyped(json, false);
}

export function ApiHealthGet200ResponseToJSONTyped(value?: ApiHealthGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'uptimeS': value['uptimeS'],
    };
}

