// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    StateGet200Response,
    TriggerType,
} from '../models/index';

export interface ControlWithGETApiTInputIdTriggerTypeGetRequest {
    inputId: number;
    triggerType: TriggerType;
}

/**
 * 
 */
export class ControlWithGETApi extends runtime.BaseAPI {

    /**
     * Creates request options for tInputIdTriggerTypeGet without sending the request
     */
    async tInputIdTriggerTypeGetRequestOpts(requestParameters: ControlWithGETApiTInputIdTriggerTypeGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['inputId'] == null) {
            throw new runtime.RequiredError(
                'inputId',
                'Required parameter "inputId" was null or undefined when calling tInputIdTriggerTypeGet().'
            );
        }

        if (requestParameters['triggerType'] == null) {
            throw new runtime.RequiredError(
                'triggerType',
                'Required parameter "triggerType" was null or undefined when calling tInputIdTriggerTypeGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/t/{inputId}/{triggerType}`;
        urlPath = urlPath.replace('{inputId}', encodeURIComponent(String(requestParameters['inputId'])));
        urlPath = urlPath.replace('{triggerType}', encodeURIComponent(String(requestParameters['triggerType'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Trigger the selected input in the chosen way to run the assigned actions (using *GET* request).
     * Trigger the selected input
     */
    async tInputIdTriggerTypeGetRaw(requestParameters: ControlWithGETApiTInputIdTriggerTypeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.tInputIdTriggerTypeGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Trigger the selected input in the chosen way to run the assigned actions (using *GET* request).
     * Trigger the selected input
     */
    async tInputIdTriggerTypeGet(requestParameters: ControlWithGETApiTInputIdTriggerTypeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.tInputIdTriggerTypeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
