// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: buttonBox
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *buttonBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    StateExtendedGet200Response,
    StateGet200Response,
} from '../models/index';

/**
 * 
 */
export class ControlStateApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiButtonboxExtendedStateGet without sending the request
     * @deprecated
     */
    async apiButtonboxExtendedStateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/buttonbox/extended/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **extended information** about **device and inputs**<br>  *(all parameters needed to display user interface)*<br> <br><br>**It is deprecated** -> look at:
     * Extended device specific state
     * @deprecated
     */
    async apiButtonboxExtendedStateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateExtendedGet200Response>> {
        const requestOptions = await this.apiButtonboxExtendedStateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **extended information** about **device and inputs**<br>  *(all parameters needed to display user interface)*<br> <br><br>**It is deprecated** -> look at:
     * Extended device specific state
     * @deprecated
     */
    async apiButtonboxExtendedStateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateExtendedGet200Response> {
        const response = await this.apiButtonboxExtendedStateGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiButtonboxStateGet without sending the request
     * @deprecated
     */
    async apiButtonboxStateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/buttonbox/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns information about **inputs state** <br><br>**It is deprecated** -> look at:
     * Device specific state
     * @deprecated
     */
    async apiButtonboxStateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.apiButtonboxStateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns information about **inputs state** <br><br>**It is deprecated** -> look at:
     * Device specific state
     * @deprecated
     */
    async apiButtonboxStateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.apiButtonboxStateGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stateExtendedGet without sending the request
     */
    async stateExtendedGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/state/extended`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns **extended information** about **device and inputs**<br>  *(all parameters needed to display user interface)*
     * Extended device specific state
     */
    async stateExtendedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateExtendedGet200Response>> {
        const requestOptions = await this.stateExtendedGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns **extended information** about **device and inputs**<br>  *(all parameters needed to display user interface)*
     * Extended device specific state
     */
    async stateExtendedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateExtendedGet200Response> {
        const response = await this.stateExtendedGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stateGet without sending the request
     */
    async stateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns information about **inputs state**
     * Device specific state
     */
    async stateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.stateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns information about **inputs state**
     * Device specific state
     */
    async stateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.stateGetRaw(initOverrides);
        return await response.value();
    }

}
