// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    ApiRgbwExtendedSetPostRequest,
    ApiRgbwExtendedStateGet200Response,
    ApiRgbwSetPostRequest,
    ApiRgbwStateGet200Response,
} from '../models/index';

export interface ControlStateApiApiRgbwExtendedSetPostOperationRequest {
    apiRgbwExtendedSetPostRequest?: ApiRgbwExtendedSetPostRequest;
}

export interface ControlStateApiApiRgbwSetPostOperationRequest {
    apiRgbwSetPostRequest?: ApiRgbwSetPostRequest;
}

/**
 * 
 */
export class ControlStateApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiRgbwExtendedSetPost without sending the request
     */
    async apiRgbwExtendedSetPostRequestOpts(requestParameters: ControlStateApiApiRgbwExtendedSetPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/rgbw/extended/set`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['apiRgbwExtendedSetPostRequest'],
        };
    }

    /**
     * Allows to **set state of lighting** - **effect, color, transition times**<br> Additionaly allows to set extended parameters - **favorite colors**<br>
     * Set extended parameters of lighting
     */
    async apiRgbwExtendedSetPostRaw(requestParameters: ControlStateApiApiRgbwExtendedSetPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwExtendedStateGet200Response>> {
        const requestOptions = await this.apiRgbwExtendedSetPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Allows to **set state of lighting** - **effect, color, transition times**<br> Additionaly allows to set extended parameters - **favorite colors**<br>
     * Set extended parameters of lighting
     */
    async apiRgbwExtendedSetPost(requestParameters: ControlStateApiApiRgbwExtendedSetPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwExtendedStateGet200Response> {
        const response = await this.apiRgbwExtendedSetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRgbwExtendedStateGet without sending the request
     */
    async apiRgbwExtendedStateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/rgbw/extended/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Returns** information about **mode, selected effect, color, transition times**.<br> Additionaly returns **favorite colors** and **effects names**<br> *(All parameters needed to display user interface)*
     * Extended parameters of lighting
     */
    async apiRgbwExtendedStateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwExtendedStateGet200Response>> {
        const requestOptions = await this.apiRgbwExtendedStateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Returns** information about **mode, selected effect, color, transition times**.<br> Additionaly returns **favorite colors** and **effects names**<br> *(All parameters needed to display user interface)*
     * Extended parameters of lighting
     */
    async apiRgbwExtendedStateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwExtendedStateGet200Response> {
        const response = await this.apiRgbwExtendedStateGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRgbwSetPost without sending the request
     */
    async apiRgbwSetPostRequestOpts(requestParameters: ControlStateApiApiRgbwSetPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/rgbw/set`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['apiRgbwSetPostRequest'],
        };
    }

    /**
     * Allows to **set desired color, effect and transition times**
     * Set state of lighting
     */
    async apiRgbwSetPostRaw(requestParameters: ControlStateApiApiRgbwSetPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.apiRgbwSetPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Allows to **set desired color, effect and transition times**
     * Set state of lighting
     */
    async apiRgbwSetPost(requestParameters: ControlStateApiApiRgbwSetPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.apiRgbwSetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiRgbwStateGet without sending the request
     */
    async apiRgbwStateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/rgbw/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Returns** information about **mode, selected effect, color and transition times**
     * State of lighting
     */
    async apiRgbwStateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRgbwStateGet200Response>> {
        const requestOptions = await this.apiRgbwStateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Returns** information about **mode, selected effect, color and transition times**
     * State of lighting
     */
    async apiRgbwStateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRgbwStateGet200Response> {
        const response = await this.apiRgbwStateGetRaw(initOverrides);
        return await response.value();
    }

}
