// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    Relay,
    StateGet200Response,
    StateSet,
} from '../models/index';

export interface ControlWithGETApiS1ForTimeTimeSNs0GetRequest {
    timeS: number;
}

export interface ControlWithGETApiSRelay1ForTimeTimeSNs0GetRequest {
    relay: Relay;
    timeS: number;
}

export interface ControlWithGETApiSRelayStateGetRequest {
    relay: Relay;
    state: StateSet;
}

export interface ControlWithGETApiSStateGetRequest {
    state: StateSet;
}

/**
 * 
 */
export class ControlWithGETApi extends runtime.BaseAPI {

    /**
     * Creates request options for s1ForTimeTimeSNs0Get without sending the request
     */
    async s1ForTimeTimeSNs0GetRequestOpts(requestParameters: ControlWithGETApiS1ForTimeTimeSNs0GetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timeS'] == null) {
            throw new runtime.RequiredError(
                'timeS',
                'Required parameter "timeS" was null or undefined when calling s1ForTimeTimeSNs0Get().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/1/forTime/{timeS}/ns/0`;
        urlPath = urlPath.replace('{timeS}', encodeURIComponent(String(requestParameters['timeS'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Set all relays state to ON for a given time in seconds** using GET request
     * Set all relays for a given time
     */
    async s1ForTimeTimeSNs0GetRaw(requestParameters: ControlWithGETApiS1ForTimeTimeSNs0GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.s1ForTimeTimeSNs0GetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Set all relays state to ON for a given time in seconds** using GET request
     * Set all relays for a given time
     */
    async s1ForTimeTimeSNs0Get(requestParameters: ControlWithGETApiS1ForTimeTimeSNs0GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.s1ForTimeTimeSNs0GetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sRelay1ForTimeTimeSNs0Get without sending the request
     */
    async sRelay1ForTimeTimeSNs0GetRequestOpts(requestParameters: ControlWithGETApiSRelay1ForTimeTimeSNs0GetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['relay'] == null) {
            throw new runtime.RequiredError(
                'relay',
                'Required parameter "relay" was null or undefined when calling sRelay1ForTimeTimeSNs0Get().'
            );
        }

        if (requestParameters['timeS'] == null) {
            throw new runtime.RequiredError(
                'timeS',
                'Required parameter "timeS" was null or undefined when calling sRelay1ForTimeTimeSNs0Get().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/{relay}/1/forTime/{timeS}/ns/0`;
        urlPath = urlPath.replace('{relay}', encodeURIComponent(String(requestParameters['relay'])));
        urlPath = urlPath.replace('{timeS}', encodeURIComponent(String(requestParameters['timeS'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Set relay state to ON for a given time in seconds** using GET request
     * Set relay for a given time
     */
    async sRelay1ForTimeTimeSNs0GetRaw(requestParameters: ControlWithGETApiSRelay1ForTimeTimeSNs0GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.sRelay1ForTimeTimeSNs0GetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Set relay state to ON for a given time in seconds** using GET request
     * Set relay for a given time
     */
    async sRelay1ForTimeTimeSNs0Get(requestParameters: ControlWithGETApiSRelay1ForTimeTimeSNs0GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.sRelay1ForTimeTimeSNs0GetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sRelayStateGet without sending the request
     */
    async sRelayStateGetRequestOpts(requestParameters: ControlWithGETApiSRelayStateGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['relay'] == null) {
            throw new runtime.RequiredError(
                'relay',
                'Required parameter "relay" was null or undefined when calling sRelayStateGet().'
            );
        }

        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling sRelayStateGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/{relay}/{state}`;
        urlPath = urlPath.replace('{relay}', encodeURIComponent(String(requestParameters['relay'])));
        urlPath = urlPath.replace('{state}', encodeURIComponent(String(requestParameters['state'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Set relay state** using *GET* request
     * Set relay
     */
    async sRelayStateGetRaw(requestParameters: ControlWithGETApiSRelayStateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.sRelayStateGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Set relay state** using *GET* request
     * Set relay
     */
    async sRelayStateGet(requestParameters: ControlWithGETApiSRelayStateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.sRelayStateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sStateGet without sending the request
     */
    async sStateGetRequestOpts(requestParameters: ControlWithGETApiSStateGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling sStateGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/s/{state}`;
        urlPath = urlPath.replace('{state}', encodeURIComponent(String(requestParameters['state'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Set all relays state** using *GET* request
     * Set all relays
     */
    async sStateGetRaw(requestParameters: ControlWithGETApiSStateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StateGet200Response>> {
        const requestOptions = await this.sStateGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Set all relays state** using *GET* request
     * Set all relays
     */
    async sStateGet(requestParameters: ControlWithGETApiSStateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StateGet200Response> {
        const response = await this.sStateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
