// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: switchBoxD
 * # Introduction                                                            It is **specific API** of BleBox devices with **API type:** *switchBoxD* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200831
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    ApiDeviceNetworkGet200Response,
    ApiDeviceSetPost200Response,
    ApiDeviceSetPostRequest,
    ApiWifiConnectPost200Response,
    ApiWifiConnectPostRequest,
    ApiWifiScanGet200Response,
    ApiWifiStatusGet200Response,
} from '../models/index';

export interface NetworkApiApiDeviceSetPostOperationRequest {
    apiDeviceSetPostRequest?: ApiDeviceSetPostRequest;
}

export interface NetworkApiApiWifiConnectPostOperationRequest {
    apiWifiConnectPostRequest?: ApiWifiConnectPostRequest;
}

/**
 * 
 */
export class NetworkApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiDeviceNetworkGet without sending the request
     */
    async apiDeviceNetworkGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/device/network`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns information about **internal WiFi AP** or about connected **local WiFi network**
     * Network information
     */
    async apiDeviceNetworkGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDeviceNetworkGet200Response>> {
        const requestOptions = await this.apiDeviceNetworkGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns information about **internal WiFi AP** or about connected **local WiFi network**
     * Network information
     */
    async apiDeviceNetworkGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDeviceNetworkGet200Response> {
        const response = await this.apiDeviceNetworkGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiDeviceSetPost without sending the request
     */
    async apiDeviceSetPostRequestOpts(requestParameters: NetworkApiApiDeviceSetPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/device/set`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['apiDeviceSetPostRequest'],
        };
    }

    /**
     * **Allows to set** interal access Point\'s **ssid and password**. Allows also to **turn off internal AP**.
     * Set internal access Point\'s settings
     */
    async apiDeviceSetPostRaw(requestParameters: NetworkApiApiDeviceSetPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDeviceSetPost200Response>> {
        const requestOptions = await this.apiDeviceSetPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Allows to set** interal access Point\'s **ssid and password**. Allows also to **turn off internal AP**.
     * Set internal access Point\'s settings
     */
    async apiDeviceSetPost(requestParameters: NetworkApiApiDeviceSetPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDeviceSetPost200Response> {
        const response = await this.apiDeviceSetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiWifiConnectPost without sending the request
     */
    async apiWifiConnectPostRequestOpts(requestParameters: NetworkApiApiWifiConnectPostOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/wifi/connect`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['apiWifiConnectPostRequest'],
        };
    }

    /**
     * Perform connect to local WiFi network
     * Perform WiFi connect
     */
    async apiWifiConnectPostRaw(requestParameters: NetworkApiApiWifiConnectPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiWifiConnectPost200Response>> {
        const requestOptions = await this.apiWifiConnectPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Perform connect to local WiFi network
     * Perform WiFi connect
     */
    async apiWifiConnectPost(requestParameters: NetworkApiApiWifiConnectPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiWifiConnectPost200Response> {
        const response = await this.apiWifiConnectPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiWifiDisconnectPost without sending the request
     */
    async apiWifiDisconnectPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/wifi/disconnect`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Perform disconnect** from current local **WiFi network**
     * Perform WiFi disconnect
     */
    async apiWifiDisconnectPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiWifiDisconnectPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * **Perform disconnect** from current local **WiFi network**
     * Perform WiFi disconnect
     */
    async apiWifiDisconnectPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiWifiDisconnectPostRaw(initOverrides);
    }

    /**
     * Creates request options for apiWifiScanGet without sending the request
     */
    async apiWifiScanGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/wifi/scan`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * **Perform WiFi scan** and **return list of found WiFi** networks. Return conflict if scanning is in progress
     * Perform WiFi scan and get results
     */
    async apiWifiScanGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiWifiScanGet200Response>> {
        const requestOptions = await this.apiWifiScanGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * **Perform WiFi scan** and **return list of found WiFi** networks. Return conflict if scanning is in progress
     * Perform WiFi scan and get results
     */
    async apiWifiScanGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiWifiScanGet200Response> {
        const response = await this.apiWifiScanGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiWifiStatusGet without sending the request
     * @deprecated
     */
    async apiWifiStatusGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/wifi/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns information about **connected local WiFi network** and **if scanning is in progress** <br><br>**It is deprecated** -> look at:
     * Local WiFi Status
     * @deprecated
     */
    async apiWifiStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiWifiStatusGet200Response>> {
        const requestOptions = await this.apiWifiStatusGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns information about **connected local WiFi network** and **if scanning is in progress** <br><br>**It is deprecated** -> look at:
     * Local WiFi Status
     * @deprecated
     */
    async apiWifiStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiWifiStatusGet200Response> {
        const response = await this.apiWifiStatusGetRaw(initOverrides);
        return await response.value();
    }

}
