// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * As the name of field says<br><br> **inc** or **dec** to increase or decrease brightness
 * @export
 */
export const Adjust = {
    Inc: 'inc',
    Dec: 'dec'
} as const;
export type Adjust = typeof Adjust[keyof typeof Adjust];


export function instanceOfAdjust(value: any): boolean {
    for (const key in Adjust) {
        if (Object.prototype.hasOwnProperty.call(Adjust, key)) {
            if (Adjust[key as keyof typeof Adjust] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AdjustFromJSON(json: any): Adjust {
    return AdjustFromJSONTyped(json, false);
}

export function AdjustFromJSONTyped(json: any, ignoreDiscriminator: boolean): Adjust {
    return json as Adjust;
}

export function AdjustToJSON(value?: Adjust | null): any {
    return value as any;
}

export function AdjustToJSONTyped(value: any, ignoreDiscriminator: boolean): Adjust {
    return value as Adjust;
}

