// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * **Internal** access Point's settings
 * @export
 * @interface ApiDeviceSetPostRequestNetwork
 */
export interface ApiDeviceSetPostRequestNetwork {
    /**
     * <br>Parameter that show if **internal** WiFi Access Point is enabled, where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**false**</td> <td>disabled</td> </tr> <tr> <td>**true**</td> <td>enabled</td> </tr> </table><br> If **false** - **apSSID** and **apPasswd** can be ignored.
     * @type {boolean}
     * @memberof ApiDeviceSetPostRequestNetwork
     */
    apEnable?: boolean;
    /**
     * SSID of **internal** WiFi access Point
     * @type {string}
     * @memberof ApiDeviceSetPostRequestNetwork
     */
    apSSID?: string;
    /**
     * Password of **internal** WiFi Access Point. <br> WPA2-PSK is used. <br>Empty string or 'null' indicates that internal AP is set to open mode (without password).
     * @type {string}
     * @memberof ApiDeviceSetPostRequestNetwork
     */
    apPasswd?: string | null;
}

/**
 * Check if a given object implements the ApiDeviceSetPostRequestNetwork interface.
 */
export function instanceOfApiDeviceSetPostRequestNetwork(value: object): value is ApiDeviceSetPostRequestNetwork {
    return true;
}

export function ApiDeviceSetPostRequestNetworkFromJSON(json: any): ApiDeviceSetPostRequestNetwork {
    return ApiDeviceSetPostRequestNetworkFromJSONTyped(json, false);
}

export function ApiDeviceSetPostRequestNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDeviceSetPostRequestNetwork {
    if (json == null) {
        return json;
    }
    return {
        
        'apEnable': json['apEnable'] == null ? undefined : json['apEnable'],
        'apSSID': json['apSSID'] == null ? undefined : json['apSSID'],
        'apPasswd': json['apPasswd'] == null ? undefined : json['apPasswd'],
    };
}

export function ApiDeviceSetPostRequestNetworkToJSON(json: any): ApiDeviceSetPostRequestNetwork {
    return ApiDeviceSetPostRequestNetworkToJSONTyped(json, false);
}

export function ApiDeviceSetPostRequestNetworkToJSONTyped(value?: ApiDeviceSetPostRequestNetwork | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apEnable': value['apEnable'],
        'apSSID': value['apSSID'],
        'apPasswd': value['apPasswd'],
    };
}

