// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * All information connected with network
 * @export
 * @interface ApiDeviceNetworkGet200Response
 */
export interface ApiDeviceNetworkGet200Response {
    /**
     * 
     * @type {object}
     * @memberof ApiDeviceNetworkGet200Response
     */
    ssid?: object;
    /**
     * BSSID of connected WiFi network. <br> **Empty string** indicates that **no WiFi network was found**
     * @type {string}
     * @memberof ApiDeviceNetworkGet200Response
     */
    bssid?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiDeviceNetworkGet200Response
     */
    ip?: object;
    /**
     * MAC address of BleBox device. <br> This interface connect to Access Point (to local WiFi network)
     * @type {string}
     * @memberof ApiDeviceNetworkGet200Response
     */
    mac?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiDeviceNetworkGet200Response
     */
    stationStatus?: object;
    /**
     * <br>Status of **cloud connection** (remote access), where:<br> <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>Waiting for stable WiFi connection</td> </tr> <tr> <td>**1**</td> <td>Connecting</td> </tr> <tr> <td>**2**</td> <td>Internet network is unreachable (DNS failed)</td> </tr> <tr> <td>**3**</td> <td>Internet network is unreachable (server not found)</td> </tr> <tr> <td>**4**</td> <td>Connection broken (connection was estabilished but it's broken now)</td> </tr> <tr> <td>**5**</td> <td>Connected</td> </tr> <tr> <td>**6**</td> <td>Disabled by user</td> </tr> </table>
     * @type {ApiDeviceNetworkGet200ResponseTunnelStatusEnum}
     * @memberof ApiDeviceNetworkGet200Response
     */
    tunnelStatus?: ApiDeviceNetworkGet200ResponseTunnelStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof ApiDeviceNetworkGet200Response
     */
    apEnable?: object;
    /**
     * 
     * @type {object}
     * @memberof ApiDeviceNetworkGet200Response
     */
    apSSID?: object;
    /**
     * 
     * @type {object}
     * @memberof ApiDeviceNetworkGet200Response
     */
    apPasswd?: object;
    /**
     * Channel of **internal** WiFi Access Point. **If device is connected to local WiFi** network then internal WiFi **channel is the same** as local WiFi Access Point's channel
     * @type {number}
     * @memberof ApiDeviceNetworkGet200Response
     */
    channel?: number;
}


/**
 * @export
 */
export const ApiDeviceNetworkGet200ResponseTunnelStatusEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type ApiDeviceNetworkGet200ResponseTunnelStatusEnum = typeof ApiDeviceNetworkGet200ResponseTunnelStatusEnum[keyof typeof ApiDeviceNetworkGet200ResponseTunnelStatusEnum];


/**
 * Check if a given object implements the ApiDeviceNetworkGet200Response interface.
 */
export function instanceOfApiDeviceNetworkGet200Response(value: object): value is ApiDeviceNetworkGet200Response {
    return true;
}

export function ApiDeviceNetworkGet200ResponseFromJSON(json: any): ApiDeviceNetworkGet200Response {
    return ApiDeviceNetworkGet200ResponseFromJSONTyped(json, false);
}

export function ApiDeviceNetworkGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDeviceNetworkGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ssid': json['ssid'] == null ? undefined : json['ssid'],
        'bssid': json['bssid'] == null ? undefined : json['bssid'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'mac': json['mac'] == null ? undefined : json['mac'],
        'stationStatus': json['station_status'] == null ? undefined : json['station_status'],
        'tunnelStatus': json['tunnel_status'] == null ? undefined : json['tunnel_status'],
        'apEnable': json['apEnable'] == null ? undefined : json['apEnable'],
        'apSSID': json['apSSID'] == null ? undefined : json['apSSID'],
        'apPasswd': json['apPasswd'] == null ? undefined : json['apPasswd'],
        'channel': json['channel'] == null ? undefined : json['channel'],
    };
}

export function ApiDeviceNetworkGet200ResponseToJSON(json: any): ApiDeviceNetworkGet200Response {
    return ApiDeviceNetworkGet200ResponseToJSONTyped(json, false);
}

export function ApiDeviceNetworkGet200ResponseToJSONTyped(value?: ApiDeviceNetworkGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ssid': value['ssid'],
        'bssid': value['bssid'],
        'ip': value['ip'],
        'mac': value['mac'],
        'station_status': value['stationStatus'],
        'tunnel_status': value['tunnelStatus'],
        'apEnable': value['apEnable'],
        'apSSID': value['apSSID'],
        'apPasswd': value['apPasswd'],
        'channel': value['channel'],
    };
}

