// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRgbwExtendedStateGet200ResponseRgbw } from './ApiRgbwExtendedStateGet200ResponseRgbw';
import {
    ApiRgbwExtendedStateGet200ResponseRgbwFromJSON,
    ApiRgbwExtendedStateGet200ResponseRgbwFromJSONTyped,
    ApiRgbwExtendedStateGet200ResponseRgbwToJSON,
    ApiRgbwExtendedStateGet200ResponseRgbwToJSONTyped,
} from './ApiRgbwExtendedStateGet200ResponseRgbw';

/**
 * 
 * @export
 * @interface ApiRgbwExtendedStateGet200Response
 */
export interface ApiRgbwExtendedStateGet200Response {
    /**
     * 
     * @type {ApiRgbwExtendedStateGet200ResponseRgbw}
     * @memberof ApiRgbwExtendedStateGet200Response
     */
    rgbw?: ApiRgbwExtendedStateGet200ResponseRgbw;
}

/**
 * Check if a given object implements the ApiRgbwExtendedStateGet200Response interface.
 */
export function instanceOfApiRgbwExtendedStateGet200Response(value: object): value is ApiRgbwExtendedStateGet200Response {
    return true;
}

export function ApiRgbwExtendedStateGet200ResponseFromJSON(json: any): ApiRgbwExtendedStateGet200Response {
    return ApiRgbwExtendedStateGet200ResponseFromJSONTyped(json, false);
}

export function ApiRgbwExtendedStateGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRgbwExtendedStateGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'rgbw': json['rgbw'] == null ? undefined : ApiRgbwExtendedStateGet200ResponseRgbwFromJSON(json['rgbw']),
    };
}

export function ApiRgbwExtendedStateGet200ResponseToJSON(json: any): ApiRgbwExtendedStateGet200Response {
    return ApiRgbwExtendedStateGet200ResponseToJSONTyped(json, false);
}

export function ApiRgbwExtendedStateGet200ResponseToJSONTyped(value?: ApiRgbwExtendedStateGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rgbw': ApiRgbwExtendedStateGet200ResponseRgbwToJSON(value['rgbw']),
    };
}

