// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FavColors } from './FavColors';
import {
    FavColorsFromJSON,
    FavColorsFromJSONTyped,
    FavColorsToJSON,
    FavColorsToJSONTyped,
} from './FavColors';
import type { DurationsMs } from './DurationsMs';
import {
    DurationsMsFromJSON,
    DurationsMsFromJSONTyped,
    DurationsMsToJSON,
    DurationsMsToJSONTyped,
} from './DurationsMs';

/**
 * An object which contain **extended parameters** related with **LED lighting**
 * @export
 * @interface ApiRgbwExtendedSetPostRequestRgbw
 */
export interface ApiRgbwExtendedSetPostRequestRgbw {
    /**
     * **No (ID) of Effect**, where <table> <tr> <td>Value:</td> <td>Decription:</td> <tr> <td>**0**</td> <td>**None Effect** - Disable current effect and restore previous state</td> </tr> <tr> <td>**>0**</td> <td>**Effect** - Turn on selected effect **(if exist)**</td> </tr> </table>
     * @type {number}
     * @memberof ApiRgbwExtendedSetPostRequestRgbw
     */
    effectID?: number;
    /**
     * **Color value in format: 4 channels (R)(G)(B)(W) or 1 channel (S)**, where <br> every channel can get value between: **00-FF** (HEX) *(DEC: 0-255)*<br><br> **Use "--"** instead hex value **to keep channel unchanged** - e.g. ff00--12.
     * @type {string}
     * @memberof ApiRgbwExtendedSetPostRequestRgbw
     */
    desiredColor?: string;
    /**
     * 
     * @type {DurationsMs}
     * @memberof ApiRgbwExtendedSetPostRequestRgbw
     */
    durationsMs?: DurationsMs;
    /**
     * 
     * @type {FavColors}
     * @memberof ApiRgbwExtendedSetPostRequestRgbw
     */
    favColors?: FavColors;
}

/**
 * Check if a given object implements the ApiRgbwExtendedSetPostRequestRgbw interface.
 */
export function instanceOfApiRgbwExtendedSetPostRequestRgbw(value: object): value is ApiRgbwExtendedSetPostRequestRgbw {
    return true;
}

export function ApiRgbwExtendedSetPostRequestRgbwFromJSON(json: any): ApiRgbwExtendedSetPostRequestRgbw {
    return ApiRgbwExtendedSetPostRequestRgbwFromJSONTyped(json, false);
}

export function ApiRgbwExtendedSetPostRequestRgbwFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRgbwExtendedSetPostRequestRgbw {
    if (json == null) {
        return json;
    }
    return {
        
        'effectID': json['effectID'] == null ? undefined : json['effectID'],
        'desiredColor': json['desiredColor'] == null ? undefined : json['desiredColor'],
        'durationsMs': json['durationsMs'] == null ? undefined : DurationsMsFromJSON(json['durationsMs']),
        'favColors': json['favColors'] == null ? undefined : FavColorsFromJSON(json['favColors']),
    };
}

export function ApiRgbwExtendedSetPostRequestRgbwToJSON(json: any): ApiRgbwExtendedSetPostRequestRgbw {
    return ApiRgbwExtendedSetPostRequestRgbwToJSONTyped(json, false);
}

export function ApiRgbwExtendedSetPostRequestRgbwToJSONTyped(value?: ApiRgbwExtendedSetPostRequestRgbw | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'effectID': value['effectID'],
        'desiredColor': value['desiredColor'],
        'durationsMs': DurationsMsToJSON(value['durationsMs']),
        'favColors': FavColorsToJSON(value['favColors']),
    };
}

