// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColorMode } from './ColorMode';
import {
    ColorModeFromJSON,
    ColorModeFromJSONTyped,
    ColorModeToJSON,
    ColorModeToJSONTyped,
} from './ColorMode';
import type { DurationsMs } from './DurationsMs';
import {
    DurationsMsFromJSON,
    DurationsMsFromJSONTyped,
    DurationsMsToJSON,
    DurationsMsToJSONTyped,
} from './DurationsMs';

/**
 * An object containing parameters related with **LED lighting**
 * @export
 * @interface ApiRgbwStateGet200ResponseRgbw
 */
export interface ApiRgbwStateGet200ResponseRgbw {
    /**
     * 
     * @type {ColorMode}
     * @memberof ApiRgbwStateGet200ResponseRgbw
     */
    colorMode?: ColorMode;
    /**
     * **No (ID) of Effect**, where <table> <tr> <td>Value:</td> <td>Decription:</td> <tr> <td>**0**</td> <td>**None Effect** - Disable current effect and restore previous state</td> </tr> <tr> <td>**>0**</td> <td>**Effect** - Turn on selected effect **(if exist)**</td> </tr> </table>
     * @type {number}
     * @memberof ApiRgbwStateGet200ResponseRgbw
     */
    effectID?: number;
    /**
     * As the name of field says<br><br> **Color value in format: 4 channels (R)(G)(B)(W) or 1 channel (S)**, where <br> every channel can get value between: **00-FF** (HEX) *(DEC: 0-255)*
     * @type {string}
     * @memberof ApiRgbwStateGet200ResponseRgbw
     */
    desiredColor?: string;
    /**
     * As the name of field says<br><br> **Color value in format: 4 channels (R)(G)(B)(W) or 1 channel (S)**, where <br> every channel can get value between: **00-FF** (HEX) *(DEC: 0-255)*
     * @type {string}
     * @memberof ApiRgbwStateGet200ResponseRgbw
     */
    currentColor?: string;
    /**
     * As the name of field says<br><br> **Color value in format: 4 channels (R)(G)(B)(W) or 1 channel (S)**, where <br> every channel can get value between: **00-FF** (HEX) *(DEC: 0-255)*
     * @type {string}
     * @memberof ApiRgbwStateGet200ResponseRgbw
     */
    lastOnColor?: string;
    /**
     * 
     * @type {DurationsMs}
     * @memberof ApiRgbwStateGet200ResponseRgbw
     */
    durationsMs?: DurationsMs;
}



/**
 * Check if a given object implements the ApiRgbwStateGet200ResponseRgbw interface.
 */
export function instanceOfApiRgbwStateGet200ResponseRgbw(value: object): value is ApiRgbwStateGet200ResponseRgbw {
    return true;
}

export function ApiRgbwStateGet200ResponseRgbwFromJSON(json: any): ApiRgbwStateGet200ResponseRgbw {
    return ApiRgbwStateGet200ResponseRgbwFromJSONTyped(json, false);
}

export function ApiRgbwStateGet200ResponseRgbwFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRgbwStateGet200ResponseRgbw {
    if (json == null) {
        return json;
    }
    return {
        
        'colorMode': json['colorMode'] == null ? undefined : ColorModeFromJSON(json['colorMode']),
        'effectID': json['effectID'] == null ? undefined : json['effectID'],
        'desiredColor': json['desiredColor'] == null ? undefined : json['desiredColor'],
        'currentColor': json['currentColor'] == null ? undefined : json['currentColor'],
        'lastOnColor': json['lastOnColor'] == null ? undefined : json['lastOnColor'],
        'durationsMs': json['durationsMs'] == null ? undefined : DurationsMsFromJSON(json['durationsMs']),
    };
}

export function ApiRgbwStateGet200ResponseRgbwToJSON(json: any): ApiRgbwStateGet200ResponseRgbw {
    return ApiRgbwStateGet200ResponseRgbwToJSONTyped(json, false);
}

export function ApiRgbwStateGet200ResponseRgbwToJSONTyped(value?: ApiRgbwStateGet200ResponseRgbw | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'colorMode': ColorModeToJSON(value['colorMode']),
        'effectID': value['effectID'],
        'desiredColor': value['desiredColor'],
        'currentColor': value['currentColor'],
        'lastOnColor': value['lastOnColor'],
        'durationsMs': DurationsMsToJSON(value['durationsMs']),
    };
}

