// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRgbwStateGet200ResponseRgbw } from './ApiRgbwStateGet200ResponseRgbw';
import {
    ApiRgbwStateGet200ResponseRgbwFromJSON,
    ApiRgbwStateGet200ResponseRgbwFromJSONTyped,
    ApiRgbwStateGet200ResponseRgbwToJSON,
    ApiRgbwStateGet200ResponseRgbwToJSONTyped,
} from './ApiRgbwStateGet200ResponseRgbw';

/**
 * 
 * @export
 * @interface ApiRgbwStateGet200Response
 */
export interface ApiRgbwStateGet200Response {
    /**
     * 
     * @type {ApiRgbwStateGet200ResponseRgbw}
     * @memberof ApiRgbwStateGet200Response
     */
    rgbw?: ApiRgbwStateGet200ResponseRgbw;
}

/**
 * Check if a given object implements the ApiRgbwStateGet200Response interface.
 */
export function instanceOfApiRgbwStateGet200Response(value: object): value is ApiRgbwStateGet200Response {
    return true;
}

export function ApiRgbwStateGet200ResponseFromJSON(json: any): ApiRgbwStateGet200Response {
    return ApiRgbwStateGet200ResponseFromJSONTyped(json, false);
}

export function ApiRgbwStateGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRgbwStateGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'rgbw': json['rgbw'] == null ? undefined : ApiRgbwStateGet200ResponseRgbwFromJSON(json['rgbw']),
    };
}

export function ApiRgbwStateGet200ResponseToJSON(json: any): ApiRgbwStateGet200Response {
    return ApiRgbwStateGet200ResponseToJSONTyped(json, false);
}

export function ApiRgbwStateGet200ResponseToJSONTyped(value?: ApiRgbwStateGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rgbw': ApiRgbwStateGet200ResponseRgbwToJSON(value['rgbw']),
    };
}

