// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FavColors } from './FavColors';
import {
    FavColorsFromJSON,
    FavColorsFromJSONTyped,
    FavColorsToJSON,
    FavColorsToJSONTyped,
} from './FavColors';
import type { EffectNames } from './EffectNames';
import {
    EffectNamesFromJSON,
    EffectNamesFromJSONTyped,
    EffectNamesToJSON,
    EffectNamesToJSONTyped,
} from './EffectNames';
import type { ColorMode } from './ColorMode';
import {
    ColorModeFromJSON,
    ColorModeFromJSONTyped,
    ColorModeToJSON,
    ColorModeToJSONTyped,
} from './ColorMode';
import type { DurationsMs } from './DurationsMs';
import {
    DurationsMsFromJSON,
    DurationsMsFromJSONTyped,
    DurationsMsToJSON,
    DurationsMsToJSONTyped,
} from './DurationsMs';

/**
 * An object containing **extended parameters** related with **LED lighting**
 * @export
 * @interface ApiRgbwExtendedStateGet200ResponseRgbw
 */
export interface ApiRgbwExtendedStateGet200ResponseRgbw {
    /**
     * 
     * @type {ColorMode}
     * @memberof ApiRgbwExtendedStateGet200ResponseRgbw
     */
    colorMode?: ColorMode;
    /**
     * **No (ID) of Effect**, where <table> <tr> <td>Value:</td> <td>Decription:</td> <tr> <td>**0**</td> <td>**None Effect** - Disable current effect and restore previous state</td> </tr> <tr> <td>**>0**</td> <td>**Effect** - Turn on selected effect **(if exist)**</td> </tr> </table>
     * @type {number}
     * @memberof ApiRgbwExtendedStateGet200ResponseRgbw
     */
    effectID?: number;
    /**
     * As the name of field says<br><br> **Color value in format: 4 channels (R)(G)(B)(W) or 1 channel (S)**, where <br> every channel can get value between: **00-FF** (HEX) *(DEC: 0-255)*
     * @type {string}
     * @memberof ApiRgbwExtendedStateGet200ResponseRgbw
     */
    desiredColor?: string;
    /**
     * As the name of field says<br><br> **Color value in format: 4 channels (R)(G)(B)(W) or 1 channel (S)**, where <br> every channel can get value between: **00-FF** (HEX) *(DEC: 0-255)*
     * @type {string}
     * @memberof ApiRgbwExtendedStateGet200ResponseRgbw
     */
    currentColor?: string;
    /**
     * As the name of field says<br><br> **Color value in format: 4 channels (R)(G)(B)(W) or 1 channel (S)**, where <br> every channel can get value between: **00-FF** (HEX) *(DEC: 0-255)*
     * @type {string}
     * @memberof ApiRgbwExtendedStateGet200ResponseRgbw
     */
    lastOnColor?: string;
    /**
     * 
     * @type {DurationsMs}
     * @memberof ApiRgbwExtendedStateGet200ResponseRgbw
     */
    durationsMs?: DurationsMs;
    /**
     * 
     * @type {EffectNames}
     * @memberof ApiRgbwExtendedStateGet200ResponseRgbw
     */
    effectNames?: EffectNames;
    /**
     * 
     * @type {FavColors}
     * @memberof ApiRgbwExtendedStateGet200ResponseRgbw
     */
    favColors?: FavColors;
}



/**
 * Check if a given object implements the ApiRgbwExtendedStateGet200ResponseRgbw interface.
 */
export function instanceOfApiRgbwExtendedStateGet200ResponseRgbw(value: object): value is ApiRgbwExtendedStateGet200ResponseRgbw {
    return true;
}

export function ApiRgbwExtendedStateGet200ResponseRgbwFromJSON(json: any): ApiRgbwExtendedStateGet200ResponseRgbw {
    return ApiRgbwExtendedStateGet200ResponseRgbwFromJSONTyped(json, false);
}

export function ApiRgbwExtendedStateGet200ResponseRgbwFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRgbwExtendedStateGet200ResponseRgbw {
    if (json == null) {
        return json;
    }
    return {
        
        'colorMode': json['colorMode'] == null ? undefined : ColorModeFromJSON(json['colorMode']),
        'effectID': json['effectID'] == null ? undefined : json['effectID'],
        'desiredColor': json['desiredColor'] == null ? undefined : json['desiredColor'],
        'currentColor': json['currentColor'] == null ? undefined : json['currentColor'],
        'lastOnColor': json['lastOnColor'] == null ? undefined : json['lastOnColor'],
        'durationsMs': json['durationsMs'] == null ? undefined : DurationsMsFromJSON(json['durationsMs']),
        'effectNames': json['effectNames'] == null ? undefined : EffectNamesFromJSON(json['effectNames']),
        'favColors': json['favColors'] == null ? undefined : FavColorsFromJSON(json['favColors']),
    };
}

export function ApiRgbwExtendedStateGet200ResponseRgbwToJSON(json: any): ApiRgbwExtendedStateGet200ResponseRgbw {
    return ApiRgbwExtendedStateGet200ResponseRgbwToJSONTyped(json, false);
}

export function ApiRgbwExtendedStateGet200ResponseRgbwToJSONTyped(value?: ApiRgbwExtendedStateGet200ResponseRgbw | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'colorMode': ColorModeToJSON(value['colorMode']),
        'effectID': value['effectID'],
        'desiredColor': value['desiredColor'],
        'currentColor': value['currentColor'],
        'lastOnColor': value['lastOnColor'],
        'durationsMs': DurationsMsToJSON(value['durationsMs']),
        'effectNames': EffectNamesToJSON(value['effectNames']),
        'favColors': FavColorsToJSON(value['favColors']),
    };
}

