// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiWifiScanGet200ResponseApInner } from './ApiWifiScanGet200ResponseApInner';
import {
    ApiWifiScanGet200ResponseApInnerFromJSON,
    ApiWifiScanGet200ResponseApInnerFromJSONTyped,
    ApiWifiScanGet200ResponseApInnerToJSON,
    ApiWifiScanGet200ResponseApInnerToJSONTyped,
} from './ApiWifiScanGet200ResponseApInner';

/**
 * 
 * @export
 * @interface ApiWifiScanGet200Response
 */
export interface ApiWifiScanGet200Response {
    /**
     * **List of** found **WiFi** networks
     * @type {Array<ApiWifiScanGet200ResponseApInner>}
     * @memberof ApiWifiScanGet200Response
     */
    ap?: Array<ApiWifiScanGet200ResponseApInner>;
}

/**
 * Check if a given object implements the ApiWifiScanGet200Response interface.
 */
export function instanceOfApiWifiScanGet200Response(value: object): value is ApiWifiScanGet200Response {
    return true;
}

export function ApiWifiScanGet200ResponseFromJSON(json: any): ApiWifiScanGet200Response {
    return ApiWifiScanGet200ResponseFromJSONTyped(json, false);
}

export function ApiWifiScanGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWifiScanGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ap': json['ap'] == null ? undefined : ((json['ap'] as Array<any>).map(ApiWifiScanGet200ResponseApInnerFromJSON)),
    };
}

export function ApiWifiScanGet200ResponseToJSON(json: any): ApiWifiScanGet200Response {
    return ApiWifiScanGet200ResponseToJSONTyped(json, false);
}

export function ApiWifiScanGet200ResponseToJSONTyped(value?: ApiWifiScanGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ap': value['ap'] == null ? undefined : ((value['ap'] as Array<any>).map(ApiWifiScanGet200ResponseApInnerToJSON)),
    };
}

