// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * **Behaviour of connected button**, where: <table> <tr> <td>Enum:</td> <td>Description:</td> </tr> <tr> <td>**0**</td> <td>**None**</td> </tr> <tr> <td>**1**</td> <td>**on - off (100%)**</td> </tr> <tr> <td>**2**</td> <td>**on - off (last brightness)**</td> </tr> <tr> <td>**3**</td> <td>**on - off (100%) with dimming**</td> </tr> <tr> <td>**4**</td> <td>**on - off (last brightness) with dimming**</td> </tr> </table> <br><br> *Warring: This settings is available only in controllers with button input. Allowed buttonMode depends from hardware/firmware version (field preferences)*
 * @export
 */
export const ButtonMode = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type ButtonMode = typeof ButtonMode[keyof typeof ButtonMode];


export function instanceOfButtonMode(value: any): boolean {
    for (const key in ButtonMode) {
        if (Object.prototype.hasOwnProperty.call(ButtonMode, key)) {
            if (ButtonMode[key as keyof typeof ButtonMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ButtonModeFromJSON(json: any): ButtonMode {
    return ButtonModeFromJSONTyped(json, false);
}

export function ButtonModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ButtonMode {
    return json as ButtonMode;
}

export function ButtonModeToJSON(value?: ButtonMode | null): any {
    return value as any;
}

export function ButtonModeToJSONTyped(value: any, ignoreDiscriminator: boolean): ButtonMode {
    return value as ButtonMode;
}

