// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * **Time of transition from current color to desired color** measured in **milliseconds** <br> (full scale: 0x00 -> 0xff)
 * @export
 */
export const ColorFade = {
    NUMBER_0: 0
} as const;
export type ColorFade = typeof ColorFade[keyof typeof ColorFade];


export function instanceOfColorFade(value: any): boolean {
    for (const key in ColorFade) {
        if (Object.prototype.hasOwnProperty.call(ColorFade, key)) {
            if (ColorFade[key as keyof typeof ColorFade] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ColorFadeFromJSON(json: any): ColorFade {
    return ColorFadeFromJSONTyped(json, false);
}

export function ColorFadeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorFade {
    return json as ColorFade;
}

export function ColorFadeToJSON(value?: ColorFade | null): any {
    return value as any;
}

export function ColorFadeToJSONTyped(value: any, ignoreDiscriminator: boolean): ColorFade {
    return value as ColorFade;
}

