// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * **Time of color transition in current effect** measured in milliseconds <br> (full scale: 0x00 -> 0xff, value will be overwritten at beginning of another effect to default value of selected effect)
 * @export
 */
export const EffectFade = {
    NUMBER_0: 0
} as const;
export type EffectFade = typeof EffectFade[keyof typeof EffectFade];


export function instanceOfEffectFade(value: any): boolean {
    for (const key in EffectFade) {
        if (Object.prototype.hasOwnProperty.call(EffectFade, key)) {
            if (EffectFade[key as keyof typeof EffectFade] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EffectFadeFromJSON(json: any): EffectFade {
    return EffectFadeFromJSONTyped(json, false);
}

export function EffectFadeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffectFade {
    return json as EffectFade;
}

export function EffectFadeToJSON(value?: EffectFade | null): any {
    return value as any;
}

export function EffectFadeToJSONTyped(value: any, ignoreDiscriminator: boolean): EffectFade {
    return value as EffectFade;
}

