// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * **Duration of step (color) in current effect** measured in milliseconds <br> (value will be overwritten at beginning of another effect to default value of selected effect)
 * @export
 */
export const EffectStep = {
    NUMBER_0: 0
} as const;
export type EffectStep = typeof EffectStep[keyof typeof EffectStep];


export function instanceOfEffectStep(value: any): boolean {
    for (const key in EffectStep) {
        if (Object.prototype.hasOwnProperty.call(EffectStep, key)) {
            if (EffectStep[key as keyof typeof EffectStep] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EffectStepFromJSON(json: any): EffectStep {
    return EffectStepFromJSONTyped(json, false);
}

export function EffectStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffectStep {
    return json as EffectStep;
}

export function EffectStepToJSON(value?: EffectStep | null): any {
    return value as any;
}

export function EffectStepToJSONTyped(value: any, ignoreDiscriminator: boolean): EffectStep {
    return value as EffectStep;
}

