// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * **Dictionary of effects** saved on device <br> *(Parameters needed to display effects in user interface)*
 * @export
 * @interface EffectNames
 */
export interface EffectNames {
    /**
     * Key, effect ID, 0 as none
     * @type {number}
     * @memberof EffectNames
     */
    id: number;
    /**
     * Name of effect
     * @type {string}
     * @memberof EffectNames
     */
    value: string;
}

/**
 * Check if a given object implements the EffectNames interface.
 */
export function instanceOfEffectNames(value: object): value is EffectNames {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function EffectNamesFromJSON(json: any): EffectNames {
    return EffectNamesFromJSONTyped(json, false);
}

export function EffectNamesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffectNames {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'value': json['value'],
    };
}

export function EffectNamesToJSON(json: any): EffectNames {
    return EffectNamesToJSONTyped(json, false);
}

export function EffectNamesToJSONTyped(value?: EffectNames | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'value': value['value'],
    };
}

