// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * **Dictionary of favorite colors** saved on device<br> *(Parameters needed to display favorite colors in user interface)*
 * @export
 * @interface FavColors
 */
export interface FavColors {
    /**
     * *Key, (ID)*
     * @type {string}
     * @memberof FavColors
     */
    id: string;
    /**
     * As the name of field says<br><br> **Color value in format: 4 channels (R)(G)(B)(W) or 1 channel (S)**, where <br> every channel can get value between: **00-FF** (HEX) *(DEC: 0-255)*
     * @type {string}
     * @memberof FavColors
     */
    value: string;
}

/**
 * Check if a given object implements the FavColors interface.
 */
export function instanceOfFavColors(value: object): value is FavColors {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function FavColorsFromJSON(json: any): FavColors {
    return FavColorsFromJSONTyped(json, false);
}

export function FavColorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavColors {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'value': json['value'],
    };
}

export function FavColorsToJSON(json: any): FavColors {
    return FavColorsToJSONTyped(json, false);
}

export function FavColorsToJSONTyped(value?: FavColors | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'value': value['value'],
    };
}

