// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldsPreferencesInner
 */
export interface FieldsPreferencesInner {
    /**
     * Name of field
     * @type {string}
     * @memberof FieldsPreferencesInner
     */
    fieldName?: string;
    /**
     * List of allowed values ​​in this field
     * @type {Array<string>}
     * @memberof FieldsPreferencesInner
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the FieldsPreferencesInner interface.
 */
export function instanceOfFieldsPreferencesInner(value: object): value is FieldsPreferencesInner {
    return true;
}

export function FieldsPreferencesInnerFromJSON(json: any): FieldsPreferencesInner {
    return FieldsPreferencesInnerFromJSONTyped(json, false);
}

export function FieldsPreferencesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldsPreferencesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'fieldName': json['field name'] == null ? undefined : json['field name'],
        'values': json['values'] == null ? undefined : json['values'],
    };
}

export function FieldsPreferencesInnerToJSON(json: any): FieldsPreferencesInner {
    return FieldsPreferencesInnerToJSONTyped(json, false);
}

export function FieldsPreferencesInnerToJSONTyped(value?: FieldsPreferencesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field name': value['fieldName'],
        'values': value['values'],
    };
}

