// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Type: wLightBox
 * # Introduction It is **specific API** of BleBox devices with **API type:** *wLightBox* <br><br> **Please check** **API type** and **API level** (version) before use, <br> **if you don\'t see the expected field** in response from a real device then **hardware version do not support this feature**.
 *
 * The version of the OpenAPI document: 20200229
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * **Frequency of LED dimming**. **Useful for filmmakers**. <br> Allowed frequencies depends from hardware/firmware version (field preferences)<br> Frequencies over 1200Hz (not exist in field preferences) and can be set only via API!
 * @export
 */
export const PwmFreq = {
    NUMBER_486: 486,
    NUMBER_600: 600,
    NUMBER_1200: 1200,
    NUMBER_2400: 2400,
    NUMBER_4800: 4800
} as const;
export type PwmFreq = typeof PwmFreq[keyof typeof PwmFreq];


export function instanceOfPwmFreq(value: any): boolean {
    for (const key in PwmFreq) {
        if (Object.prototype.hasOwnProperty.call(PwmFreq, key)) {
            if (PwmFreq[key as keyof typeof PwmFreq] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PwmFreqFromJSON(json: any): PwmFreq {
    return PwmFreqFromJSONTyped(json, false);
}

export function PwmFreqFromJSONTyped(json: any, ignoreDiscriminator: boolean): PwmFreq {
    return json as PwmFreq;
}

export function PwmFreqToJSON(value?: PwmFreq | null): any {
    return value as any;
}

export function PwmFreqToJSONTyped(value: any, ignoreDiscriminator: boolean): PwmFreq {
    return value as PwmFreq;
}

